import { StyleSheet } from 'react-native';

import { colors, radius } from '../../constants/theme';

const MEAL_CARD_IMAGE_HEIGHT = 390;

const mealScreenStyles = StyleSheet.create({
  overlayBackBtn: {
    flexDirection: 'row',
    alignItems: 'center',
    gap: 4,
    paddingHorizontal: 10,
    paddingVertical: 6,
    borderRadius: 999,
    borderWidth: 1,
    alignSelf: 'flex-start',
  },
  overlayBackText: {
    fontSize: 12,
    fontWeight: '700',
  },
  emptyStateCard: {
    padding: 24,
    alignItems: 'center',
    borderRadius: radius.lg,
    borderWidth: 1,
    gap: 8,
  },
  emptyStateTitle: { fontSize: 15, fontWeight: '800', textAlign: 'center' },
  emptyStateBody: { fontSize: 12, lineHeight: 18, textAlign: 'center' },
  historyCalendarScoreBadge: {
    minWidth: 18,
    height: 18,
    borderRadius: 9,
    borderWidth: StyleSheet.hairlineWidth,
    alignItems: 'center',
    justifyContent: 'center',
    paddingHorizontal: 3,
    marginTop: 2,
  },
  historyCalendarScoreText: {
    fontSize: 9,
    lineHeight: 10,
    fontWeight: '900',
    fontVariant: ['tabular-nums'] as any,
    includeFontPadding: false as any,
  },
  historyScoreCircle: {
    minWidth: 40,
    height: 40,
    borderRadius: 20,
    borderWidth: 2,
    alignItems: 'center',
    justifyContent: 'center',
    paddingHorizontal: 4,
    flexShrink: 0,
  },
  historyScoreCircleValue: {
    fontSize: 14,
    lineHeight: 16,
    fontWeight: '900',
    fontVariant: ['tabular-nums'] as any,
    includeFontPadding: false as any,
  },
  historyScoreCircleLabel: {
    fontSize: 6,
    lineHeight: 8,
    fontWeight: '900',
    letterSpacing: 0.3,
    textTransform: 'uppercase',
    marginTop: -1,
    includeFontPadding: false as any,
  },
  labeledActionRow: {
    flexDirection: 'row',
    flexWrap: 'wrap',
    gap: 8,
    marginTop: 4,
    marginBottom: 10,
  },
  labeledActionBtn: {
    flexDirection: 'row',
    alignItems: 'center',
    gap: 6,
    paddingHorizontal: 12,
    paddingVertical: 8,
    borderRadius: 999,
    borderWidth: 1,
    position: 'relative',
    shadowOpacity: 0.12,
    shadowRadius: 10,
    shadowOffset: { width: 0, height: 4 },
    elevation: 2,
  },
  labeledActionGlow: { ...StyleSheet.absoluteFillObject, borderRadius: 999 },
  labeledActionText: {
    fontSize: 12,
    fontWeight: '700',
    letterSpacing: 0.2,
  },
  cardPhotoDarkHueOverlay: { ...StyleSheet.absoluteFillObject, backgroundColor: 'rgba(2,6,23,0.18)' },
  cardPhotoBottomFade: { position: 'absolute', left: 0, right: 0, bottom: 0, height: 120 },
  lightPhotoCopyPanel: {
    marginHorizontal: 14,
    marginTop: 14,
    paddingHorizontal: 12,
    paddingTop: 12,
    paddingBottom: 12,
    borderRadius: 14,
    borderWidth: StyleSheet.hairlineWidth,
  },
  lightPhotoMetricPanel: {
    marginHorizontal: 14,
    marginTop: 8,
    paddingVertical: 4,
    borderRadius: 14,
    borderWidth: StyleSheet.hairlineWidth,
  },
  mealAccordionCard: {
    position: 'relative',
    backgroundColor: colors.surface,
    borderRadius: 22,
    borderWidth: 1,
    borderColor: colors.border,
    marginBottom: 12,
    overflow: 'hidden',
  },
  mealCardImageLayer: {
    position: 'absolute',
    top: 0,
    left: 0,
    right: 0,
    bottom: 0,
    overflow: 'hidden',
  },
  mealCardPhotoTopContent: {
    minHeight: MEAL_CARD_IMAGE_HEIGHT,
    overflow: 'hidden',
  },
  mealCardBackgroundImage: { ...StyleSheet.absoluteFillObject, width: '100%', height: '100%', opacity: 0.62 },
  mealCardBackgroundImageLight: { opacity: 0.18 },
  mealCardForegroundImage: { ...StyleSheet.absoluteFillObject, width: '100%', height: '100%', opacity: 1 },
  mealCardForegroundImageLight: { opacity: 0.96 },
  mealCardBackgroundOverlay: { ...StyleSheet.absoluteFillObject },
  mealAccordionHeader: {
    flexDirection: 'row',
    alignItems: 'center',
    paddingHorizontal: 14,
    paddingVertical: 16,
    borderBottomWidth: 1,
    borderBottomColor: 'transparent',
  },
  mealAccordionTitle: { fontSize: 18, fontWeight: '700', color: colors.textPrimary },
  mealExpansionRail: {
    paddingHorizontal: 16,
    paddingTop: 12,
    paddingBottom: 16,
    marginTop: 0,
    backgroundColor: colors.surface,
  },
  mealHydrationPanel: {
    marginHorizontal: 14,
    marginTop: 0,
    marginBottom: 14,
    padding: 12,
    borderRadius: radius.md,
    borderWidth: 1,
    borderTopWidth: 0,
  },
});

export default mealScreenStyles;
