// Trimmed-down workout + meal models for the watch. The phone's shapes
// are much richer (micronutrients, image URLs, archetype metadata);
// none of that is useful at the wrist, so we send slim structs over
// WatchConnectivity and decode here.

import Foundation

// ─── Workout ─────────────────────────────────────────────────────────

struct WatchExercise: Codable, Identifiable, Equatable {
    var id: String { name }
    let name: String
    let sets: Int
    let reps: String
    let restSeconds: Int
    let equipment: String?
    let plannedTargetWeightLbs: Double?
    let recommendation: String?
    /// "warmup" | "primary" | "secondary" | "isolation" | "core" | "cooldown"
    /// — shown as a badge on the active card so the user knows to
    /// dial intensity up or down for that slot. Optional for back-compat.
    let slotRole: String?
}

/// Lifecycle state of today's workout — the watch renders different
/// UI for each. Mirrors the phone's own state machine: `scheduled`
/// is the default, `active` is the in-progress session, `completed`
/// after the user finishes, `skipped` after tap-skip or swap-to-rest.
enum WatchWorkoutStatus: String, Codable {
    case scheduled
    case active
    case completed
    case skipped
    case rest
}

struct WatchWorkout: Codable, Equatable {
    let focus: String
    let durationMinutes: Int
    let dateISO: String
    let status: WatchWorkoutStatus
    /// Unique per-session identifier. Generated by the phone when a
    /// workout becomes active. The watch uses this to distinguish a
    /// fresh start from a stale `.active` lingering in applicationContext.
    let sessionId: String?
    /// 0-100 readiness score pushed from the phone's preparedness
    /// engine. Nil when HealthKit data is too thin to score.
    let readiness: Int?
    /// "Primed" / "Ready" / "Moderate" / "Fatigued" — same label the
    /// iOS TrainingReadinessCard uses. Shown on Today view as a chip.
    let readinessLabel: String?
    let exercises: [WatchExercise]
    /// Plain-text warm-up bullets from the phone's buildWarmupPlan
    /// (or AI warmup when it resolves). Shown as a dismissable card
    /// on the exercise tab before the first set. Nil / empty = no
    /// warmup (recovery / cardio / cold-start days).
    let warmupSteps: [String]?
    let syncedAtMs: Double
}

// ─── Meals ───────────────────────────────────────────────────────────

struct WatchMealItem: Codable, Identifiable, Equatable {
    var id: String { mealType }
    let mealType: String
    let name: String
    let calories: Int
    let proteinG: Int
    let carbsG: Int
    let fatG: Int
    let checked: Bool
}

struct WatchMealTargets: Codable, Equatable {
    let calories: Int
    let proteinG: Int
    let carbsG: Int
    let fatG: Int
}

struct WatchMealsDay: Codable, Equatable {
    let dateISO: String
    let targets: WatchMealTargets
    let actual: WatchMealTargets
    /// 0-100 unified Nutrition Score (adherence + quality + micro).
    /// Matches what /meals/score returns on the phone. Nil when the
    /// day has no logged meals yet.
    let score: Int?
    let meals: [WatchMealItem]
    let syncedAtMs: Double
}

// ─── Supplements ─────────────────────────────────────────────────────

struct WatchSupplementItem: Codable, Identifiable, Equatable {
    /// Stable per-stack-item id — matches the phone's StackItem.id so
    /// watch-originated "take" commands can round-trip to api.logDose
    /// without the watch needing to know the full product taxonomy.
    let id: Int
    let name: String
    let dose: String?       // pre-formatted "200 IU" / "5 g" etc
    let timing: String?     // "morning" / "with_food" / "post_workout"
    let taken: Bool
    let skipped: Bool
}

struct WatchSupplementsDay: Codable, Equatable {
    let dateISO: String
    let items: [WatchSupplementItem]
    let syncedAtMs: Double
}

// ─── Sleep ──────────────────────────────────────────────────────────

// ─── Readiness drill-down ──────────────────────────────────────────

struct WatchReadinessFactor: Codable, Equatable {
    /// "Sleep" / "RHR" / "HRV" / "Recovery" / "Fueling".
    let label: String
    /// 0–100 sub-score for that factor. Watch renders as a colored bar.
    let value: Int
    /// "good" / "ok" / "low" — drives the bar color independent of value.
    let status: String
    /// Short human note like "7.4h last night" or "elevated 4 bpm".
    let detail: String?
}

struct WatchReadinessSnapshot: Codable, Equatable {
    /// 0–100 composite readiness (mirrors the phone's TrainingReadinessCard).
    let score: Int?
    /// "Primed" / "Ready" / "Moderate" / "Fatigued" / "Hold" — same
    /// label set the phone surfaces.
    let label: String?
    /// One-line takeaway phrased like a coach.
    let summary: String?
    /// Per-factor breakdown so the user sees which signals are low.
    let factors: [WatchReadinessFactor]
    let syncedAtMs: Double
}

// ─── Body weight quick-log ─────────────────────────────────────────

struct WatchWeightSnapshot: Codable, Equatable {
    /// Most recently logged weight (lbs). Used to seed the Digital
    /// Crown wheel so the user lands on a sensible value.
    let latestLbs: Double?
    /// Days since the last log — drives the "log today" prompt.
    let daysSinceLastLog: Int?
    /// 7-day EMA trend for the headline display.
    let emaLbs: Double?
    /// Slope in lbs/wk — positive = gaining, negative = losing.
    let slopeLbsPerWeek: Double?
    let syncedAtMs: Double
}

struct WatchSleepSnapshot: Codable, Equatable {
    /// 0–100 sleep score. Mirrors the phone's `scoreSleep()` output.
    let score: Int?
    /// Hours slept last night (in-bed time, not strictly asleep).
    let hoursLastNight: Double?
    /// Minutes of asleep / awake / REM / deep / core if HK provided
    /// stage breakdown; nil otherwise.
    let asleepMin: Int?
    let remMin: Int?
    let deepMin: Int?
    /// Resting heart rate (latest 7-day average from HealthKit).
    let restingHr: Int?
    /// Average HRV over recent days (ms); nil if HRV not authorised.
    let hrvMs: Int?
    /// Short label: "Excellent" / "Good" / "OK" / "Low".
    let label: String?
    /// Brief one-line takeaway phrased like a coach's note.
    let summary: String?
    let syncedAtMs: Double
}
