// Motivational phrases shown at the end of the 3-2-1 countdown when
// a workout starts. Kept short (≤ ~16 chars) so they render on the
// Apple Watch without truncating.
//
// ⚠️ Sync rule: if you change this list, mirror it in
// `targets/thallo-watch/ActiveWorkoutView.swift` under
// `StartCountdownOverlay.phrases`. Both surfaces roll their own
// random pick so the two don't need to be exactly the same at run
// time — but the POOL should stay identical.

export const START_PHRASES: readonly string[] = [
  "LET'S GO!",
  "LIGHTS OUT.",
  "LOCK IN.",
  "SHOW UP.",
  "EARN IT.",
  "GAME TIME.",
  "DIG IN.",
  "RISE UP.",
  "YOUR MOVE.",
  "MAKE IT COUNT.",
  "NO EXCUSES.",
  "LEAVE IT ALL.",
  "BEAST MODE.",
  "FULL SEND.",
  "STAY HUNGRY.",
  "GRIND ON.",
  "BREAK LIMITS.",
  "OWN IT.",
  "ATTACK.",
  "NO MERCY.",
  "DOMINATE.",
  "FOCUS UP.",
  "LEVEL UP.",
  "WORK.",
  "PUSH HARDER.",
  "HEART IN.",
  "BRING HEAT.",
  "GO TIME.",
  "CLAIM IT.",
  "NO QUIT.",
  "OUTWORK.",
  "SEND IT.",
  "WAR MODE.",
  "NEXT REP.",
  "UNLEASH.",
  "RAW POWER.",
  "STAY SHARP.",
  "BE RUTHLESS.",
  "ALL IN.",
  "TRUST IT.",
  "TUNE IN.",
  "DRIVE.",
  "KEEP GOING.",
  "EVERY REP.",
  "EARN TODAY.",
  "FUEL UP.",
  "OUTLAST.",
  "WIN REPS.",
  "CRUSH IT.",
  "OWN THE HOUR.",
  "LIGHT IT UP.",
  "KEEP PUSHING.",
  "SWEAT NOW.",
  "NO OFF DAYS.",
  "RAISE THE BAR.",
  "HEAD DOWN.",
  "CHIN UP.",
  "STAY STRONG.",
  "HOLD THE LINE.",
  "OUTGRIND.",
  "FIRE UP.",
  "BE THE WORK.",
  "NO COMFORT.",
  "HUSTLE.",
  "SAVAGE.",
  "GO BIG.",
  "ONE MORE.",
  "EFFORT FIRST.",
  "BEAT YESTERDAY.",
  "MAKE MOVES.",
  "PROVE IT.",
  "STACK WINS.",
  "MOVE WEIGHT.",
  "BUILD IT.",
  "OWN THE DAY.",
  "DIAL IN.",
  "RAISE HELL.",
  "UNBROKEN.",
  "BURN IT.",
  "SET PACE.",
  "SPARK UP.",
  "GO HEAVIER.",
  "NO STEP BACK.",
  "PRIDE ON.",
  "NOTHING EASY.",
  "FORGE ON.",
  "RUN IT UP.",
  "WORK SPEAKS.",
  "KEEP EDGE.",
  "BREAKTHROUGH.",
  "HEAT CHECK.",
  "GO AGAIN.",
  "FULL BORE.",
  "GAME ON.",
  "DO THE WORK.",
  "REP FOR REP.",
  "RISE TO IT.",
  "MAKE THEM LOOK.",
  "STRONGER TODAY.",
  "FINISH STRONG.",
  "NO BLINKING.",
];
