import { Alert, Share } from 'react-native';
import { loadWorkoutHistory } from './workoutHistory';
import { loadWeightHistory } from './weightHistory';
import { THALLO_LOGO_BLACK_B64 } from './logoBase64';

function formatDuration(secs: number): string {
  const m = Math.floor(secs / 60);
  return m >= 60 ? `${Math.floor(m / 60)}h ${m % 60}m` : `${m}m`;
}

function generateWorkoutHTML(history: any[]): string {
  const cards = history.map(s => {
    const date = new Date(s.date);
    const dateStr = date.toLocaleDateString('en-US', { weekday: 'short', month: 'short', day: 'numeric' });
    const dur = formatDuration(s.durationSeconds || 0);
    const exercises = (s.exercises ?? []).map((ex: any) => {
      const sets = (ex.sets ?? []).map((set: any, i: number) => {
        if (set.durationSeconds) return `${Math.floor(set.durationSeconds / 60)}:${(set.durationSeconds % 60).toString().padStart(2, '0')}`;
        return `${set.weightLbs || 0}×${set.reps || 0}`;
      });
      return `<tr>
        <td class="ex-name">${ex.name}</td>
        <td class="ex-sets">${sets.join(' · ') || '—'}</td>
      </tr>`;
    }).join('');

    return `<div class="card">
      <div class="card-header">
        <div class="card-top">
          <span class="focus">${s.focus || 'Workout'}</span>
          <span class="duration">${dur}</span>
        </div>
        <div class="date">${dateStr}</div>
      </div>
      ${exercises ? `<table class="ex-table">${exercises}</table>` : '<p class="empty">No details</p>'}
    </div>`;
  }).join('');

  const totalSets = history.reduce((s, w) => s + (w.exercises ?? []).reduce((es: number, ex: any) => es + (ex.sets?.length ?? 0), 0), 0);
  const totalHours = Math.round(history.reduce((s, w) => s + (w.durationSeconds || 0), 0) / 3600 * 10) / 10;

  return `<!DOCTYPE html>
<html>
<head>
<meta charset="utf-8">
<style>
  @page { margin: 14mm 10mm; }
  * { margin: 0; padding: 0; box-sizing: border-box; }
  body { font-family: -apple-system, Helvetica, Arial, sans-serif; color: #1a1a1a; font-size: 9px; line-height: 1.3; }
  .header { text-align: center; margin-bottom: 12px; padding-bottom: 8px; border-bottom: 1.5px solid #ddd; }
  .header img { height: 48px; margin-bottom: 2px; }
  .header .sub { font-size: 9px; color: #555; }
  .grid { display: flex; flex-wrap: wrap; gap: 6px; }
  .card { width: calc(50% - 3px); border: 1px solid #e0e0e0; border-radius: 5px; padding: 6px 8px; page-break-inside: avoid; }
  .card-header { margin-bottom: 3px; }
  .card-top { display: flex; justify-content: space-between; align-items: center; }
  .focus { font-size: 11px; font-weight: 700; color: #111; }
  .duration { font-size: 8px; font-weight: 600; color: #555; background: #f0f0f0; padding: 1px 5px; border-radius: 3px; }
  .date { font-size: 8px; color: #444; }
  .ex-table { width: 100%; border-collapse: collapse; }
  .ex-table tr { border-top: 1px solid #f4f4f4; }
  .ex-table tr:first-child { border-top: none; }
  .ex-name { font-size: 9px; font-weight: 600; color: #222; padding: 2px 0; }
  .ex-sets { font-size: 8px; color: #555; text-align: right; padding: 2px 0; white-space: nowrap; }
  .empty { font-size: 8px; color: #bbb; font-style: italic; }
  .footer { text-align: center; margin-top: 8px; padding-top: 6px; border-top: 1px solid #e0e0e0; }
  .footer-text { font-size: 7px; color: #ccc; }
</style>
</head>
<body>
  <div class="header">
    <img src="data:image/png;base64,${THALLO_LOGO_BLACK_B64}" alt="Thallo" />
    <div class="sub">Workout History</div>
  </div>
  <div class="grid">
  ${cards}
  </div>
  <div class="footer"><div class="footer-text">Generated by Thallo · ${new Date().toLocaleDateString()}</div></div>
</body>
</html>`;
}

async function shareFile(filename: string, content: string, mimeType: string): Promise<void> {
  let path: string | null = null;
  try {
    const FS = require('expo-file-system');
    const Sharing = require('expo-sharing');
    const dir = FS.cacheDirectory || FS.documentDirectory;
    if (dir) {
      path = dir + filename;
      await FS.writeAsStringAsync(path, content, { encoding: FS.EncodingType.UTF8 });
      if (await Sharing.isAvailableAsync()) {
        try {
          await Sharing.shareAsync(path, { mimeType, dialogTitle: `Share ${filename}` });
        } finally {
          await FS.deleteAsync(path, { idempotent: true }).catch(() => {});
        }
        return;
      }
      await FS.deleteAsync(path, { idempotent: true }).catch(() => {});
    }
  } catch {}
  await Share.share({ message: content, title: filename });
}

async function sharePDF(filename: string, html: string): Promise<void> {
  let uri: string | null = null;
  try {
    const Print = require('expo-print');
    const Sharing = require('expo-sharing');
    const FS = require('expo-file-system');
    const result = await Print.printToFileAsync({ html, base64: false });
    uri = result.uri;
    if (await Sharing.isAvailableAsync()) {
      try {
        await Sharing.shareAsync(uri, { mimeType: 'application/pdf', dialogTitle: `Share ${filename}` });
      } finally {
        await FS.deleteAsync(uri, { idempotent: true }).catch(() => {});
      }
      return;
    }
    await FS.deleteAsync(uri, { idempotent: true }).catch(() => {});
  } catch (e) {
    console.log('[export] PDF generation failed, falling back to HTML:', e);
  }
  await shareFile(filename.replace('.pdf', '.html'), html, 'text/html');
}

export async function exportWorkoutHistory(username?: string): Promise<void> {
  const history = await loadWorkoutHistory();
  if (!history.length) {
    Alert.alert('No data', 'Complete a workout first to have data to export.');
    return;
  }
  const html = generateWorkoutHTML(history);
  const name = (username || 'workout').replace(/\s+/g, '_').toLowerCase();
  const date = new Date().toISOString().slice(0, 10);
  await sharePDF(`${name}_${date}_history.pdf`, html);
}

export async function exportWeightHistory(): Promise<void> {
  const history = await loadWeightHistory();
  if (!history.length) {
    Alert.alert('No data', 'Log your weight first to have data to export.');
    return;
  }
  const rows = ['Date,Weight (lbs),Source'];
  for (const e of history) {
    rows.push(`${e.date},${e.weightLbs},${e.source ?? 'manual'}`);
  }
  await shareFile('thallo_weight.csv', rows.join('\n'), 'text/csv');
}

export async function exportAccountDataJson(data: unknown, username?: string): Promise<void> {
  const safeName = (username || 'account').replace(/[^a-z0-9_-]+/gi, '_').toLowerCase();
  const date = new Date().toISOString().slice(0, 10);
  await shareFile(`thallo_${safeName}_${date}_account_export.json`, JSON.stringify(data, null, 2), 'application/json');
}
