// AUTO-GENERATED - do not edit by hand.
// Source: assets/full-library.zip via scripts/sync-move-kit-demos.mjs

export type MoveKitExerciseVideo = {
  readonly source: number;
  readonly filename: string;
  readonly label: string;
};

const MOVE_KIT_FILES = {
  BAND_CURL: {
    source: require('../../assets/exercise-videos/move-kit/band-curl.mp4'),
    filename: 'band-curl.mp4',
    label: 'Band Curl',
  },
  BAND_HIGH_FACE_PULL: {
    source: require('../../assets/exercise-videos/move-kit/band-high-face-pull.mp4'),
    filename: 'band-high-face-pull.mp4',
    label: 'Band High Face Pull',
  },
  BAND_ROW: {
    source: require('../../assets/exercise-videos/move-kit/band-row.mp4'),
    filename: 'band-row.mp4',
    label: 'Band Row',
  },
  BARBELL_BENCH_PRESS: {
    source: require('../../assets/exercise-videos/move-kit/barbell-bench-press.mp4'),
    filename: 'barbell-bench-press.mp4',
    label: 'Barbell Bench Press',
  },
  BARBELL_BENT_OVER_ROW: {
    source: require('../../assets/exercise-videos/move-kit/barbell-bent-over-row.mp4'),
    filename: 'barbell-bent-over-row.mp4',
    label: 'Barbell Bent Over Row',
  },
  BARBELL_CLOSE_GRIP_BENCH_PRESS: {
    source: require('../../assets/exercise-videos/move-kit/barbell-close-grip-bench-press.mp4'),
    filename: 'barbell-close-grip-bench-press.mp4',
    label: 'Barbell Close Grip Bench Press',
  },
  BARBELL_CURL: {
    source: require('../../assets/exercise-videos/move-kit/barbell-curl.mp4'),
    filename: 'barbell-curl.mp4',
    label: 'Barbell Curl',
  },
  BARBELL_DEADLIFT: {
    source: require('../../assets/exercise-videos/move-kit/barbell-deadlift.mp4'),
    filename: 'barbell-deadlift.mp4',
    label: 'Barbell Deadlift',
  },
  BARBELL_DRAG_CURL: {
    source: require('../../assets/exercise-videos/move-kit/barbell-drag-curl.mp4'),
    filename: 'barbell-drag-curl.mp4',
    label: 'Barbell Drag Curl',
  },
  BARBELL_INCLINE_BENCH_PRESS: {
    source: require('../../assets/exercise-videos/move-kit/barbell-incline-bench-press.mp4'),
    filename: 'barbell-incline-bench-press.mp4',
    label: 'Barbell Incline Bench Press',
  },
  BARBELL_OVERHEAD_PRESS: {
    source: require('../../assets/exercise-videos/move-kit/barbell-overhead-press.mp4'),
    filename: 'barbell-overhead-press.mp4',
    label: 'Barbell Overhead Press',
  },
  BARBELL_POWER_SNATCH: {
    source: require('../../assets/exercise-videos/move-kit/barbell-power-snatch.mp4'),
    filename: 'barbell-power-snatch.mp4',
    label: 'Barbell Power Snatch',
  },
  BARBELL_RACK_PULL: {
    source: require('../../assets/exercise-videos/move-kit/barbell-rack-pull.mp4'),
    filename: 'barbell-rack-pull.mp4',
    label: 'Barbell Rack Pull',
  },
  BARBELL_SHRUG: {
    source: require('../../assets/exercise-videos/move-kit/barbell-shrug.mp4'),
    filename: 'barbell-shrug.mp4',
    label: 'Barbell Shrug',
  },
  BARBELL_SQUAT: {
    source: require('../../assets/exercise-videos/move-kit/barbell-squat.mp4'),
    filename: 'barbell-squat.mp4',
    label: 'Barbell Squat',
  },
  BARBELL_STIFF_LEG_DEADLIFTS: {
    source: require('../../assets/exercise-videos/move-kit/barbell-stiff-leg-deadlifts.mp4'),
    filename: 'barbell-stiff-leg-deadlifts.mp4',
    label: 'Barbell Stiff Leg Deadlifts',
  },
  BARBELL_UPRIGHT_ROW: {
    source: require('../../assets/exercise-videos/move-kit/barbell-upright-row.mp4'),
    filename: 'barbell-upright-row.mp4',
    label: 'Barbell Upright Row',
  },
  BENCH_DIPS: {
    source: require('../../assets/exercise-videos/move-kit/bench-dips.mp4'),
    filename: 'bench-dips.mp4',
    label: 'Bench Dips',
  },
  BODYWEIGHT_ALTERNATING_LATERAL_LUNGE: {
    source: require('../../assets/exercise-videos/move-kit/bodyweight-alternating-lateral-lunge.mp4'),
    filename: 'bodyweight-alternating-lateral-lunge.mp4',
    label: 'Bodyweight Alternating Lateral Lunge',
  },
  BODYWEIGHT_DONKEY_CALF_RAISE: {
    source: require('../../assets/exercise-videos/move-kit/bodyweight-donkey-calf-raise.mp4'),
    filename: 'bodyweight-donkey-calf-raise.mp4',
    label: 'Bodyweight Donkey Calf Raise',
  },
  BODYWEIGHT_REVERSE_LUNGE: {
    source: require('../../assets/exercise-videos/move-kit/bodyweight-reverse-lunge.mp4'),
    filename: 'bodyweight-reverse-lunge.mp4',
    label: 'Bodyweight Reverse Lunge',
  },
  BODYWEIGHT_RUSSIAN_TWIST: {
    source: require('../../assets/exercise-videos/move-kit/bodyweight-russian-twist.mp4'),
    filename: 'bodyweight-russian-twist.mp4',
    label: 'Bodyweight Russian Twist',
  },
  BODYWEIGHT_SQUAT: {
    source: require('../../assets/exercise-videos/move-kit/bodyweight-squat.mp4'),
    filename: 'bodyweight-squat.mp4',
    label: 'Bodyweight Squat',
  },
  BOX_JUMP: {
    source: require('../../assets/exercise-videos/move-kit/box-jump.mp4'),
    filename: 'box-jump.mp4',
    label: 'Box Jump',
  },
  BULGARIAN_SPLIT_SQUAT: {
    source: require('../../assets/exercise-videos/move-kit/bulgarian-split-squat.mp4'),
    filename: 'bulgarian-split-squat.mp4',
    label: 'Bulgarian Split Squat',
  },
  BURPEE: {
    source: require('../../assets/exercise-videos/move-kit/burpee.mp4'),
    filename: 'burpee.mp4',
    label: 'Burpee',
  },
  CABLE_BAR_CURL: {
    source: require('../../assets/exercise-videos/move-kit/cable-bar-curl.mp4'),
    filename: 'cable-bar-curl.mp4',
    label: 'Cable Bar Curl',
  },
  CABLE_BAR_FACE_PULL: {
    source: require('../../assets/exercise-videos/move-kit/cable-bar-face-pull.mp4'),
    filename: 'cable-bar-face-pull.mp4',
    label: 'Cable Bar Face Pull',
  },
  CABLE_BAR_PUSHDOWN: {
    source: require('../../assets/exercise-videos/move-kit/cable-bar-pushdown.mp4'),
    filename: 'cable-bar-pushdown.mp4',
    label: 'Cable Bar Pushdown',
  },
  CABLE_CHEST_PRESS: {
    source: require('../../assets/exercise-videos/move-kit/cable-chest-press.mp4'),
    filename: 'cable-chest-press.mp4',
    label: 'Cable Chest Press',
  },
  CABLE_PEC_FLY: {
    source: require('../../assets/exercise-videos/move-kit/cable-pec-fly.mp4'),
    filename: 'cable-pec-fly.mp4',
    label: 'Cable Pec Fly',
  },
  CABLE_ROPE_PUSHDOWN: {
    source: require('../../assets/exercise-videos/move-kit/cable-rope-pushdown.mp4'),
    filename: 'cable-rope-pushdown.mp4',
    label: 'Cable Rope Pushdown',
  },
  CABLE_SINGLE_ARM_NEUTRAL_GRIP_ROW: {
    source: require('../../assets/exercise-videos/move-kit/cable-single-arm-neutral-grip-row.mp4'),
    filename: 'cable-single-arm-neutral-grip-row.mp4',
    label: 'Cable Single Arm Neutral Grip Row',
  },
  CABLE_SINGLE_ARM_ROPE_PUSHDOWN: {
    source: require('../../assets/exercise-videos/move-kit/cable-single-arm-rope-pushdown.mp4'),
    filename: 'cable-single-arm-rope-pushdown.mp4',
    label: 'Cable Single Arm Rope Pushdown',
  },
  CABLE_STANDING_SINGLE_ARM_CHEST_PRESS: {
    source: require('../../assets/exercise-videos/move-kit/cable-standing-single-arm-chest-press.mp4'),
    filename: 'cable-standing-single-arm-chest-press.mp4',
    label: 'Cable Standing Single Arm Chest Press',
  },
  CABLE_WOOD_CHOPPER: {
    source: require('../../assets/exercise-videos/move-kit/cable-wood-chopper.mp4'),
    filename: 'cable-wood-chopper.mp4',
    label: 'Cable Wood Chopper',
  },
  CHIN_UPS: {
    source: require('../../assets/exercise-videos/move-kit/chin-ups.mp4'),
    filename: 'chin-ups.mp4',
    label: 'Chin Ups',
  },
  DECLINE_PUSH_UP: {
    source: require('../../assets/exercise-videos/move-kit/decline-push-up.mp4'),
    filename: 'decline-push-up.mp4',
    label: 'Decline Push Up',
  },
  DIAMOND_PUSH_UPS: {
    source: require('../../assets/exercise-videos/move-kit/diamond-push-ups.mp4'),
    filename: 'diamond-push-ups.mp4',
    label: 'Diamond Push Ups',
  },
  DUMBBELL_BENCH_PRESS: {
    source: require('../../assets/exercise-videos/move-kit/dumbbell-bench-press.mp4'),
    filename: 'dumbbell-bench-press.mp4',
    label: 'Dumbbell Bench Press',
  },
  DUMBBELL_CHEST_FLY: {
    source: require('../../assets/exercise-videos/move-kit/dumbbell-chest-fly.mp4'),
    filename: 'dumbbell-chest-fly.mp4',
    label: 'Dumbbell Chest Fly',
  },
  DUMBBELL_CONCENTRATION_CURL: {
    source: require('../../assets/exercise-videos/move-kit/dumbbell-concentration-curl.mp4'),
    filename: 'dumbbell-concentration-curl.mp4',
    label: 'Dumbbell Concentration Curl',
  },
  DUMBBELL_CURL: {
    source: require('../../assets/exercise-videos/move-kit/dumbbell-curl.mp4'),
    filename: 'dumbbell-curl.mp4',
    label: 'Dumbbell Curl',
  },
  DUMBBELL_DECLINE_BENCH_PRESS: {
    source: require('../../assets/exercise-videos/move-kit/dumbbell-decline-bench-press.mp4'),
    filename: 'dumbbell-decline-bench-press.mp4',
    label: 'Dumbbell Decline Bench Press',
  },
  DUMBBELL_FRONT_RAISE: {
    source: require('../../assets/exercise-videos/move-kit/dumbbell-front-raise.mp4'),
    filename: 'dumbbell-front-raise.mp4',
    label: 'Dumbbell Front Raise',
  },
  DUMBBELL_GOBLET_SPLIT_SQUAT: {
    source: require('../../assets/exercise-videos/move-kit/dumbbell-goblet-split-squat.mp4'),
    filename: 'dumbbell-goblet-split-squat.mp4',
    label: 'Dumbbell Goblet Split Squat',
  },
  DUMBBELL_GOBLET_SQUAT: {
    source: require('../../assets/exercise-videos/move-kit/dumbbell-goblet-squat.mp4'),
    filename: 'dumbbell-goblet-squat.mp4',
    label: 'Dumbbell Goblet Squat',
  },
  DUMBBELL_HAMMER_CURL: {
    source: require('../../assets/exercise-videos/move-kit/dumbbell-hammer-curl.mp4'),
    filename: 'dumbbell-hammer-curl.mp4',
    label: 'Dumbbell Hammer Curl',
  },
  DUMBBELL_INCLINE_BENCH_PRESS: {
    source: require('../../assets/exercise-videos/move-kit/dumbbell-incline-bench-press.mp4'),
    filename: 'dumbbell-incline-bench-press.mp4',
    label: 'Dumbbell Incline Bench Press',
  },
  DUMBBELL_INCLINE_CHEST_FLY: {
    source: require('../../assets/exercise-videos/move-kit/dumbbell-incline-chest-fly.mp4'),
    filename: 'dumbbell-incline-chest-fly.mp4',
    label: 'Dumbbell Incline Chest Fly',
  },
  DUMBBELL_INCLINE_CURL: {
    source: require('../../assets/exercise-videos/move-kit/dumbbell-incline-curl.mp4'),
    filename: 'dumbbell-incline-curl.mp4',
    label: 'Dumbbell Incline Curl',
  },
  DUMBBELL_INCLINE_HAMMER_CURL: {
    source: require('../../assets/exercise-videos/move-kit/dumbbell-incline-hammer-curl.mp4'),
    filename: 'dumbbell-incline-hammer-curl.mp4',
    label: 'Dumbbell Incline Hammer Curl',
  },
  DUMBBELL_LATERAL_RAISE: {
    source: require('../../assets/exercise-videos/move-kit/dumbbell-lateral-raise.mp4'),
    filename: 'dumbbell-lateral-raise.mp4',
    label: 'Dumbbell Lateral Raise',
  },
  DUMBBELL_PREACHER_CURL: {
    source: require('../../assets/exercise-videos/move-kit/dumbbell-preacher-curl.mp4'),
    filename: 'dumbbell-preacher-curl.mp4',
    label: 'Dumbbell Preacher Curl',
  },
  DUMBBELL_REAR_DELT_FLY: {
    source: require('../../assets/exercise-videos/move-kit/dumbbell-rear-delt-fly.mp4'),
    filename: 'dumbbell-rear-delt-fly.mp4',
    label: 'Dumbbell Rear Delt Fly',
  },
  DUMBBELL_ROW_UNILATERAL: {
    source: require('../../assets/exercise-videos/move-kit/dumbbell-row-unilateral.mp4'),
    filename: 'dumbbell-row-unilateral.mp4',
    label: 'Dumbbell Row Unilateral',
  },
  DUMBBELL_SEATED_OVERHEAD_PRESS: {
    source: require('../../assets/exercise-videos/move-kit/dumbbell-seated-overhead-press.mp4'),
    filename: 'dumbbell-seated-overhead-press.mp4',
    label: 'Dumbbell Seated Overhead Press',
  },
  DUMBBELL_SEATED_OVERHEAD_TRICEP_EXTENSION: {
    source: require('../../assets/exercise-videos/move-kit/dumbbell-seated-overhead-tricep-extension.mp4'),
    filename: 'dumbbell-seated-overhead-tricep-extension.mp4',
    label: 'Dumbbell Seated Overhead Tricep Extension',
  },
  DUMBBELL_SHRUG: {
    source: require('../../assets/exercise-videos/move-kit/dumbbell-shrug.mp4'),
    filename: 'dumbbell-shrug.mp4',
    label: 'Dumbbell Shrug',
  },
  DUMBBELL_SINGLE_ARM_CHEST_PRESS: {
    source: require('../../assets/exercise-videos/move-kit/dumbbell-single-arm-chest-press.mp4'),
    filename: 'dumbbell-single-arm-chest-press.mp4',
    label: 'Dumbbell Single Arm Chest Press',
  },
  DUMBBELL_SINGLE_LEG_CALF_RAISE: {
    source: require('../../assets/exercise-videos/move-kit/dumbbell-single-leg-calf-raise.mp4'),
    filename: 'dumbbell-single-leg-calf-raise.mp4',
    label: 'Dumbbell Single Leg Calf Raise',
  },
  DUMBBELL_SITUP: {
    source: require('../../assets/exercise-videos/move-kit/dumbbell-situp.mp4'),
    filename: 'dumbbell-situp.mp4',
    label: 'Dumbbell Situp',
  },
  DUMBBELL_SKULLCRUSHER: {
    source: require('../../assets/exercise-videos/move-kit/dumbbell-skullcrusher.mp4'),
    filename: 'dumbbell-skullcrusher.mp4',
    label: 'Dumbbell Skullcrusher',
  },
  DUMBBELL_SUMO_SQUAT: {
    source: require('../../assets/exercise-videos/move-kit/dumbbell-sumo-squat.mp4'),
    filename: 'dumbbell-sumo-squat.mp4',
    label: 'Dumbbell Sumo Squat',
  },
  DUMBBELL_THRUSTER: {
    source: require('../../assets/exercise-videos/move-kit/dumbbell-thruster.mp4'),
    filename: 'dumbbell-thruster.mp4',
    label: 'Dumbbell Thruster',
  },
  DUMBBELL_TRICEP_KICKBACK: {
    source: require('../../assets/exercise-videos/move-kit/dumbbell-tricep-kickback.mp4'),
    filename: 'dumbbell-tricep-kickback.mp4',
    label: 'Dumbbell Tricep Kickback',
  },
  DUMBBELL_WRIST_CURL: {
    source: require('../../assets/exercise-videos/move-kit/dumbbell-wrist-curl.mp4'),
    filename: 'dumbbell-wrist-curl.mp4',
    label: 'Dumbbell Wrist Curl',
  },
  ELBOW_SIDE_PLANK: {
    source: require('../../assets/exercise-videos/move-kit/elbow-side-plank.mp4'),
    filename: 'elbow-side-plank.mp4',
    label: 'Elbow Side Plank',
  },
  GOOD_MORNINGS: {
    source: require('../../assets/exercise-videos/move-kit/good-mornings.mp4'),
    filename: 'good-mornings.mp4',
    label: 'Good Mornings',
  },
  HAND_PLANK: {
    source: require('../../assets/exercise-videos/move-kit/hand-plank.mp4'),
    filename: 'hand-plank.mp4',
    label: 'Hand Plank',
  },
  HANGING_KNEE_RAISES: {
    source: require('../../assets/exercise-videos/move-kit/hanging-knee-raises.mp4'),
    filename: 'hanging-knee-raises.mp4',
    label: 'Hanging Knee Raises',
  },
  INCLINE_PUSH_UP: {
    source: require('../../assets/exercise-videos/move-kit/incline-push-up.mp4'),
    filename: 'incline-push-up.mp4',
    label: 'Incline Push Up',
  },
  INVERTED_ROW: {
    source: require('../../assets/exercise-videos/move-kit/inverted-row.mp4'),
    filename: 'inverted-row.mp4',
    label: 'Inverted Row',
  },
  JUMP_SQUATS: {
    source: require('../../assets/exercise-videos/move-kit/jump-squats.mp4'),
    filename: 'jump-squats.mp4',
    label: 'Jump Squats',
  },
  KETTLEBELL_ROW: {
    source: require('../../assets/exercise-videos/move-kit/kettlebell-row.mp4'),
    filename: 'kettlebell-row.mp4',
    label: 'Kettlebell Row',
  },
  KETTLEBELL_SWING: {
    source: require('../../assets/exercise-videos/move-kit/kettlebell-swing.mp4'),
    filename: 'kettlebell-swing.mp4',
    label: 'Kettlebell Swing',
  },
  KETTLEBELL_THRUSTER: {
    source: require('../../assets/exercise-videos/move-kit/kettlebell-thruster.mp4'),
    filename: 'kettlebell-thruster.mp4',
    label: 'Kettlebell Thruster',
  },
  KETTLEBELL_WINDMILL: {
    source: require('../../assets/exercise-videos/move-kit/kettlebell-windmill.mp4'),
    filename: 'kettlebell-windmill.mp4',
    label: 'Kettlebell Windmill',
  },
  LANDMINE_T_BAR_ROWS: {
    source: require('../../assets/exercise-videos/move-kit/landmine-t-bar-rows.mp4'),
    filename: 'landmine-t-bar-rows.mp4',
    label: 'Landmine T Bar Rows',
  },
  LUNGE_WALKING: {
    source: require('../../assets/exercise-videos/move-kit/lunge-walking.mp4'),
    filename: 'lunge-walking.mp4',
    label: 'Lunge Walking',
  },
  MACHINE_45_DEGREE_BACK_EXTENSION: {
    source: require('../../assets/exercise-videos/move-kit/machine-45-degree-back-extension.mp4'),
    filename: 'machine-45-degree-back-extension.mp4',
    label: 'Machine 45 Degree Back Extension',
  },
  MACHINE_CHEST_PRESS: {
    source: require('../../assets/exercise-videos/move-kit/machine-chest-press.mp4'),
    filename: 'machine-chest-press.mp4',
    label: 'Machine Chest Press',
  },
  MACHINE_CRUNCH: {
    source: require('../../assets/exercise-videos/move-kit/machine-crunch.mp4'),
    filename: 'machine-crunch.mp4',
    label: 'Machine Crunch',
  },
  MACHINE_DIPS: {
    source: require('../../assets/exercise-videos/move-kit/machine-dips.mp4'),
    filename: 'machine-dips.mp4',
    label: 'Machine Dips',
  },
  MACHINE_FRONT_MILITARY_PRESS: {
    source: require('../../assets/exercise-videos/move-kit/machine-front-military-press.mp4'),
    filename: 'machine-front-military-press.mp4',
    label: 'Machine Front Military Press',
  },
  MACHINE_LEG_EXTENSION: {
    source: require('../../assets/exercise-videos/move-kit/machine-leg-extension.mp4'),
    filename: 'machine-leg-extension.mp4',
    label: 'Machine Leg Extension',
  },
  MACHINE_LEG_PRESS: {
    source: require('../../assets/exercise-videos/move-kit/machine-leg-press.mp4'),
    filename: 'machine-leg-press.mp4',
    label: 'Machine Leg Press',
  },
  MACHINE_NEUTRAL_ROW: {
    source: require('../../assets/exercise-videos/move-kit/machine-neutral-row.mp4'),
    filename: 'machine-neutral-row.mp4',
    label: 'Machine Neutral Row',
  },
  MACHINE_PEC_FLY: {
    source: require('../../assets/exercise-videos/move-kit/machine-pec-fly.mp4'),
    filename: 'machine-pec-fly.mp4',
    label: 'Machine Pec Fly',
  },
  MACHINE_PULLDOWN: {
    source: require('../../assets/exercise-videos/move-kit/machine-pulldown.mp4'),
    filename: 'machine-pulldown.mp4',
    label: 'Machine Pulldown',
  },
  MACHINE_SEATED_CABLE_ROW: {
    source: require('../../assets/exercise-videos/move-kit/machine-seated-cable-row.mp4'),
    filename: 'machine-seated-cable-row.mp4',
    label: 'Machine Seated Cable Row',
  },
  MOUNTAIN_CLIMBER: {
    source: require('../../assets/exercise-videos/move-kit/mountain-climber.mp4'),
    filename: 'mountain-climber.mp4',
    label: 'Mountain Climber',
  },
  NARROW_PULLDOWN: {
    source: require('../../assets/exercise-videos/move-kit/narrow-pulldown.mp4'),
    filename: 'narrow-pulldown.mp4',
    label: 'Narrow Pulldown',
  },
  PARRALEL_BAR_DIPS: {
    source: require('../../assets/exercise-videos/move-kit/parralel-bar-dips.mp4'),
    filename: 'parralel-bar-dips.mp4',
    label: 'Parralel Bar Dips',
  },
  PULL_UPS: {
    source: require('../../assets/exercise-videos/move-kit/pull-ups.mp4'),
    filename: 'pull-ups.mp4',
    label: 'Pull Ups',
  },
  PUSH_UP: {
    source: require('../../assets/exercise-videos/move-kit/push-up.mp4'),
    filename: 'push-up.mp4',
    label: 'Push Up',
  },
  SMITH_MACHINE_INCLINE_BENCH_PRESS: {
    source: require('../../assets/exercise-videos/move-kit/smith-machine-incline-bench-press.mp4'),
    filename: 'smith-machine-incline-bench-press.mp4',
    label: 'Smith Machine Incline Bench Press',
  },
  SMITH_MACHINE_SUMO_ROMANIAN_DEADLIFT: {
    source: require('../../assets/exercise-videos/move-kit/smith-machine-sumo-romanian-deadlift.mp4'),
    filename: 'smith-machine-sumo-romanian-deadlift.mp4',
    label: 'Smith Machine Sumo Romanian Deadlift',
  },
  SUPERMANS: {
    source: require('../../assets/exercise-videos/move-kit/supermans.mp4'),
    filename: 'supermans.mp4',
    label: 'Supermans',
  },
  WALL_SIT: {
    source: require('../../assets/exercise-videos/move-kit/wall-sit.mp4'),
    filename: 'wall-sit.mp4',
    label: 'Wall Sit',
  },
} as const satisfies Readonly<Record<string, MoveKitExerciseVideo>>;

export const MOVE_KIT_VIDEO_BY_DEMO_ID = {
  'Ab_Crunch_Machine': MOVE_KIT_FILES.MACHINE_CRUNCH,
  'Barbell_Bench_Press_-_Medium_Grip': MOVE_KIT_FILES.BARBELL_BENCH_PRESS,
  'Barbell_Curl': MOVE_KIT_FILES.BARBELL_CURL,
  'Barbell_Deadlift': MOVE_KIT_FILES.BARBELL_DEADLIFT,
  'Barbell_Incline_Bench_Press_-_Medium_Grip': MOVE_KIT_FILES.BARBELL_INCLINE_BENCH_PRESS,
  'Barbell_Shoulder_Press': MOVE_KIT_FILES.BARBELL_OVERHEAD_PRESS,
  'Barbell_Shrug': MOVE_KIT_FILES.BARBELL_SHRUG,
  'Barbell_Squat': MOVE_KIT_FILES.BARBELL_SQUAT,
  'Bench_Dips': MOVE_KIT_FILES.BENCH_DIPS,
  'Bent_Over_Barbell_Row': MOVE_KIT_FILES.BARBELL_BENT_OVER_ROW,
  'Bodyweight_Squat': MOVE_KIT_FILES.BODYWEIGHT_SQUAT,
  'Cable_Chest_Press': MOVE_KIT_FILES.CABLE_CHEST_PRESS,
  'Cable_Crossover': MOVE_KIT_FILES.CABLE_PEC_FLY,
  'Chin-Up': MOVE_KIT_FILES.CHIN_UPS,
  'Close-Grip_Barbell_Bench_Press': MOVE_KIT_FILES.BARBELL_CLOSE_GRIP_BENCH_PRESS,
  'Concentration_Curls': MOVE_KIT_FILES.DUMBBELL_CONCENTRATION_CURL,
  'Decline_Dumbbell_Bench_Press': MOVE_KIT_FILES.DUMBBELL_DECLINE_BENCH_PRESS,
  'Decline_Push-Up': MOVE_KIT_FILES.DECLINE_PUSH_UP,
  'Dip_Machine': MOVE_KIT_FILES.MACHINE_DIPS,
  'Dips_-_Chest_Version': MOVE_KIT_FILES.PARRALEL_BAR_DIPS,
  'Donkey_Calf_Raises': MOVE_KIT_FILES.BODYWEIGHT_DONKEY_CALF_RAISE,
  'Drag_Curl': MOVE_KIT_FILES.BARBELL_DRAG_CURL,
  'Dumbbell_Bench_Press': MOVE_KIT_FILES.DUMBBELL_BENCH_PRESS,
  'Dumbbell_Bicep_Curl': MOVE_KIT_FILES.DUMBBELL_CURL,
  'Dumbbell_Flyes': MOVE_KIT_FILES.DUMBBELL_CHEST_FLY,
  'Dumbbell_One-Arm_Shoulder_Press': MOVE_KIT_FILES.DUMBBELL_SEATED_OVERHEAD_PRESS,
  'Dumbbell_Seated_One-Leg_Calf_Raise': MOVE_KIT_FILES.DUMBBELL_SINGLE_LEG_CALF_RAISE,
  'Dumbbell_Shrug': MOVE_KIT_FILES.DUMBBELL_SHRUG,
  'Face_Pull': MOVE_KIT_FILES.CABLE_BAR_FACE_PULL,
  'Freehand_Jump_Squat': MOVE_KIT_FILES.JUMP_SQUATS,
  'Front_Box_Jump': MOVE_KIT_FILES.BOX_JUMP,
  'Front_Dumbbell_Raise': MOVE_KIT_FILES.DUMBBELL_FRONT_RAISE,
  'Goblet_Squat': MOVE_KIT_FILES.DUMBBELL_GOBLET_SQUAT,
  'Good_Morning': MOVE_KIT_FILES.GOOD_MORNINGS,
  'Hammer_Curls': MOVE_KIT_FILES.DUMBBELL_HAMMER_CURL,
  'Hanging_Leg_Raise': MOVE_KIT_FILES.HANGING_KNEE_RAISES,
  'Hyperextensions_Back_Extensions': MOVE_KIT_FILES.MACHINE_45_DEGREE_BACK_EXTENSION,
  'Incline_Dumbbell_Curl': MOVE_KIT_FILES.DUMBBELL_INCLINE_CURL,
  'Incline_Dumbbell_Flyes': MOVE_KIT_FILES.DUMBBELL_INCLINE_CHEST_FLY,
  'Incline_Dumbbell_Press': MOVE_KIT_FILES.DUMBBELL_INCLINE_BENCH_PRESS,
  'Incline_Hammer_Curls': MOVE_KIT_FILES.DUMBBELL_INCLINE_HAMMER_CURL,
  'Incline_Push-Up': MOVE_KIT_FILES.INCLINE_PUSH_UP,
  'Inverted_Row': MOVE_KIT_FILES.INVERTED_ROW,
  'Kettlebell_Thruster': MOVE_KIT_FILES.KETTLEBELL_THRUSTER,
  'Kettlebell_Windmill': MOVE_KIT_FILES.KETTLEBELL_WINDMILL,
  'Leg_Extensions': MOVE_KIT_FILES.MACHINE_LEG_EXTENSION,
  'Leg_Press': MOVE_KIT_FILES.MACHINE_LEG_PRESS,
  'Lying_T-Bar_Row': MOVE_KIT_FILES.LANDMINE_T_BAR_ROWS,
  'Lying_Triceps_Press': MOVE_KIT_FILES.DUMBBELL_SKULLCRUSHER,
  'Mountain_Climbers': MOVE_KIT_FILES.MOUNTAIN_CLIMBER,
  'One_Arm_Dumbbell_Bench_Press': MOVE_KIT_FILES.DUMBBELL_SINGLE_ARM_CHEST_PRESS,
  'One-Arm_Kettlebell_Swings': MOVE_KIT_FILES.KETTLEBELL_SWING,
  'Plank': MOVE_KIT_FILES.HAND_PLANK,
  'Power_Snatch': MOVE_KIT_FILES.BARBELL_POWER_SNATCH,
  'Preacher_Curl': MOVE_KIT_FILES.DUMBBELL_PREACHER_CURL,
  'Pullups': MOVE_KIT_FILES.PULL_UPS,
  'Pushups': MOVE_KIT_FILES.PUSH_UP,
  'Rack_Pulls': MOVE_KIT_FILES.BARBELL_RACK_PULL,
  'Reverse_Flyes': MOVE_KIT_FILES.DUMBBELL_REAR_DELT_FLY,
  'Romanian_Deadlift': MOVE_KIT_FILES.BARBELL_STIFF_LEG_DEADLIFTS,
  'Russian_Twist': MOVE_KIT_FILES.BODYWEIGHT_RUSSIAN_TWIST,
  'Seated_Cable_Rows': MOVE_KIT_FILES.MACHINE_SEATED_CABLE_ROW,
  'Seated_Dumbbell_Press': MOVE_KIT_FILES.DUMBBELL_SEATED_OVERHEAD_PRESS,
  'Seated_One-arm_Cable_Pulley_Rows': MOVE_KIT_FILES.CABLE_SINGLE_ARM_NEUTRAL_GRIP_ROW,
  'Side_Bridge': MOVE_KIT_FILES.ELBOW_SIDE_PLANK,
  'Side_Lateral_Raise': MOVE_KIT_FILES.DUMBBELL_LATERAL_RAISE,
  'Smith_Machine_Incline_Bench_Press': MOVE_KIT_FILES.SMITH_MACHINE_INCLINE_BENCH_PRESS,
  'Split_Squat_with_Dumbbells': MOVE_KIT_FILES.DUMBBELL_GOBLET_SPLIT_SQUAT,
  'Standing_Biceps_Cable_Curl': MOVE_KIT_FILES.CABLE_BAR_CURL,
  'Standing_Dumbbell_Triceps_Extension': MOVE_KIT_FILES.DUMBBELL_SEATED_OVERHEAD_TRICEP_EXTENSION,
  'Standing_Military_Press': MOVE_KIT_FILES.BARBELL_OVERHEAD_PRESS,
  'Superman': MOVE_KIT_FILES.SUPERMANS,
  'Tricep_Dumbbell_Kickback': MOVE_KIT_FILES.DUMBBELL_TRICEP_KICKBACK,
  'Triceps_Pushdown': MOVE_KIT_FILES.CABLE_BAR_PUSHDOWN,
  'Upright_Barbell_Row': MOVE_KIT_FILES.BARBELL_UPRIGHT_ROW,
  'Wide-Grip_Lat_Pulldown': MOVE_KIT_FILES.MACHINE_PULLDOWN,
} as const satisfies Readonly<Record<string, MoveKitExerciseVideo>>;

export const MOVE_KIT_VIDEO_BY_EXERCISE_KEY = {
  'ab crunch machine': MOVE_KIT_FILES.MACHINE_CRUNCH,
  'alternating dumbbell curl': MOVE_KIT_FILES.DUMBBELL_CURL,
  'assisted dip machine': MOVE_KIT_FILES.MACHINE_DIPS,
  'back extension back focused': MOVE_KIT_FILES.MACHINE_45_DEGREE_BACK_EXTENSION,
  'back extension glute focused': MOVE_KIT_FILES.MACHINE_45_DEGREE_BACK_EXTENSION,
  'band bicep curl': MOVE_KIT_FILES.BAND_CURL,
  'band curl': MOVE_KIT_FILES.BAND_CURL,
  'band face pull': MOVE_KIT_FILES.BAND_HIGH_FACE_PULL,
  'band high face pull': MOVE_KIT_FILES.BAND_HIGH_FACE_PULL,
  'band row': MOVE_KIT_FILES.BAND_ROW,
  'barbell bench press': MOVE_KIT_FILES.BARBELL_BENCH_PRESS,
  'barbell bench press medium grip': MOVE_KIT_FILES.BARBELL_BENCH_PRESS,
  'barbell bent over row': MOVE_KIT_FILES.BARBELL_BENT_OVER_ROW,
  'barbell close grip bench press': MOVE_KIT_FILES.BARBELL_CLOSE_GRIP_BENCH_PRESS,
  'barbell curl': MOVE_KIT_FILES.BARBELL_CURL,
  'barbell deadlift': MOVE_KIT_FILES.BARBELL_DEADLIFT,
  'barbell drag curl': MOVE_KIT_FILES.BARBELL_DRAG_CURL,
  'barbell incline bench press': MOVE_KIT_FILES.BARBELL_INCLINE_BENCH_PRESS,
  'barbell incline bench press medium grip': MOVE_KIT_FILES.BARBELL_INCLINE_BENCH_PRESS,
  'barbell overhead press': MOVE_KIT_FILES.BARBELL_OVERHEAD_PRESS,
  'barbell power snatch': MOVE_KIT_FILES.BARBELL_POWER_SNATCH,
  'barbell rack pull': MOVE_KIT_FILES.BARBELL_RACK_PULL,
  'barbell romanian deadlift': MOVE_KIT_FILES.BARBELL_STIFF_LEG_DEADLIFTS,
  'barbell row': MOVE_KIT_FILES.BARBELL_BENT_OVER_ROW,
  'barbell shoulder press': MOVE_KIT_FILES.BARBELL_OVERHEAD_PRESS,
  'barbell shrug': MOVE_KIT_FILES.BARBELL_SHRUG,
  'barbell squat': MOVE_KIT_FILES.BARBELL_SQUAT,
  'barbell stiff leg deadlift': MOVE_KIT_FILES.BARBELL_STIFF_LEG_DEADLIFTS,
  'barbell upright row': MOVE_KIT_FILES.BARBELL_UPRIGHT_ROW,
  'bench dip': MOVE_KIT_FILES.BENCH_DIPS,
  'bent over barbell row': MOVE_KIT_FILES.BARBELL_BENT_OVER_ROW,
  'bilateral cable chest press': MOVE_KIT_FILES.CABLE_CHEST_PRESS,
  'bodyweight alternating lateral lunge': MOVE_KIT_FILES.BODYWEIGHT_ALTERNATING_LATERAL_LUNGE,
  'bodyweight donkey calf raise': MOVE_KIT_FILES.BODYWEIGHT_DONKEY_CALF_RAISE,
  'bodyweight reverse lunge': MOVE_KIT_FILES.BODYWEIGHT_REVERSE_LUNGE,
  'bodyweight russian twist': MOVE_KIT_FILES.BODYWEIGHT_RUSSIAN_TWIST,
  'bodyweight squat': MOVE_KIT_FILES.BODYWEIGHT_SQUAT,
  'box jump': MOVE_KIT_FILES.BOX_JUMP,
  'bulgarian split squat': MOVE_KIT_FILES.BULGARIAN_SPLIT_SQUAT,
  'burpee': MOVE_KIT_FILES.BURPEE,
  'burpees': MOVE_KIT_FILES.BURPEE,
  'cable bar curl': MOVE_KIT_FILES.CABLE_BAR_CURL,
  'cable bar face pull': MOVE_KIT_FILES.CABLE_BAR_FACE_PULL,
  'cable bar pushdown': MOVE_KIT_FILES.CABLE_BAR_PUSHDOWN,
  'cable chest press': MOVE_KIT_FILES.CABLE_CHEST_PRESS,
  'cable crossover': MOVE_KIT_FILES.CABLE_PEC_FLY,
  'cable curl': MOVE_KIT_FILES.CABLE_BAR_CURL,
  'cable fly': MOVE_KIT_FILES.CABLE_PEC_FLY,
  'cable pec fly': MOVE_KIT_FILES.CABLE_PEC_FLY,
  'cable rope pushdown': MOVE_KIT_FILES.CABLE_ROPE_PUSHDOWN,
  'cable single arm neutral grip row': MOVE_KIT_FILES.CABLE_SINGLE_ARM_NEUTRAL_GRIP_ROW,
  'cable single arm rope pushdown': MOVE_KIT_FILES.CABLE_SINGLE_ARM_ROPE_PUSHDOWN,
  'cable standing single arm chest press': MOVE_KIT_FILES.CABLE_STANDING_SINGLE_ARM_CHEST_PRESS,
  'cable wood chopper': MOVE_KIT_FILES.CABLE_WOOD_CHOPPER,
  'cable woodchop': MOVE_KIT_FILES.CABLE_WOOD_CHOPPER,
  'chest dip': MOVE_KIT_FILES.PARRALEL_BAR_DIPS,
  'chin up': MOVE_KIT_FILES.CHIN_UPS,
  'chin ups': MOVE_KIT_FILES.CHIN_UPS,
  'close grip barbell bench press': MOVE_KIT_FILES.BARBELL_CLOSE_GRIP_BENCH_PRESS,
  'close grip bench press': MOVE_KIT_FILES.BARBELL_CLOSE_GRIP_BENCH_PRESS,
  'close grip lat pulldown': MOVE_KIT_FILES.NARROW_PULLDOWN,
  'concentration curl': MOVE_KIT_FILES.DUMBBELL_CONCENTRATION_CURL,
  'crunch machine': MOVE_KIT_FILES.MACHINE_CRUNCH,
  'deadlift': MOVE_KIT_FILES.BARBELL_DEADLIFT,
  'decline dumbbell bench press': MOVE_KIT_FILES.DUMBBELL_DECLINE_BENCH_PRESS,
  'decline dumbbell press': MOVE_KIT_FILES.DUMBBELL_DECLINE_BENCH_PRESS,
  'decline push up': MOVE_KIT_FILES.DECLINE_PUSH_UP,
  'decline push ups': MOVE_KIT_FILES.DECLINE_PUSH_UP,
  'diamond push ups': MOVE_KIT_FILES.DIAMOND_PUSH_UPS,
  'dip chest version': MOVE_KIT_FILES.PARRALEL_BAR_DIPS,
  'dip machine': MOVE_KIT_FILES.MACHINE_DIPS,
  'donkey calf raise': MOVE_KIT_FILES.BODYWEIGHT_DONKEY_CALF_RAISE,
  'drag curl': MOVE_KIT_FILES.BARBELL_DRAG_CURL,
  'dumbbell bench press': MOVE_KIT_FILES.DUMBBELL_BENCH_PRESS,
  'dumbbell bicep curl': MOVE_KIT_FILES.DUMBBELL_CURL,
  'dumbbell chest fly': MOVE_KIT_FILES.DUMBBELL_CHEST_FLY,
  'dumbbell concentration curl': MOVE_KIT_FILES.DUMBBELL_CONCENTRATION_CURL,
  'dumbbell curl': MOVE_KIT_FILES.DUMBBELL_CURL,
  'dumbbell decline bench press': MOVE_KIT_FILES.DUMBBELL_DECLINE_BENCH_PRESS,
  'dumbbell fly': MOVE_KIT_FILES.DUMBBELL_CHEST_FLY,
  'dumbbell front raise': MOVE_KIT_FILES.DUMBBELL_FRONT_RAISE,
  'dumbbell goblet split squat': MOVE_KIT_FILES.DUMBBELL_GOBLET_SPLIT_SQUAT,
  'dumbbell goblet squat': MOVE_KIT_FILES.DUMBBELL_GOBLET_SQUAT,
  'dumbbell hammer curl': MOVE_KIT_FILES.DUMBBELL_HAMMER_CURL,
  'dumbbell incline bench press': MOVE_KIT_FILES.DUMBBELL_INCLINE_BENCH_PRESS,
  'dumbbell incline chest fly': MOVE_KIT_FILES.DUMBBELL_INCLINE_CHEST_FLY,
  'dumbbell incline curl': MOVE_KIT_FILES.DUMBBELL_INCLINE_CURL,
  'dumbbell incline hammer curl': MOVE_KIT_FILES.DUMBBELL_INCLINE_HAMMER_CURL,
  'dumbbell lateral raise': MOVE_KIT_FILES.DUMBBELL_LATERAL_RAISE,
  'dumbbell one arm shoulder press': MOVE_KIT_FILES.DUMBBELL_SEATED_OVERHEAD_PRESS,
  'dumbbell preacher curl': MOVE_KIT_FILES.DUMBBELL_PREACHER_CURL,
  'dumbbell rear delt fly': MOVE_KIT_FILES.DUMBBELL_REAR_DELT_FLY,
  'dumbbell row': MOVE_KIT_FILES.DUMBBELL_ROW_UNILATERAL,
  'dumbbell row unilateral': MOVE_KIT_FILES.DUMBBELL_ROW_UNILATERAL,
  'dumbbell seated one leg calf raise': MOVE_KIT_FILES.DUMBBELL_SINGLE_LEG_CALF_RAISE,
  'dumbbell seated overhead press': MOVE_KIT_FILES.DUMBBELL_SEATED_OVERHEAD_PRESS,
  'dumbbell seated overhead tricep extension': MOVE_KIT_FILES.DUMBBELL_SEATED_OVERHEAD_TRICEP_EXTENSION,
  'dumbbell shoulder press': MOVE_KIT_FILES.DUMBBELL_SEATED_OVERHEAD_PRESS,
  'dumbbell shrug': MOVE_KIT_FILES.DUMBBELL_SHRUG,
  'dumbbell single arm chest press': MOVE_KIT_FILES.DUMBBELL_SINGLE_ARM_CHEST_PRESS,
  'dumbbell single leg calf raise': MOVE_KIT_FILES.DUMBBELL_SINGLE_LEG_CALF_RAISE,
  'dumbbell situp': MOVE_KIT_FILES.DUMBBELL_SITUP,
  'dumbbell skull crusher': MOVE_KIT_FILES.DUMBBELL_SKULLCRUSHER,
  'dumbbell skullcrusher': MOVE_KIT_FILES.DUMBBELL_SKULLCRUSHER,
  'dumbbell sumo squat': MOVE_KIT_FILES.DUMBBELL_SUMO_SQUAT,
  'dumbbell thruster': MOVE_KIT_FILES.DUMBBELL_THRUSTER,
  'dumbbell tricep kickback': MOVE_KIT_FILES.DUMBBELL_TRICEP_KICKBACK,
  'dumbbell wrist curl': MOVE_KIT_FILES.DUMBBELL_WRIST_CURL,
  'elbow side plank': MOVE_KIT_FILES.ELBOW_SIDE_PLANK,
  'face pull': MOVE_KIT_FILES.CABLE_BAR_FACE_PULL,
  'freehand jump squat': MOVE_KIT_FILES.JUMP_SQUATS,
  'front box jump': MOVE_KIT_FILES.BOX_JUMP,
  'front dumbbell raise': MOVE_KIT_FILES.DUMBBELL_FRONT_RAISE,
  'front raise': MOVE_KIT_FILES.DUMBBELL_FRONT_RAISE,
  'goblet squat': MOVE_KIT_FILES.DUMBBELL_GOBLET_SQUAT,
  'good morning': MOVE_KIT_FILES.GOOD_MORNINGS,
  'hammer curl': MOVE_KIT_FILES.DUMBBELL_HAMMER_CURL,
  'hand plank': MOVE_KIT_FILES.HAND_PLANK,
  'hanging knee raise': MOVE_KIT_FILES.HANGING_KNEE_RAISES,
  'hanging leg raise': MOVE_KIT_FILES.HANGING_KNEE_RAISES,
  'heel elevated goblet squat': MOVE_KIT_FILES.DUMBBELL_GOBLET_SQUAT,
  'hyperextensions back extension': MOVE_KIT_FILES.MACHINE_45_DEGREE_BACK_EXTENSION,
  'incline barbell press': MOVE_KIT_FILES.BARBELL_INCLINE_BENCH_PRESS,
  'incline dumbbell curl': MOVE_KIT_FILES.DUMBBELL_INCLINE_CURL,
  'incline dumbbell fly': MOVE_KIT_FILES.DUMBBELL_INCLINE_CHEST_FLY,
  'incline dumbbell press': MOVE_KIT_FILES.DUMBBELL_INCLINE_BENCH_PRESS,
  'incline hammer curl': MOVE_KIT_FILES.DUMBBELL_INCLINE_HAMMER_CURL,
  'incline push up': MOVE_KIT_FILES.INCLINE_PUSH_UP,
  'inverted row': MOVE_KIT_FILES.INVERTED_ROW,
  'iso lateral row': MOVE_KIT_FILES.MACHINE_NEUTRAL_ROW,
  'jump squats': MOVE_KIT_FILES.JUMP_SQUATS,
  'kettlebell row': MOVE_KIT_FILES.KETTLEBELL_ROW,
  'kettlebell swing': MOVE_KIT_FILES.KETTLEBELL_SWING,
  'kettlebell thruster': MOVE_KIT_FILES.KETTLEBELL_THRUSTER,
  'kettlebell windmill': MOVE_KIT_FILES.KETTLEBELL_WINDMILL,
  'landmine t bar row': MOVE_KIT_FILES.LANDMINE_T_BAR_ROWS,
  'lat pulldown': MOVE_KIT_FILES.MACHINE_PULLDOWN,
  'lateral lunge': MOVE_KIT_FILES.BODYWEIGHT_ALTERNATING_LATERAL_LUNGE,
  'lateral raise': MOVE_KIT_FILES.DUMBBELL_LATERAL_RAISE,
  'leg extension': MOVE_KIT_FILES.MACHINE_LEG_EXTENSION,
  'leg press': MOVE_KIT_FILES.MACHINE_LEG_PRESS,
  'lunge walking': MOVE_KIT_FILES.LUNGE_WALKING,
  'lying t bar row': MOVE_KIT_FILES.LANDMINE_T_BAR_ROWS,
  'lying triceps press': MOVE_KIT_FILES.DUMBBELL_SKULLCRUSHER,
  'machine 45 degree back extension': MOVE_KIT_FILES.MACHINE_45_DEGREE_BACK_EXTENSION,
  'machine chest press': MOVE_KIT_FILES.MACHINE_CHEST_PRESS,
  'machine crunch': MOVE_KIT_FILES.MACHINE_CRUNCH,
  'machine dip': MOVE_KIT_FILES.MACHINE_DIPS,
  'machine front military press': MOVE_KIT_FILES.MACHINE_FRONT_MILITARY_PRESS,
  'machine leg extension': MOVE_KIT_FILES.MACHINE_LEG_EXTENSION,
  'machine leg press': MOVE_KIT_FILES.MACHINE_LEG_PRESS,
  'machine neutral row': MOVE_KIT_FILES.MACHINE_NEUTRAL_ROW,
  'machine pec fly': MOVE_KIT_FILES.MACHINE_PEC_FLY,
  'machine pulldown': MOVE_KIT_FILES.MACHINE_PULLDOWN,
  'machine seated cable row': MOVE_KIT_FILES.MACHINE_SEATED_CABLE_ROW,
  'machine shoulder press': MOVE_KIT_FILES.MACHINE_FRONT_MILITARY_PRESS,
  'mountain climber': MOVE_KIT_FILES.MOUNTAIN_CLIMBER,
  'narrow pulldown': MOVE_KIT_FILES.NARROW_PULLDOWN,
  'neutral grip lat pulldown': MOVE_KIT_FILES.NARROW_PULLDOWN,
  'one arm dumbbell bench press': MOVE_KIT_FILES.DUMBBELL_SINGLE_ARM_CHEST_PRESS,
  'one arm kettlebell swings': MOVE_KIT_FILES.KETTLEBELL_SWING,
  'overhead press': MOVE_KIT_FILES.BARBELL_OVERHEAD_PRESS,
  'overhead tricep extension': MOVE_KIT_FILES.DUMBBELL_SEATED_OVERHEAD_TRICEP_EXTENSION,
  'parralel bar dip': MOVE_KIT_FILES.PARRALEL_BAR_DIPS,
  'pec deck': MOVE_KIT_FILES.MACHINE_PEC_FLY,
  'pectoral fly': MOVE_KIT_FILES.MACHINE_PEC_FLY,
  'pendlay row': MOVE_KIT_FILES.BARBELL_BENT_OVER_ROW,
  'plank': MOVE_KIT_FILES.HAND_PLANK,
  'power snatch': MOVE_KIT_FILES.BARBELL_POWER_SNATCH,
  'preacher curl': MOVE_KIT_FILES.DUMBBELL_PREACHER_CURL,
  'pull ups': MOVE_KIT_FILES.PULL_UPS,
  'push up': MOVE_KIT_FILES.PUSH_UP,
  'push ups': MOVE_KIT_FILES.PUSH_UP,
  'rack pull': MOVE_KIT_FILES.BARBELL_RACK_PULL,
  'rack pulls': MOVE_KIT_FILES.BARBELL_RACK_PULL,
  'rear delt fly': MOVE_KIT_FILES.DUMBBELL_REAR_DELT_FLY,
  'reverse fly': MOVE_KIT_FILES.DUMBBELL_REAR_DELT_FLY,
  'reverse lunge': MOVE_KIT_FILES.BODYWEIGHT_REVERSE_LUNGE,
  'romanian deadlift': MOVE_KIT_FILES.BARBELL_STIFF_LEG_DEADLIFTS,
  'rope pushdown': MOVE_KIT_FILES.CABLE_ROPE_PUSHDOWN,
  'russian twist': MOVE_KIT_FILES.BODYWEIGHT_RUSSIAN_TWIST,
  'seated cable row': MOVE_KIT_FILES.MACHINE_SEATED_CABLE_ROW,
  'seated dip machine': MOVE_KIT_FILES.MACHINE_DIPS,
  'seated dumbbell press': MOVE_KIT_FILES.DUMBBELL_SEATED_OVERHEAD_PRESS,
  'seated one arm cable pulley row': MOVE_KIT_FILES.CABLE_SINGLE_ARM_NEUTRAL_GRIP_ROW,
  'seated row machine': MOVE_KIT_FILES.MACHINE_NEUTRAL_ROW,
  'side bridge': MOVE_KIT_FILES.ELBOW_SIDE_PLANK,
  'side lateral raise': MOVE_KIT_FILES.DUMBBELL_LATERAL_RAISE,
  'side plank': MOVE_KIT_FILES.ELBOW_SIDE_PLANK,
  'single arm cable chest press': MOVE_KIT_FILES.CABLE_STANDING_SINGLE_ARM_CHEST_PRESS,
  'single arm cable pushdown': MOVE_KIT_FILES.CABLE_SINGLE_ARM_ROPE_PUSHDOWN,
  'single arm cable row': MOVE_KIT_FILES.CABLE_SINGLE_ARM_NEUTRAL_GRIP_ROW,
  'single arm dumbbell bench press': MOVE_KIT_FILES.DUMBBELL_SINGLE_ARM_CHEST_PRESS,
  'single leg calf raise': MOVE_KIT_FILES.DUMBBELL_SINGLE_LEG_CALF_RAISE,
  'skull crusher': MOVE_KIT_FILES.DUMBBELL_SKULLCRUSHER,
  'slant board goblet squat': MOVE_KIT_FILES.DUMBBELL_GOBLET_SQUAT,
  'slider mountain climber': MOVE_KIT_FILES.MOUNTAIN_CLIMBER,
  'smith machine incline bench press': MOVE_KIT_FILES.SMITH_MACHINE_INCLINE_BENCH_PRESS,
  'smith machine incline press': MOVE_KIT_FILES.SMITH_MACHINE_INCLINE_BENCH_PRESS,
  'smith machine romanian deadlift': MOVE_KIT_FILES.SMITH_MACHINE_SUMO_ROMANIAN_DEADLIFT,
  'smith machine sumo romanian deadlift': MOVE_KIT_FILES.SMITH_MACHINE_SUMO_ROMANIAN_DEADLIFT,
  'split squat': MOVE_KIT_FILES.DUMBBELL_GOBLET_SPLIT_SQUAT,
  'split squat with dumbbells': MOVE_KIT_FILES.DUMBBELL_GOBLET_SPLIT_SQUAT,
  'standing biceps cable curl': MOVE_KIT_FILES.CABLE_BAR_CURL,
  'standing dumbbell triceps extension': MOVE_KIT_FILES.DUMBBELL_SEATED_OVERHEAD_TRICEP_EXTENSION,
  'standing military press': MOVE_KIT_FILES.BARBELL_OVERHEAD_PRESS,
  'sumo squat': MOVE_KIT_FILES.DUMBBELL_SUMO_SQUAT,
  'superman': MOVE_KIT_FILES.SUPERMANS,
  'superman hold': MOVE_KIT_FILES.SUPERMANS,
  't bar row': MOVE_KIT_FILES.LANDMINE_T_BAR_ROWS,
  'thrusters': MOVE_KIT_FILES.DUMBBELL_THRUSTER,
  'tricep dumbbell kickback': MOVE_KIT_FILES.DUMBBELL_TRICEP_KICKBACK,
  'tricep pushdown': MOVE_KIT_FILES.CABLE_BAR_PUSHDOWN,
  'triceps pushdown': MOVE_KIT_FILES.CABLE_BAR_PUSHDOWN,
  'upright barbell row': MOVE_KIT_FILES.BARBELL_UPRIGHT_ROW,
  'upright row': MOVE_KIT_FILES.BARBELL_UPRIGHT_ROW,
  'walking lunge': MOVE_KIT_FILES.LUNGE_WALKING,
  'wall sit': MOVE_KIT_FILES.WALL_SIT,
  'weighted sit up': MOVE_KIT_FILES.DUMBBELL_SITUP,
  'wide grip lat pulldown': MOVE_KIT_FILES.MACHINE_PULLDOWN,
  'wide push ups': MOVE_KIT_FILES.PUSH_UP,
  'wrist curl': MOVE_KIT_FILES.DUMBBELL_WRIST_CURL,
} as const satisfies Readonly<Record<string, MoveKitExerciseVideo>>;

