"""USDA-sourced micronutrient panels (per 100g) for seed foods that lacked them.

Auto-generated from USDA FoodData Central via the seed-backfill matcher, then
hand-reviewed for match correctness. Merged into MICRONUTRIENTS at import time.
"""

USDA_MICRONUTRIENTS = {
    "protein bar": {
        "fiber": 7.3,
        "sugar": 15.2,
        "sodium": 436,
        "calcium": 322,
        "iron": 5.4,
        "magnesium": 71.0,
        "phosphorus": 445,
        "potassium": 793,
        "zinc": 2.39,
        "copper": 0.85,
        "manganese": 1.02,
        "selenium": 9.0,
        "vitamin_b12": 0.61,
        "vitamin_c": 27.9,
        "vitamin_e": 4.61,
        "vitamin_a": 391,
        "saturated_fat": 3.38,
        "monounsaturated_fat": 4.29,
        "polyunsaturated_fat": 5.33,
        "cholesterol": 3.0
    },
    "chicken sausage": {
        "sodium": 705,
        "calcium": 38,
        "iron": 1.38,
        "magnesium": 22,
        "phosphorus": 209,
        "potassium": 365,
        "zinc": 3.04,
        "copper": 0.08,
        "selenium": 14.7,
        "vitamin_d": 0.5,
        "vitamin_b12": 1.41,
        "vitamin_e": 0.28,
        "saturated_fat": 2.98,
        "monounsaturated_fat": 3.61,
        "polyunsaturated_fat": 3.71,
        "cholesterol": 92
    },
    "bacon": {
        "sodium": 1680.0,
        "calcium": 11.0,
        "iron": 0.95,
        "magnesium": 31.0,
        "phosphorus": 388,
        "potassium": 499,
        "zinc": 3.06,
        "copper": 0.1,
        "manganese": 0.02,
        "selenium": 50.7,
        "vitamin_d": 0.4,
        "vitamin_b12": 1.09,
        "vitamin_e": 0.42,
        "vitamin_a": 11.0,
        "saturated_fat": 12.0,
        "monounsaturated_fat": 15.5,
        "polyunsaturated_fat": 6.11,
        "cholesterol": 99.0
    },
    "whole milk": {
        "sodium": 38.0,
        "calcium": 123,
        "magnesium": 11.9,
        "phosphorus": 101,
        "potassium": 150,
        "zinc": 0.42,
        "copper": 0.0,
        "selenium": 1.9,
        "vitamin_d": 0.96,
        "vitamin_b12": 0.54,
        "vitamin_e": 0.05,
        "vitamin_a": 32.0,
        "saturated_fat": 1.86,
        "monounsaturated_fat": 0.69,
        "polyunsaturated_fat": 0.11,
        "cholesterol": 12.0
    },
    "2% milk": {
        "sugar": 5.06,
        "sodium": 47.0,
        "calcium": 120,
        "iron": 0.02,
        "magnesium": 11.0,
        "phosphorus": 92.0,
        "potassium": 140,
        "zinc": 0.48,
        "copper": 0.01,
        "manganese": 0.01,
        "selenium": 2.5,
        "vitamin_d": 1.2,
        "vitamin_b12": 0.53,
        "vitamin_c": 0.2,
        "vitamin_e": 0.03,
        "vitamin_a": 55.0,
        "saturated_fat": 1.26,
        "monounsaturated_fat": 0.56,
        "polyunsaturated_fat": 0.07,
        "cholesterol": 8.0
    },
    "skim milk": {
        "sugar": 4.85,
        "sodium": 52.0,
        "calcium": 204,
        "iron": 0.04,
        "magnesium": 11.0,
        "phosphorus": 101,
        "potassium": 166,
        "zinc": 0.4,
        "copper": 0.01,
        "selenium": 2.1,
        "vitamin_d": 1.2,
        "vitamin_b12": 0.38,
        "vitamin_c": 1.0,
        "vitamin_e": 0.01,
        "vitamin_a": 137,
        "saturated_fat": 0.12,
        "monounsaturated_fat": 0.05,
        "polyunsaturated_fat": 0.01,
        "cholesterol": 2.0
    },
    "cream cheese": {
        "sugar": 3.76,
        "sodium": 314,
        "calcium": 97.0,
        "iron": 0.11,
        "magnesium": 9.0,
        "phosphorus": 107,
        "potassium": 132,
        "zinc": 0.5,
        "copper": 0.02,
        "manganese": 0.01,
        "selenium": 8.6,
        "vitamin_b12": 0.22,
        "vitamin_e": 0.86,
        "vitamin_a": 308,
        "saturated_fat": 20.2,
        "monounsaturated_fat": 8.91,
        "polyunsaturated_fat": 1.48,
        "cholesterol": 101
    },
    "heavy cream": {
        "sugar": 2.92,
        "sodium": 27.0,
        "calcium": 66.0,
        "iron": 0.1,
        "magnesium": 7.0,
        "phosphorus": 58.0,
        "potassium": 95.0,
        "zinc": 0.24,
        "copper": 0.01,
        "manganese": 0.01,
        "selenium": 3.0,
        "vitamin_d": 1.6,
        "vitamin_b12": 0.16,
        "vitamin_c": 0.6,
        "vitamin_e": 0.92,
        "vitamin_a": 411,
        "saturated_fat": 23.0,
        "monounsaturated_fat": 9.1,
        "polyunsaturated_fat": 1.57,
        "cholesterol": 113
    },
    "edamame (shelled)": {
        "fiber": 5.2,
        "sugar": 2.18,
        "sodium": 6.0,
        "calcium": 63.0,
        "iron": 2.27,
        "magnesium": 64.0,
        "phosphorus": 169,
        "potassium": 436,
        "zinc": 1.37,
        "copper": 0.34,
        "manganese": 1.02,
        "selenium": 0.8,
        "vitamin_c": 6.1,
        "vitamin_e": 0.68,
        "vitamin_a": 15.0,
        "saturated_fat": 0.62,
        "monounsaturated_fat": 1.28,
        "polyunsaturated_fat": 2.16
    },
    "hummus": {
        "fiber": 5.5,
        "sugar": 0.62,
        "sodium": 426,
        "calcium": 47.0,
        "iron": 2.54,
        "magnesium": 75.0,
        "phosphorus": 181,
        "potassium": 312,
        "zinc": 1.44,
        "copper": 0.38,
        "manganese": 1.16,
        "selenium": 4.7,
        "vitamin_e": 1.54,
        "vitamin_a": 1.0,
        "saturated_fat": 2.56,
        "monounsaturated_fat": 5.34,
        "polyunsaturated_fat": 8.81
    },
    "kidney beans (cooked)": {
        "fiber": 7.4,
        "sugar": 0.32,
        "sodium": 238,
        "calcium": 28.0,
        "iron": 2.94,
        "magnesium": 45.0,
        "phosphorus": 142,
        "potassium": 403,
        "zinc": 1.07,
        "copper": 0.24,
        "manganese": 0.48,
        "selenium": 1.2,
        "vitamin_c": 1.2,
        "vitamin_e": 0.03,
        "saturated_fat": 0.07,
        "monounsaturated_fat": 0.04,
        "polyunsaturated_fat": 0.28
    },
    "sweet potato": {
        "fiber": 3.3,
        "sugar": 6.48,
        "sodium": 246,
        "calcium": 38.0,
        "iron": 0.69,
        "magnesium": 27.0,
        "phosphorus": 54.0,
        "potassium": 475,
        "zinc": 0.32,
        "copper": 0.16,
        "manganese": 0.5,
        "selenium": 0.2,
        "vitamin_c": 19.6,
        "vitamin_e": 0.71,
        "saturated_fat": 0.05,
        "monounsaturated_fat": 0.0,
        "polyunsaturated_fat": 0.09
    },
    "potato": {
        "fiber": 2.3,
        "sugar": 1.08,
        "sodium": 14.0,
        "calcium": 18.0,
        "iron": 1.07,
        "magnesium": 30.0,
        "phosphorus": 71.0,
        "potassium": 550,
        "zinc": 0.35,
        "copper": 0.11,
        "manganese": 0.23,
        "selenium": 0.5,
        "vitamin_c": 8.3,
        "vitamin_e": 0.07,
        "vitamin_a": 1.0,
        "saturated_fat": 0.03,
        "monounsaturated_fat": 0.0,
        "polyunsaturated_fat": 0.05
    },
    "flour tortilla": {
        "fiber": 3.5,
        "sugar": 3.71,
        "sodium": 736,
        "calcium": 146,
        "iron": 3.63,
        "magnesium": 22.0,
        "phosphorus": 206,
        "potassium": 125,
        "zinc": 0.53,
        "copper": 0.1,
        "manganese": 0.54,
        "selenium": 22.3,
        "saturated_fat": 2.92,
        "monounsaturated_fat": 1.75,
        "polyunsaturated_fat": 2.29
    },
    "granola": {
        "fiber": 8.9,
        "sugar": 19.8,
        "sodium": 26.0,
        "calcium": 76.0,
        "iron": 3.95,
        "magnesium": 168,
        "phosphorus": 431,
        "potassium": 539,
        "zinc": 4.17,
        "copper": 0.65,
        "manganese": 4.0,
        "selenium": 25.4,
        "vitamin_c": 1.2,
        "vitamin_e": 11.1,
        "vitamin_a": 1.0,
        "saturated_fat": 3.96,
        "monounsaturated_fat": 11.0,
        "polyunsaturated_fat": 7.81
    },
    "honey": {
        "fiber": 0.2,
        "sugar": 82.1,
        "sodium": 4.0,
        "calcium": 6.0,
        "iron": 0.42,
        "magnesium": 2.0,
        "phosphorus": 4.0,
        "potassium": 52.0,
        "zinc": 0.22,
        "copper": 0.04,
        "manganese": 0.08,
        "selenium": 0.8,
        "vitamin_c": 0.5
    },
    "rice cakes": {
        "fiber": 4.2,
        "sugar": 0.88,
        "sodium": 71.0,
        "calcium": 11.0,
        "iron": 1.49,
        "magnesium": 131,
        "phosphorus": 360,
        "potassium": 428,
        "zinc": 3.0,
        "copper": 0.45,
        "selenium": 24.6,
        "vitamin_e": 1.24,
        "saturated_fat": 0.88,
        "monounsaturated_fat": 1.58,
        "polyunsaturated_fat": 1.52
    },
    "english muffin": {
        "fiber": 4.6,
        "sugar": 1.56,
        "sodium": 353,
        "calcium": 178,
        "iron": 2.87,
        "magnesium": 37.0,
        "phosphorus": 107,
        "potassium": 186,
        "zinc": 1.07,
        "copper": 0.15,
        "manganese": 1.0,
        "selenium": 29.2,
        "vitamin_e": 0.45,
        "saturated_fat": 0.29,
        "monounsaturated_fat": 0.28,
        "polyunsaturated_fat": 0.83
    },
    "cucumber": {
        "fiber": 0.7,
        "sugar": 1.38,
        "sodium": 2.0,
        "calcium": 14.0,
        "iron": 0.22,
        "magnesium": 12.0,
        "phosphorus": 21.0,
        "potassium": 136,
        "zinc": 0.17,
        "copper": 0.07,
        "manganese": 0.07,
        "selenium": 0.1,
        "vitamin_c": 3.2,
        "vitamin_e": 0.03,
        "vitamin_a": 4.0,
        "saturated_fat": 0.08,
        "monounsaturated_fat": 0.01,
        "polyunsaturated_fat": 0.02
    },
    "mushrooms (white)": {
        "fiber": 2.5,
        "sodium": 17.0,
        "calcium": 6.0,
        "iron": 0.33,
        "magnesium": 14.0,
        "phosphorus": 127,
        "potassium": 488,
        "zinc": 0.73,
        "copper": 0.37,
        "manganese": 0.06,
        "selenium": 18.0,
        "vitamin_d": 0.3,
        "saturated_fat": 0.06,
        "monounsaturated_fat": 0.02,
        "polyunsaturated_fat": 0.28
    },
    "onion": {
        "fiber": 1.7,
        "sugar": 4.24,
        "sodium": 4.0,
        "calcium": 23.0,
        "iron": 0.21,
        "magnesium": 10.0,
        "phosphorus": 29.0,
        "potassium": 146,
        "zinc": 0.17,
        "copper": 0.04,
        "manganese": 0.13,
        "selenium": 0.5,
        "vitamin_c": 7.4,
        "vitamin_e": 0.02,
        "saturated_fat": 0.04,
        "monounsaturated_fat": 0.01,
        "polyunsaturated_fat": 0.02
    },
    "brussels sprouts": {
        "fiber": 3.8,
        "sugar": 2.2,
        "sodium": 25.0,
        "calcium": 42.0,
        "iron": 1.4,
        "magnesium": 23.0,
        "phosphorus": 69.0,
        "potassium": 389,
        "zinc": 0.42,
        "copper": 0.07,
        "manganese": 0.34,
        "selenium": 1.6,
        "vitamin_c": 85.0,
        "vitamin_e": 0.88,
        "vitamin_a": 38.0,
        "saturated_fat": 0.06,
        "monounsaturated_fat": 0.02,
        "polyunsaturated_fat": 0.15
    },
    "mixed salad greens": {
        "fiber": 1.4,
        "sugar": 0.97,
        "sodium": 41,
        "calcium": 39,
        "iron": 0.46,
        "magnesium": 27,
        "phosphorus": 26,
        "potassium": 316,
        "zinc": 0.3,
        "copper": 0.05,
        "selenium": 0.5,
        "vitamin_c": 11.7,
        "vitamin_e": 0.54,
        "vitamin_a": 298,
        "saturated_fat": 0.03,
        "monounsaturated_fat": 0.01,
        "polyunsaturated_fat": 0.12
    },
    "grapes": {
        "fiber": 0.9,
        "sugar": 15.5,
        "sodium": 2.0,
        "calcium": 10.0,
        "iron": 0.36,
        "magnesium": 7.0,
        "phosphorus": 20.0,
        "potassium": 191,
        "zinc": 0.07,
        "copper": 0.13,
        "manganese": 0.07,
        "selenium": 0.1,
        "vitamin_c": 3.2,
        "vitamin_e": 0.19,
        "vitamin_a": 3.0,
        "saturated_fat": 0.05,
        "monounsaturated_fat": 0.01,
        "polyunsaturated_fat": 0.05
    },
    "mango": {
        "fiber": 1.6,
        "sugar": 13.7,
        "sodium": 1.0,
        "calcium": 11.0,
        "iron": 0.16,
        "magnesium": 10.0,
        "phosphorus": 14.0,
        "potassium": 168,
        "zinc": 0.09,
        "copper": 0.11,
        "manganese": 0.06,
        "selenium": 0.6,
        "vitamin_c": 36.4,
        "vitamin_e": 0.9,
        "vitamin_a": 54.0,
        "saturated_fat": 0.09,
        "monounsaturated_fat": 0.14,
        "polyunsaturated_fat": 0.07
    },
    "watermelon": {
        "fiber": 0.4,
        "sugar": 6.2,
        "sodium": 1.0,
        "calcium": 7.0,
        "iron": 0.24,
        "magnesium": 10.0,
        "phosphorus": 11.0,
        "potassium": 112,
        "zinc": 0.1,
        "copper": 0.04,
        "manganese": 0.04,
        "selenium": 0.4,
        "vitamin_c": 8.1,
        "vitamin_e": 0.05,
        "vitamin_a": 28.0,
        "saturated_fat": 0.02,
        "monounsaturated_fat": 0.04,
        "polyunsaturated_fat": 0.05
    },
    "raspberries": {
        "fiber": 6.5,
        "sugar": 4.42,
        "sodium": 1.0,
        "calcium": 25.0,
        "iron": 0.69,
        "magnesium": 22.0,
        "phosphorus": 29.0,
        "potassium": 151,
        "zinc": 0.42,
        "copper": 0.09,
        "manganese": 0.67,
        "selenium": 0.2,
        "vitamin_c": 26.2,
        "vitamin_e": 0.87,
        "vitamin_a": 2.0,
        "saturated_fat": 0.02,
        "monounsaturated_fat": 0.06,
        "polyunsaturated_fat": 0.38
    },
    "cashews": {
        "fiber": 3.3,
        "sugar": 5.91,
        "sodium": 12.0,
        "calcium": 37.0,
        "iron": 6.68,
        "magnesium": 292,
        "phosphorus": 593,
        "potassium": 660,
        "zinc": 5.78,
        "copper": 2.2,
        "manganese": 1.66,
        "selenium": 19.9,
        "vitamin_c": 0.5,
        "vitamin_e": 0.9,
        "saturated_fat": 7.78,
        "monounsaturated_fat": 23.8,
        "polyunsaturated_fat": 7.84
    },
    "flax seeds": {
        "fiber": 23.1,
        "sugar": 1.55,
        "sodium": 37,
        "calcium": 230,
        "iron": 5.78,
        "magnesium": 372,
        "phosphorus": 556,
        "potassium": 793,
        "zinc": 4.74,
        "copper": 1.34,
        "selenium": 135.9,
        "vitamin_c": 0.6,
        "saturated_fat": 3.28,
        "monounsaturated_fat": 5.94,
        "polyunsaturated_fat": 24.7
    },
    "coconut oil": {
        "calcium": 1.0,
        "iron": 0.05,
        "zinc": 0.02,
        "vitamin_e": 0.11,
        "saturated_fat": 82.5,
        "monounsaturated_fat": 6.33,
        "polyunsaturated_fat": 1.7
    },
    "dark chocolate (70%+)": {
        "fiber": 10.9,
        "sugar": 24.0,
        "sodium": 20.0,
        "calcium": 73.0,
        "iron": 11.9,
        "magnesium": 228,
        "phosphorus": 308,
        "potassium": 715,
        "zinc": 3.31,
        "copper": 1.77,
        "manganese": 1.95,
        "selenium": 6.8,
        "vitamin_b12": 0.28,
        "vitamin_e": 0.59,
        "vitamin_a": 2.0,
        "saturated_fat": 24.5,
        "monounsaturated_fat": 12.8,
        "polyunsaturated_fat": 1.26,
        "cholesterol": 3.0
    },
    "trail mix": {
        "sodium": 229,
        "calcium": 78.0,
        "iron": 3.05,
        "magnesium": 158,
        "phosphorus": 345,
        "potassium": 685,
        "zinc": 3.22,
        "copper": 0.98,
        "manganese": 1.03,
        "vitamin_c": 1.4,
        "vitamin_a": 1.0,
        "saturated_fat": 5.55,
        "monounsaturated_fat": 12.5,
        "polyunsaturated_fat": 9.65
    },
    "avocado oil": {
        "saturated_fat": 11.6,
        "monounsaturated_fat": 70.6,
        "polyunsaturated_fat": 13.5
    },
    "marinara sauce": {
        "fiber": 1.8,
        "sodium": 419,
        "calcium": 27.0,
        "iron": 0.78,
        "magnesium": 18.5,
        "phosphorus": 34.0,
        "potassium": 319,
        "zinc": 0.2,
        "copper": 0.08,
        "manganese": 0.14,
        "vitamin_a": 32.0,
        "saturated_fat": 0.17,
        "monounsaturated_fat": 0.38,
        "polyunsaturated_fat": 0.5
    },
    "salsa": {
        "fiber": 1.8,
        "sodium": 656,
        "calcium": 28.0,
        "iron": 0.42,
        "magnesium": 15.2,
        "phosphorus": 32.0,
        "potassium": 258,
        "zinc": 0.2,
        "copper": 0.07,
        "manganese": 0.11,
        "vitamin_e": 1.22,
        "vitamin_a": 24.0
    },
    "soy sauce": {
        "fiber": 0.8,
        "sugar": 1.7,
        "sodium": 5590.0,
        "calcium": 20.0,
        "iron": 2.38,
        "magnesium": 40.0,
        "phosphorus": 130,
        "potassium": 212,
        "zinc": 0.43,
        "copper": 0.14,
        "manganese": 0.5,
        "selenium": 0.8,
        "saturated_fat": 0.01,
        "monounsaturated_fat": 0.02,
        "polyunsaturated_fat": 0.04
    },
    "hot sauce": {
        "fiber": 1.9,
        "sugar": 2.55,
        "sodium": 25.0,
        "calcium": 5.0,
        "iron": 0.4,
        "magnesium": 12.0,
        "phosphorus": 14.0,
        "potassium": 564,
        "zinc": 0.15,
        "copper": 0.09,
        "selenium": 0.2,
        "vitamin_c": 68.0,
        "vitamin_e": 0.34,
        "vitamin_a": 29.0,
        "saturated_fat": 0.01,
        "monounsaturated_fat": 0.07,
        "polyunsaturated_fat": 0.01
    },
    "coffee (black)": {
        "sodium": 2.0,
        "calcium": 2.0,
        "iron": 0.01,
        "magnesium": 3.0,
        "phosphorus": 3.0,
        "potassium": 49.0,
        "zinc": 0.02,
        "copper": 0.0,
        "manganese": 0.02,
        "vitamin_e": 0.01,
        "saturated_fat": 0.0,
        "monounsaturated_fat": 0.01,
        "polyunsaturated_fat": 0.0
    }
}
