"""Curated YouTube video IDs for the most-used exercises.

Keyed by exercise slug. Every entry in this file has been validated
against YouTube's oembed endpoint — no dead/private/region-locked IDs.
Re-run validation with:

    docker exec thallo-backend python /app/scripts/validate_exercise_videos.py

When a slug matches, the client shows a YouTube thumbnail card that
deep-links to the embedded FormVideoModal player. Unlisted slugs fall
back to a branded "video tile" placeholder — never a broken thumbnail.

Sources prioritized for clean form: Jeff Nippard, AthleanX, Squat
University, Scott Herman, Renaissance Periodization (Mike Israetel).
"""
from __future__ import annotations

# slug → YouTube video ID (the `v=` param).
# IMPORTANT: every entry below has been verified via oembed.
EXERCISE_VIDEOS: dict[str, str] = {
    "alternating_dumbbell_curl": "sAq_ocpRh_I",
    "arnold_press": "6Z15_WdXmVw",
    "back_extension": "ph3pddpKzzw",
    "back_extension_back": "ph3pddpKzzw",
    "back_extension_glute": "ph3pddpKzzw",
    "barbell_back_squat": "nhoikoUEI8U",
    "barbell_bench_press": "rT7DgCr-3pg",
    "barbell_curl": "kwG2ipFRgfo",
    "barbell_row": "9efgcAjQe7E",
    "barbell_squat": "nhoikoUEI8U",
    "bench_dips": "6kALZikXxLc",
    "bicep_curl": "ykJmrZ5v0Oo",
    "bird_dog": "wiFNA3sqjCA",
    "bodyweight_squat": "bEv6CCg2BC8",
    "box_jump": "52r_Ul5k03g",
    "bulgarian_split_squat": "2C-uNgKwPLE",
    "burpee": "TU8QYVW0gDU",
    "burpees": "TU8QYVW0gDU",
    "cable_fly": "Iwe6AmxVf7o",
    "cable_lateral_raise": "3VcKaXpzqRo",
    "cable_overhead_tricep_extension": "YbX7Wd8jQ-Q",
    "chair_step_up": "aajhW7DD1EA",
    "chest_dips": "2z8JmcrW-As",
    "chin_up": "brhRXlOhsAM",
    "chinups": "brhRXlOhsAM",
    "close_grip_bench_press": "nEF0bv2FW94",
    "close_grip_lat_pulldown": "V8dZ3pyiCBo",
    "conventional_deadlift": "AweC3UaM14o",
    "cross_body_hammer_curl": "TwD-YGVP4Bk",
    "crunch": "Xyd_fa5zoEU",
    "dead_bug": "g_BYB0R-4Ws",
    "deadlift": "AweC3UaM14o",
    "decline_bench_press": "LfyQBUKR8SE",
    "decline_pushups": "SKPab2YC8BE",
    "diamond_pushups": "J0DnG1_S92I",
    "dumbbell_bench_press": "VmB1G1K7v94",
    "dumbbell_bicep_curl": "in7PaeYlhrM",
    "dumbbell_curl": "in7PaeYlhrM",
    "dumbbell_fly": "eozdVDA78K0",
    "dumbbell_lateral_raise": "3VcKaXpzqRo",
    "dumbbell_row": "roCP6wCXPqo",
    "dumbbell_shoulder_press": "qEwKCR5JCog",
    "face_pull": "V8dZ3pyiCBo",
    "farmer_carry": "Fkzk_RqlYig",
    "farmers_walk": "Fkzk_RqlYig",
    "glute_bridge": "wPM8icPu6H8",
    "goblet_squat": "MxsFDhcyFyE",
    "hammer_curl": "zC3nLlEvin4",
    "hanging_knee_raise": "ytGaGIn3SjE",
    "hanging_leg_raise": "Pr1ieGZ5atk",
    "high_to_low_cable_fly": "Iwe6AmxVf7o",
    "hiit_circuit": "ml6cT4AZdqI",
    "hip_thrust": "LM8XHLYJoYs",
    "hollow_body_hold": "LlDNef_Ztsc",
    "incline_barbell_bench_press": "SrqOu55lrYU",
    "incline_barbell_press": "SrqOu55lrYU",
    "incline_dumbbell_bench_press": "8iPEnn-ltC8",
    "incline_dumbbell_curl": "soxrZlIl35U",
    "incline_dumbbell_press": "8iPEnn-ltC8",
    "inverted_row": "dvkIaarnf0g",
    "jogging": "_kGESn8ArrU",
    "jump_rope": "FJmRQ5iTXKE",
    "jump_rope_calf": "1BZM2Vre5oc",
    "jump_rope_hiit": "1BZM2Vre5oc",
    "jumping_jacks": "uLVt6u15L98",
    "kettlebell_swing": "YSxHifyI6s8",
    "lat_pulldown": "CAwf7n6Luuc",
    "lateral_raise": "3VcKaXpzqRo",
    "leg_curl": "F488k67BTNo",
    "leg_extension": "YyvSfVjQeL0",
    "leg_press": "yZmx_Ac3880",
    "low_to_high_cable_fly": "Iwe6AmxVf7o",
    "machine_chest_fly": "eozdVDA78K0",
    "machine_row": "xQNrFHEMhI4",
    "machine_shoulder_press": "qEwKCR5JCog",
    "mountain_climber": "nmwgirgXLYM",
    "mountain_climbers": "nmwgirgXLYM",
    "overhead_press": "2yjwXTZQDDI",
    "overhead_tricep_extension": "YbX7Wd8jQ-Q",
    "pallof_press": "AH_QZLm_0-s",
    "pec_deck": "Z57CtFmRMxA",
    "plank": "ASdvN_XEl_c",
    "preacher_curl": "fIWP-FRFNU0",
    "pull_up": "aAggnpPyR6E",
    "pullups": "aAggnpPyR6E",
    "push_press": "iaBVSJm78ko",
    "pushup": "IODxDxX7oi4",
    "pushups": "IODxDxX7oi4",
    "reverse_curl": "nRgxYX2Ve9w",
    "romanian_deadlift": "JCXUYuzwNrM",
    "rope_face_pull": "V8dZ3pyiCBo",
    "rope_pushdown": "vB5OHsJ3EME",
    "rowing_erg": "zQ82RYIFLN8",
    "rowing_machine": "zQ82RYIFLN8",
    "rowing_machine_intervals": "zQ82RYIFLN8",
    "running": "brFHyOtTwH4",
    "running_outdoor": "brFHyOtTwH4",
    "russian_twist": "wkD8rjkodUI",
    "seated_cable_row": "GZbfZ033f74",
    "seated_calf_raise": "JbyjNymZOt0",
    "seated_dumbbell_press": "qEwKCR5JCog",
    "seated_hamstring_curl": "F488k67BTNo",
    "seated_row": "GZbfZ033f74",
    "side_plank": "K2VljzCC16g",
    "single_arm_cable_fly": "Iwe6AmxVf7o",
    "single_arm_db_shoulder_press": "B-aVuyhvLHU",
    "single_arm_dumbbell_bench_press": "VmB1G1K7v94",
    "single_arm_dumbbell_row": "roCP6wCXPqo",
    "sit_up": "jDwoBqPH0jk",
    "situp": "jDwoBqPH0jk",
    "skull_crusher": "d_KZxkY_0cM",
    "split_squat": "2C-uNgKwPLE",
    "standing_calf_raise": "gwLzBJYoWlI",
    "step_up": "aajhW7DD1EA",
    "step_ups": "aajhW7DD1EA",
    "straight_arm_pulldown": "kiuVA0gs3EI",
    "sumo_deadlift": "Uv_DKDl7EjA",
    "superman_hold": "cc6UVRS7PW4",
    "suspension_row": "dvkIaarnf0g",
    "thrusters": "L219ltL15zk",
    "tibialis_raise": "y-wV4Venusw",
    "treadmill_run": "brFHyOtTwH4",
    "tricep_dip": "0326dy_-CzM",
    "tricep_pushdown": "2-LAMcpzODU",
    "tricep_rope_pushdown": "2-LAMcpzODU",
    "walking_lunge": "L8fvypPrzzs",
    "walking_lunges": "L8fvypPrzzs",
    "wall_sit": "-cdph8hv0O0",
    "weighted_plank": "pSHjTRCQxIw",
    "wide_grip_lat_pulldown": "CAwf7n6Luuc",
    "wide_pushups": "WDIpL0pjun0",
}


def video_id_for_slug(slug: str | None) -> str | None:
    if not slug:
        return None
    return EXERCISE_VIDEOS.get(slug.lower().strip())
