"""
Structured exercise seed data with equipment mappings.

Each exercise is a dict:
  slug:              Stable unique identifier (snake_case, never changes)
  name:              Display name
  primary_muscle:    MuscleGroup enum value
  secondary_muscles: List of MuscleGroup enum values
  equipment_bucket:  Legacy EquipmentType for backward compat
  movement_pattern:  MovementPattern enum value
  exercise_type:     ExerciseType enum value (strength | cardio | mobility)
  is_compound:       bool
  is_machine:        bool
  is_unilateral:     bool
  description:       Short text
  equipment:         List of {slug, role, required} dicts mapping to Equipment slugs

Equipment roles:
  primary  — the main implement (barbell, dumbbell, machine)
  support  — needed surface or rack (bench, squat rack)
  optional — helpful but exercise works without it (e.g. squat rack for bench press spotting)

To add exercises: append to the appropriate section list.
To add a new category: create the list and include it in SEED_EXERCISES at the bottom.
"""

# ─── Chest ───────────────────────────────────────────────────────────────────

CHEST = [
    {
        "slug": "barbell_bench_press",
        "name": "Barbell Bench Press",
        "primary_muscle": "chest",
        "secondary_muscles": ["triceps", "shoulders"],
        "equipment_bucket": "gym",
        "movement_pattern": "horizontal_press",
        "exercise_type": "strength",
        "is_compound": True,
        "is_machine": False,
        "is_unilateral": False,
        "description": "Classic horizontal press — primary chest builder",
        "equipment": [
            {"slug": "barbell", "role": "primary", "required": True},
            {"slug": "flat_bench", "role": "support", "required": True},
            {"slug": "squat_rack", "role": "optional", "required": False},
        ],
    },
    {
        "slug": "incline_barbell_press",
        "name": "Incline Barbell Press",
        "primary_muscle": "chest",
        "secondary_muscles": ["triceps", "shoulders"],
        "equipment_bucket": "gym",
        "movement_pattern": "horizontal_press",
        "exercise_type": "strength",
        "is_compound": True,
        "is_machine": False,
        "is_unilateral": False,
        "description": "Upper chest focus with inclined barbell press",
        "equipment": [
            {"slug": "barbell", "role": "primary", "required": True},
            {"slug": "adjustable_bench", "role": "support", "required": True},
        ],
    },
    {
        "slug": "decline_bench_press",
        "name": "Decline Bench Press",
        "primary_muscle": "chest",
        "secondary_muscles": ["triceps", "shoulders"],
        "equipment_bucket": "gym",
        "movement_pattern": "horizontal_press",
        "exercise_type": "strength",
        "is_compound": True,
        "is_machine": False,
        "is_unilateral": False,
        "description": "Lower chest press variation",
        "equipment": [
            {"slug": "barbell", "role": "primary", "required": True},
            {"slug": "adjustable_bench", "role": "support", "required": True},
        ],
    },
    {
        "slug": "dumbbell_bench_press",
        "name": "Dumbbell Bench Press",
        "primary_muscle": "chest",
        "secondary_muscles": ["triceps", "shoulders"],
        "equipment_bucket": "dumbbells",
        "movement_pattern": "horizontal_press",
        "exercise_type": "strength",
        "is_compound": True,
        "is_machine": False,
        "is_unilateral": False,
        "description": "Greater range of motion than barbell",
        "equipment": [
            {"slug": "dumbbells", "role": "primary", "required": True},
            {"slug": "flat_bench", "role": "support", "required": True},
        ],
    },
    {
        "slug": "incline_dumbbell_press",
        "name": "Incline Dumbbell Press",
        "primary_muscle": "chest",
        "secondary_muscles": ["triceps", "shoulders"],
        "equipment_bucket": "dumbbells",
        "movement_pattern": "horizontal_press",
        "exercise_type": "strength",
        "is_compound": True,
        "is_machine": False,
        "is_unilateral": False,
        "description": "Upper chest dumbbell pressing",
        "equipment": [
            {"slug": "dumbbells", "role": "primary", "required": True},
            {"slug": "adjustable_bench", "role": "support", "required": True},
        ],
    },
    {
        "slug": "decline_pushups",
        "name": "Decline Push-ups",
        "primary_muscle": "chest",
        "secondary_muscles": ["triceps", "shoulders"],
        "equipment_bucket": "bodyweight",
        "movement_pattern": "horizontal_press",
        "exercise_type": "strength",
        "is_compound": True,
        "is_machine": False,
        "is_unilateral": False,
        "description": "Harder push-up variation emphasizing upper chest",
        "equipment": [],
    },
    {
        "slug": "pushups",
        "name": "Push-ups",
        "primary_muscle": "chest",
        "secondary_muscles": ["triceps", "shoulders"],
        "equipment_bucket": "bodyweight",
        "movement_pattern": "horizontal_press",
        "exercise_type": "strength",
        "is_compound": True,
        "is_machine": False,
        "is_unilateral": False,
        "description": "Foundational bodyweight chest exercise",
        "equipment": [],
    },
    {
        "slug": "wide_pushups",
        "name": "Wide Push-ups",
        "primary_muscle": "chest",
        "secondary_muscles": ["shoulders"],
        "equipment_bucket": "bodyweight",
        "movement_pattern": "horizontal_press",
        "exercise_type": "strength",
        "is_compound": True,
        "is_machine": False,
        "is_unilateral": False,
        "description": "Wider hand placement for extra chest emphasis",
        "equipment": [],
    },
    {
        "slug": "diamond_pushups",
        "name": "Diamond Push-ups",
        "primary_muscle": "triceps",
        "secondary_muscles": ["chest", "shoulders"],
        "equipment_bucket": "bodyweight",
        "movement_pattern": "horizontal_press",
        "exercise_type": "strength",
        "is_compound": True,
        "is_machine": False,
        "is_unilateral": False,
        "description": "Close-hand push-up emphasizing triceps",
        "equipment": [],
    },
    {
        "slug": "chest_dips",
        "name": "Chest Dips",
        "primary_muscle": "chest",
        "secondary_muscles": ["triceps"],
        "equipment_bucket": "home",
        "movement_pattern": "horizontal_press",
        "exercise_type": "strength",
        "is_compound": True,
        "is_machine": False,
        "is_unilateral": False,
        "description": "Forward-lean dip for chest emphasis — needs dip bars",
        "equipment": [
            {"slug": "dip_bars", "role": "primary", "required": True},
        ],
    },
    {
        "slug": "dumbbell_fly",
        "name": "Dumbbell Fly",
        "primary_muscle": "chest",
        "secondary_muscles": [],
        "equipment_bucket": "dumbbells",
        "movement_pattern": "isolation",
        "exercise_type": "strength",
        "is_compound": False,
        "is_machine": False,
        "is_unilateral": False,
        "description": "Isolation stretch for the chest",
        "equipment": [
            {"slug": "dumbbells", "role": "primary", "required": True},
            {"slug": "flat_bench", "role": "support", "required": True},
        ],
    },
    {
        "slug": "cable_fly",
        "name": "Cable Fly",
        "primary_muscle": "chest",
        "secondary_muscles": [],
        "equipment_bucket": "gym",
        "movement_pattern": "isolation",
        "exercise_type": "strength",
        "is_compound": False,
        "is_machine": False,
        "is_unilateral": False,
        "description": "Constant tension chest isolation on cable",
        "equipment": [
            {"slug": "cable_machine", "role": "primary", "required": True},
        ],
    },
    {
        "slug": "machine_chest_press",
        "name": "Machine Chest Press",
        "primary_muscle": "chest",
        "secondary_muscles": ["triceps", "shoulders"],
        "equipment_bucket": "gym",
        "movement_pattern": "horizontal_press",
        "exercise_type": "strength",
        "is_compound": True,
        "is_machine": True,
        "is_unilateral": False,
        "description": "Stable machine-based chest press",
        "equipment": [
            {"slug": "chest_press_machine", "role": "primary", "required": True},
        ],
    },
    {
        "slug": "pec_deck",
        "name": "Pec Deck",
        "primary_muscle": "chest",
        "secondary_muscles": [],
        "equipment_bucket": "gym",
        "movement_pattern": "isolation",
        "exercise_type": "strength",
        "is_compound": False,
        "is_machine": True,
        "is_unilateral": False,
        "description": "Machine chest fly isolation",
        "equipment": [
            {"slug": "leverage_machines", "role": "primary", "required": True},
        ],
    },
    {
        "slug": "scap_pushup",
        "name": "Scap Push-up",
        "primary_muscle": "back",
        "secondary_muscles": ["shoulders"],
        "equipment_bucket": "bodyweight",
        "movement_pattern": "mobility",
        "exercise_type": "mobility",
        "is_compound": False,
        "is_machine": False,
        "is_unilateral": False,
        "description": "Protract and retract the scapula at the bottom of a push-up position — improves shoulder health",
        "equipment": [],
    },
]

# ─── Back ────────────────────────────────────────────────────────────────────

BACK = [
    {
        "slug": "deadlift",
        "name": "Deadlift",
        "primary_muscle": "back",
        "secondary_muscles": ["hamstrings", "glutes", "core"],
        "equipment_bucket": "gym",
        "movement_pattern": "hinge",
        "exercise_type": "strength",
        "is_compound": True,
        "is_machine": False,
        "is_unilateral": False,
        "description": "King of compound lifts — full posterior chain",
        "equipment": [
            {"slug": "barbell", "role": "primary", "required": True},
            {"slug": "weight_plates", "role": "support", "required": True},
        ],
    },
    {
        "slug": "romanian_deadlift",
        "name": "Romanian Deadlift",
        "primary_muscle": "hamstrings",
        "secondary_muscles": ["glutes", "back"],
        "equipment_bucket": "gym",
        "movement_pattern": "hinge",
        "exercise_type": "strength",
        "is_compound": True,
        "is_machine": False,
        "is_unilateral": False,
        "description": "Hip-hinge pattern targeting hamstrings",
        "equipment": [
            {"slug": "barbell", "role": "primary", "required": True},
        ],
    },
    {
        "slug": "rack_pull",
        "name": "Rack Pull",
        "primary_muscle": "back",
        "secondary_muscles": ["glutes", "hamstrings"],
        "equipment_bucket": "gym",
        "movement_pattern": "hinge",
        "exercise_type": "strength",
        "is_compound": True,
        "is_machine": False,
        "is_unilateral": False,
        "description": "Partial deadlift emphasizing upper posterior chain",
        "equipment": [
            {"slug": "barbell", "role": "primary", "required": True},
            {"slug": "power_rack", "role": "support", "required": True},
        ],
    },
    {
        "slug": "barbell_row",
        "name": "Barbell Row",
        "primary_muscle": "back",
        "secondary_muscles": ["biceps"],
        "equipment_bucket": "gym",
        "movement_pattern": "horizontal_pull",
        "exercise_type": "strength",
        "is_compound": True,
        "is_machine": False,
        "is_unilateral": False,
        "description": "Horizontal pull — lat and mid-back thickness",
        "equipment": [
            {"slug": "barbell", "role": "primary", "required": True},
        ],
    },
    {
        "slug": "pendlay_row",
        "name": "Pendlay Row",
        "primary_muscle": "back",
        "secondary_muscles": ["biceps"],
        "equipment_bucket": "gym",
        "movement_pattern": "horizontal_pull",
        "exercise_type": "strength",
        "is_compound": True,
        "is_machine": False,
        "is_unilateral": False,
        "description": "Explosive strict row from the floor",
        "equipment": [
            {"slug": "barbell", "role": "primary", "required": True},
        ],
    },
    {
        "slug": "t_bar_row",
        "name": "T-Bar Row",
        "primary_muscle": "back",
        "secondary_muscles": ["biceps"],
        "equipment_bucket": "gym",
        "movement_pattern": "horizontal_pull",
        "exercise_type": "strength",
        "is_compound": True,
        "is_machine": False,
        "is_unilateral": False,
        "description": "Heavy rowing variation for back thickness",
        "equipment": [
            {"slug": "barbell", "role": "primary", "required": True},
            {"slug": "landmine_attachment", "role": "support", "required": True},
        ],
    },
    {
        "slug": "dumbbell_row",
        "name": "Dumbbell Row",
        "primary_muscle": "back",
        "secondary_muscles": ["biceps"],
        "equipment_bucket": "dumbbells",
        "movement_pattern": "horizontal_pull",
        "exercise_type": "strength",
        "is_compound": True,
        "is_machine": False,
        "is_unilateral": True,
        "description": "Unilateral back builder with good stretch",
        "equipment": [
            {"slug": "dumbbells", "role": "primary", "required": True},
            {"slug": "flat_bench", "role": "support", "required": False},
        ],
    },
    {
        "slug": "chest_supported_row",
        "name": "Chest Supported Row",
        "primary_muscle": "back",
        "secondary_muscles": ["biceps"],
        "equipment_bucket": "dumbbells",
        "movement_pattern": "horizontal_pull",
        "exercise_type": "strength",
        "is_compound": True,
        "is_machine": False,
        "is_unilateral": False,
        "description": "Lower-back-friendly incline dumbbell row",
        "equipment": [
            {"slug": "dumbbells", "role": "primary", "required": True},
            {"slug": "adjustable_bench", "role": "support", "required": True},
        ],
    },
    {
        "slug": "pullups",
        "name": "Pull-ups",
        "primary_muscle": "back",
        "secondary_muscles": ["biceps"],
        "equipment_bucket": "home",
        "movement_pattern": "vertical_pull",
        "exercise_type": "strength",
        "is_compound": True,
        "is_machine": False,
        "is_unilateral": False,
        "description": "Best bodyweight back exercise — requires pull-up bar",
        "equipment": [
            {"slug": "pull_up_bar", "role": "primary", "required": True},
        ],
    },
    {
        "slug": "chinups",
        "name": "Chin-ups",
        "primary_muscle": "back",
        "secondary_muscles": ["biceps"],
        "equipment_bucket": "home",
        "movement_pattern": "vertical_pull",
        "exercise_type": "strength",
        "is_compound": True,
        "is_machine": False,
        "is_unilateral": False,
        "description": "Supinated pull-up — more biceps involvement",
        "equipment": [
            {"slug": "pull_up_bar", "role": "primary", "required": True},
        ],
    },
    {
        "slug": "assisted_pullup",
        "name": "Assisted Pull-up",
        "primary_muscle": "back",
        "secondary_muscles": ["biceps"],
        "equipment_bucket": "gym",
        "movement_pattern": "vertical_pull",
        "exercise_type": "strength",
        "is_compound": True,
        "is_machine": True,
        "is_unilateral": False,
        "description": "Machine-assisted pull-up for beginners building lat strength",
        "equipment": [
            {"slug": "assisted_pullup_machine", "role": "primary", "required": True},
        ],
    },
    {
        "slug": "lat_pulldown",
        "name": "Lat Pulldown",
        "primary_muscle": "back",
        "secondary_muscles": ["biceps"],
        "equipment_bucket": "gym",
        "movement_pattern": "vertical_pull",
        "exercise_type": "strength",
        "is_compound": True,
        "is_machine": True,
        "is_unilateral": False,
        "description": "Cable pull-down for lat width",
        "equipment": [
            {"slug": "lat_pulldown_machine", "role": "primary", "required": True},
        ],
    },
    {
        "slug": "seated_cable_row",
        "name": "Seated Cable Row",
        "primary_muscle": "back",
        "secondary_muscles": ["biceps"],
        "equipment_bucket": "gym",
        "movement_pattern": "horizontal_pull",
        "exercise_type": "strength",
        "is_compound": True,
        "is_machine": False,
        "is_unilateral": False,
        "description": "Horizontal cable pull for mid-back thickness",
        "equipment": [
            {"slug": "cable_machine", "role": "primary", "required": True},
        ],
    },
    {
        "slug": "straight_arm_pulldown",
        "name": "Straight-arm Pulldown",
        "primary_muscle": "back",
        "secondary_muscles": [],
        "equipment_bucket": "gym",
        "movement_pattern": "isolation",
        "exercise_type": "strength",
        "is_compound": False,
        "is_machine": False,
        "is_unilateral": False,
        "description": "Lat isolation keeping arms straight on cable",
        "equipment": [
            {"slug": "cable_machine", "role": "primary", "required": True},
        ],
    },
    {
        "slug": "face_pull",
        "name": "Face Pull",
        "primary_muscle": "shoulders",
        "secondary_muscles": ["back"],
        "equipment_bucket": "gym",
        "movement_pattern": "horizontal_pull",
        "exercise_type": "strength",
        "is_compound": False,
        "is_machine": False,
        "is_unilateral": False,
        "description": "Rear delt and rotator cuff health with cable rope",
        "equipment": [
            {"slug": "cable_machine", "role": "primary", "required": True},
        ],
    },
    {
        "slug": "inverted_row",
        "name": "Inverted Row",
        "primary_muscle": "back",
        "secondary_muscles": ["biceps"],
        "equipment_bucket": "home",
        "movement_pattern": "horizontal_pull",
        "exercise_type": "strength",
        "is_compound": True,
        "is_machine": False,
        "is_unilateral": False,
        "description": "Horizontal bodyweight pull from a low bar",
        "equipment": [
            {"slug": "pull_up_bar", "role": "primary", "required": False},
        ],
    },
    {
        "slug": "superman_hold",
        "name": "Superman Hold",
        "primary_muscle": "back",
        "secondary_muscles": ["glutes"],
        "equipment_bucket": "bodyweight",
        "movement_pattern": "anti_extension",
        "exercise_type": "strength",
        "is_compound": False,
        "is_machine": False,
        "is_unilateral": False,
        "description": "Posterior chain and spinal erector isometric hold",
        "equipment": [],
    },
    {
        "slug": "thoracic_rotation",
        "name": "Thoracic Rotation",
        "primary_muscle": "back",
        "secondary_muscles": ["core"],
        "equipment_bucket": "bodyweight",
        "movement_pattern": "mobility",
        "exercise_type": "mobility",
        "is_compound": False,
        "is_machine": False,
        "is_unilateral": False,
        "description": "Controlled rotation drill for thoracic spine mobility",
        "equipment": [],
    },
    {
        "slug": "back_extension_back",
        "name": "Back Extension (Back Focused)",
        "primary_muscle": "back",
        "secondary_muscles": ["glutes", "hamstrings"],
        "equipment_bucket": "gym",
        "movement_pattern": "hinge",
        "exercise_type": "strength",
        "is_compound": False,
        "is_machine": False,
        "is_unilateral": False,
        "description": "45-degree hyperextension bench — neutral spine targets spinal erectors",
        "equipment": [
            {"slug": "leverage_machines", "role": "primary", "required": True},
        ],
    },
    {
        "slug": "back_extension_glute",
        "name": "Back Extension (Glute Focused)",
        "primary_muscle": "glutes",
        "secondary_muscles": ["hamstrings", "back"],
        "equipment_bucket": "gym",
        "movement_pattern": "hinge",
        "exercise_type": "strength",
        "is_compound": False,
        "is_machine": False,
        "is_unilateral": False,
        "description": "45-degree hyperextension bench — posterior pelvic tilt maximises glute activation",
        "equipment": [
            {"slug": "leverage_machines", "role": "primary", "required": True},
        ],
    },
]

# ─── Shoulders ───────────────────────────────────────────────────────────────

SHOULDERS = [
    {
        "slug": "overhead_press",
        "name": "Overhead Press",
        "primary_muscle": "shoulders",
        "secondary_muscles": ["triceps"],
        "equipment_bucket": "gym",
        "movement_pattern": "vertical_press",
        "exercise_type": "strength",
        "is_compound": True,
        "is_machine": False,
        "is_unilateral": False,
        "description": "Standing or seated barbell shoulder press",
        "equipment": [
            {"slug": "barbell", "role": "primary", "required": True},
        ],
    },
    {
        "slug": "push_press",
        "name": "Push Press",
        "primary_muscle": "shoulders",
        "secondary_muscles": ["triceps", "quads"],
        "equipment_bucket": "gym",
        "movement_pattern": "vertical_press",
        "exercise_type": "strength",
        "is_compound": True,
        "is_machine": False,
        "is_unilateral": False,
        "description": "Explosive overhead press using leg drive",
        "equipment": [
            {"slug": "barbell", "role": "primary", "required": True},
        ],
    },
    {
        "slug": "dumbbell_shoulder_press",
        "name": "Dumbbell Shoulder Press",
        "primary_muscle": "shoulders",
        "secondary_muscles": ["triceps"],
        "equipment_bucket": "dumbbells",
        "movement_pattern": "vertical_press",
        "exercise_type": "strength",
        "is_compound": True,
        "is_machine": False,
        "is_unilateral": False,
        "description": "Seated or standing dumbbell press for shoulders",
        "equipment": [
            {"slug": "dumbbells", "role": "primary", "required": True},
            {"slug": "adjustable_bench", "role": "support", "required": False},
        ],
    },
    {
        "slug": "arnold_press",
        "name": "Arnold Press",
        "primary_muscle": "shoulders",
        "secondary_muscles": ["triceps"],
        "equipment_bucket": "dumbbells",
        "movement_pattern": "vertical_press",
        "exercise_type": "strength",
        "is_compound": True,
        "is_machine": False,
        "is_unilateral": False,
        "description": "Rotational press hitting all three delt heads",
        "equipment": [
            {"slug": "dumbbells", "role": "primary", "required": True},
        ],
    },
    {
        "slug": "machine_shoulder_press",
        "name": "Machine Shoulder Press",
        "primary_muscle": "shoulders",
        "secondary_muscles": ["triceps"],
        "equipment_bucket": "gym",
        "movement_pattern": "vertical_press",
        "exercise_type": "strength",
        "is_compound": True,
        "is_machine": True,
        "is_unilateral": False,
        "description": "Stable overhead press on shoulder machine",
        "equipment": [
            {"slug": "shoulder_press_machine", "role": "primary", "required": True},
        ],
    },
    {
        "slug": "lateral_raise",
        "name": "Lateral Raise",
        "primary_muscle": "shoulders",
        "secondary_muscles": [],
        "equipment_bucket": "dumbbells",
        "movement_pattern": "isolation",
        "exercise_type": "strength",
        "is_compound": False,
        "is_machine": False,
        "is_unilateral": False,
        "description": "Side delt isolation — shoulder width",
        "equipment": [
            {"slug": "dumbbells", "role": "primary", "required": True},
        ],
    },
    {
        "slug": "front_raise",
        "name": "Front Raise",
        "primary_muscle": "shoulders",
        "secondary_muscles": [],
        "equipment_bucket": "dumbbells",
        "movement_pattern": "isolation",
        "exercise_type": "strength",
        "is_compound": False,
        "is_machine": False,
        "is_unilateral": False,
        "description": "Anterior delt isolation",
        "equipment": [
            {"slug": "dumbbells", "role": "primary", "required": True},
        ],
    },
    {
        "slug": "rear_delt_fly",
        "name": "Rear Delt Fly",
        "primary_muscle": "shoulders",
        "secondary_muscles": ["back"],
        "equipment_bucket": "dumbbells",
        "movement_pattern": "isolation",
        "exercise_type": "strength",
        "is_compound": False,
        "is_machine": False,
        "is_unilateral": False,
        "description": "Rear shoulder isolation — posture and balance",
        "equipment": [
            {"slug": "dumbbells", "role": "primary", "required": True},
        ],
    },
    {
        "slug": "cable_lateral_raise",
        "name": "Cable Lateral Raise",
        "primary_muscle": "shoulders",
        "secondary_muscles": [],
        "equipment_bucket": "gym",
        "movement_pattern": "isolation",
        "exercise_type": "strength",
        "is_compound": False,
        "is_machine": False,
        "is_unilateral": True,
        "description": "Constant-tension side delt work on cable",
        "equipment": [
            {"slug": "cable_machine", "role": "primary", "required": True},
        ],
    },
    {
        "slug": "upright_row",
        "name": "Upright Row",
        "primary_muscle": "shoulders",
        "secondary_muscles": ["traps"],
        "equipment_bucket": "gym",
        "movement_pattern": "vertical_pull",
        "exercise_type": "strength",
        "is_compound": True,
        "is_machine": False,
        "is_unilateral": False,
        "description": "Vertical pull for shoulders and upper traps",
        "equipment": [
            {"slug": "barbell", "role": "primary", "required": True},
        ],
    },
    {
        "slug": "pike_pushups",
        "name": "Pike Push-ups",
        "primary_muscle": "shoulders",
        "secondary_muscles": ["triceps"],
        "equipment_bucket": "bodyweight",
        "movement_pattern": "vertical_press",
        "exercise_type": "strength",
        "is_compound": True,
        "is_machine": False,
        "is_unilateral": False,
        "description": "Bodyweight overhead press progression",
        "equipment": [],
    },
    {
        "slug": "landmine_press",
        "name": "Landmine Press",
        "primary_muscle": "shoulders",
        "secondary_muscles": ["chest", "triceps"],
        "equipment_bucket": "gym",
        "movement_pattern": "vertical_press",
        "exercise_type": "strength",
        "is_compound": True,
        "is_machine": False,
        "is_unilateral": True,
        "description": "Angled press from landmine attachment — shoulder-friendly",
        "equipment": [
            {"slug": "barbell", "role": "primary", "required": True},
            {"slug": "landmine_attachment", "role": "support", "required": True},
        ],
    },
    {
        "slug": "band_pull_apart",
        "name": "Band Pull-Apart",
        "primary_muscle": "shoulders",
        "secondary_muscles": ["back"],
        "equipment_bucket": "home",
        "movement_pattern": "horizontal_pull",
        "exercise_type": "strength",
        "is_compound": False,
        "is_machine": False,
        "is_unilateral": False,
        "description": "Resistance band pull for rear delts and scapular health",
        "equipment": [
            {"slug": "resistance_bands", "role": "primary", "required": True},
        ],
    },
    {
        "slug": "wall_slide",
        "name": "Wall Slide",
        "primary_muscle": "shoulders",
        "secondary_muscles": ["back"],
        "equipment_bucket": "bodyweight",
        "movement_pattern": "mobility",
        "exercise_type": "mobility",
        "is_compound": False,
        "is_machine": False,
        "is_unilateral": False,
        "description": "Overhead wall slide drill for shoulder mobility and stability",
        "equipment": [],
    },
]

# ─── Biceps ──────────────────────────────────────────────────────────────────

BICEPS = [
    {
        "slug": "barbell_curl",
        "name": "Barbell Curl",
        "primary_muscle": "biceps",
        "secondary_muscles": [],
        "equipment_bucket": "gym",
        "movement_pattern": "isolation",
        "exercise_type": "strength",
        "is_compound": False,
        "is_machine": False,
        "is_unilateral": False,
        "description": "Classic barbell bicep curl",
        "equipment": [
            {"slug": "barbell", "role": "primary", "required": True},
        ],
    },
    {
        "slug": "ez_bar_curl",
        "name": "EZ Bar Curl",
        "primary_muscle": "biceps",
        "secondary_muscles": [],
        "equipment_bucket": "gym",
        "movement_pattern": "isolation",
        "exercise_type": "strength",
        "is_compound": False,
        "is_machine": False,
        "is_unilateral": False,
        "description": "More wrist-friendly curling variation",
        "equipment": [
            {"slug": "ez_curl_bar", "role": "primary", "required": True},
        ],
    },
    {
        "slug": "dumbbell_curl",
        "name": "Dumbbell Curl",
        "primary_muscle": "biceps",
        "secondary_muscles": [],
        "equipment_bucket": "dumbbells",
        "movement_pattern": "isolation",
        "exercise_type": "strength",
        "is_compound": False,
        "is_machine": False,
        "is_unilateral": False,
        "description": "Alternating or simultaneous dumbbell curl",
        "equipment": [
            {"slug": "dumbbells", "role": "primary", "required": True},
        ],
    },
    {
        "slug": "hammer_curl",
        "name": "Hammer Curl",
        "primary_muscle": "biceps",
        "secondary_muscles": ["forearms"],
        "equipment_bucket": "dumbbells",
        "movement_pattern": "isolation",
        "exercise_type": "strength",
        "is_compound": False,
        "is_machine": False,
        "is_unilateral": False,
        "description": "Neutral grip curl for brachialis and forearm thickness",
        "equipment": [
            {"slug": "dumbbells", "role": "primary", "required": True},
        ],
    },
    {
        "slug": "incline_dumbbell_curl",
        "name": "Incline Dumbbell Curl",
        "primary_muscle": "biceps",
        "secondary_muscles": [],
        "equipment_bucket": "dumbbells",
        "movement_pattern": "isolation",
        "exercise_type": "strength",
        "is_compound": False,
        "is_machine": False,
        "is_unilateral": False,
        "description": "Long-head focused curl on incline bench",
        "equipment": [
            {"slug": "dumbbells", "role": "primary", "required": True},
            {"slug": "adjustable_bench", "role": "support", "required": True},
        ],
    },
    {
        "slug": "concentration_curl",
        "name": "Concentration Curl",
        "primary_muscle": "biceps",
        "secondary_muscles": [],
        "equipment_bucket": "dumbbells",
        "movement_pattern": "isolation",
        "exercise_type": "strength",
        "is_compound": False,
        "is_machine": False,
        "is_unilateral": True,
        "description": "Strict unilateral bicep isolation",
        "equipment": [
            {"slug": "dumbbells", "role": "primary", "required": True},
        ],
    },
    {
        "slug": "preacher_curl",
        "name": "Preacher Curl",
        "primary_muscle": "biceps",
        "secondary_muscles": [],
        "equipment_bucket": "gym",
        "movement_pattern": "isolation",
        "exercise_type": "strength",
        "is_compound": False,
        "is_machine": False,
        "is_unilateral": False,
        "description": "Isolates biceps with preacher bench support",
        "equipment": [
            {"slug": "ez_curl_bar", "role": "primary", "required": True},
            {"slug": "leverage_machines", "role": "support", "required": True},
        ],
    },
    {
        "slug": "cable_curl",
        "name": "Cable Curl",
        "primary_muscle": "biceps",
        "secondary_muscles": [],
        "equipment_bucket": "gym",
        "movement_pattern": "isolation",
        "exercise_type": "strength",
        "is_compound": False,
        "is_machine": False,
        "is_unilateral": False,
        "description": "Constant tension curl on cable machine",
        "equipment": [
            {"slug": "cable_machine", "role": "primary", "required": True},
        ],
    },
]

# ─── Triceps ─────────────────────────────────────────────────────────────────

TRICEPS = [
    {
        "slug": "skull_crusher",
        "name": "Skull Crusher",
        "primary_muscle": "triceps",
        "secondary_muscles": [],
        "equipment_bucket": "gym",
        "movement_pattern": "isolation",
        "exercise_type": "strength",
        "is_compound": False,
        "is_machine": False,
        "is_unilateral": False,
        "description": "Lying tricep extension with barbell or EZ bar",
        "equipment": [
            {"slug": "ez_curl_bar", "role": "primary", "required": True},
            {"slug": "flat_bench", "role": "support", "required": True},
        ],
    },
    {
        "slug": "tricep_pushdown",
        "name": "Tricep Pushdown",
        "primary_muscle": "triceps",
        "secondary_muscles": [],
        "equipment_bucket": "gym",
        "movement_pattern": "isolation",
        "exercise_type": "strength",
        "is_compound": False,
        "is_machine": False,
        "is_unilateral": False,
        "description": "Cable pushdown for tricep isolation",
        "equipment": [
            {"slug": "cable_machine", "role": "primary", "required": True},
        ],
    },
    {
        "slug": "rope_pushdown",
        "name": "Rope Pushdown",
        "primary_muscle": "triceps",
        "secondary_muscles": [],
        "equipment_bucket": "gym",
        "movement_pattern": "isolation",
        "exercise_type": "strength",
        "is_compound": False,
        "is_machine": False,
        "is_unilateral": False,
        "description": "Cable rope pushdown for full lockout and flare",
        "equipment": [
            {"slug": "cable_machine", "role": "primary", "required": True},
        ],
    },
    {
        "slug": "close_grip_bench_press",
        "name": "Close-grip Bench Press",
        "primary_muscle": "triceps",
        "secondary_muscles": ["chest"],
        "equipment_bucket": "gym",
        "movement_pattern": "horizontal_press",
        "exercise_type": "strength",
        "is_compound": True,
        "is_machine": False,
        "is_unilateral": False,
        "description": "Bench press variation with close grip for triceps",
        "equipment": [
            {"slug": "barbell", "role": "primary", "required": True},
            {"slug": "flat_bench", "role": "support", "required": True},
        ],
    },
    {
        "slug": "overhead_tricep_extension",
        "name": "Overhead Tricep Extension",
        "primary_muscle": "triceps",
        "secondary_muscles": [],
        "equipment_bucket": "dumbbells",
        "movement_pattern": "isolation",
        "exercise_type": "strength",
        "is_compound": False,
        "is_machine": False,
        "is_unilateral": False,
        "description": "Long head stretch with overhead dumbbell position",
        "equipment": [
            {"slug": "dumbbells", "role": "primary", "required": True},
        ],
    },
    {
        "slug": "bench_dips",
        "name": "Bench Dips",
        "primary_muscle": "triceps",
        "secondary_muscles": ["chest"],
        "equipment_bucket": "bodyweight",
        "movement_pattern": "horizontal_press",
        "exercise_type": "strength",
        "is_compound": True,
        "is_machine": False,
        "is_unilateral": False,
        "description": "Bodyweight tricep dip using a bench or chair",
        "equipment": [],
    },
    {
        "slug": "kickbacks",
        "name": "Kickbacks",
        "primary_muscle": "triceps",
        "secondary_muscles": [],
        "equipment_bucket": "dumbbells",
        "movement_pattern": "isolation",
        "exercise_type": "strength",
        "is_compound": False,
        "is_machine": False,
        "is_unilateral": True,
        "description": "Strict tricep lockout with dumbbell",
        "equipment": [
            {"slug": "dumbbells", "role": "primary", "required": True},
        ],
    },
]

# ─── Quads ───────────────────────────────────────────────────────────────────

QUADS = [
    {
        "slug": "barbell_squat",
        "name": "Barbell Squat",
        "primary_muscle": "quads",
        "secondary_muscles": ["glutes", "hamstrings"],
        "equipment_bucket": "gym",
        "movement_pattern": "squat",
        "exercise_type": "strength",
        "is_compound": True,
        "is_machine": False,
        "is_unilateral": False,
        "description": "Foundational lower body compound movement",
        "equipment": [
            {"slug": "barbell", "role": "primary", "required": True},
            {"slug": "squat_rack", "role": "support", "required": True},
        ],
    },
    {
        "slug": "front_squat",
        "name": "Front Squat",
        "primary_muscle": "quads",
        "secondary_muscles": ["core", "glutes"],
        "equipment_bucket": "gym",
        "movement_pattern": "squat",
        "exercise_type": "strength",
        "is_compound": True,
        "is_machine": False,
        "is_unilateral": False,
        "description": "Quad-dominant squat with very upright torso",
        "equipment": [
            {"slug": "barbell", "role": "primary", "required": True},
            {"slug": "squat_rack", "role": "support", "required": True},
        ],
    },
    {
        "slug": "leg_press",
        "name": "Leg Press",
        "primary_muscle": "quads",
        "secondary_muscles": ["glutes", "hamstrings"],
        "equipment_bucket": "gym",
        "movement_pattern": "squat",
        "exercise_type": "strength",
        "is_compound": True,
        "is_machine": True,
        "is_unilateral": False,
        "description": "Machine squat variation — high volume friendly",
        "equipment": [
            {"slug": "leg_press_machine", "role": "primary", "required": True},
        ],
    },
    {
        "slug": "leg_extension",
        "name": "Leg Extension",
        "primary_muscle": "quads",
        "secondary_muscles": [],
        "equipment_bucket": "gym",
        "movement_pattern": "isolation",
        "exercise_type": "strength",
        "is_compound": False,
        "is_machine": True,
        "is_unilateral": False,
        "description": "Quad isolation on leg extension machine",
        "equipment": [
            {"slug": "leg_extension_machine", "role": "primary", "required": True},
        ],
    },
    {
        "slug": "hack_squat",
        "name": "Hack Squat",
        "primary_muscle": "quads",
        "secondary_muscles": ["glutes"],
        "equipment_bucket": "gym",
        "movement_pattern": "squat",
        "exercise_type": "strength",
        "is_compound": True,
        "is_machine": True,
        "is_unilateral": False,
        "description": "Machine squat with upright torso and loaded back pad",
        "equipment": [
            {"slug": "hack_squat_machine", "role": "primary", "required": True},
        ],
    },
    {
        "slug": "smith_machine_squat",
        "name": "Smith Machine Squat",
        "primary_muscle": "quads",
        "secondary_muscles": ["glutes", "hamstrings"],
        "equipment_bucket": "gym",
        "movement_pattern": "squat",
        "exercise_type": "strength",
        "is_compound": True,
        "is_machine": True,
        "is_unilateral": False,
        "description": "Guided barbell squat for beginners or heavy volume",
        "equipment": [
            {"slug": "smith_machine", "role": "primary", "required": True},
        ],
    },
    {
        "slug": "bulgarian_split_squat",
        "name": "Bulgarian Split Squat",
        "primary_muscle": "quads",
        "secondary_muscles": ["glutes", "hamstrings"],
        "equipment_bucket": "dumbbells",
        "movement_pattern": "lunge",
        "exercise_type": "strength",
        "is_compound": True,
        "is_machine": False,
        "is_unilateral": True,
        "description": "Unilateral leg exercise with rear foot elevated",
        "equipment": [
            {"slug": "dumbbells", "role": "primary", "required": False},
        ],
    },
    {
        "slug": "walking_lunges",
        "name": "Walking Lunges",
        "primary_muscle": "quads",
        "secondary_muscles": ["glutes", "hamstrings"],
        "equipment_bucket": "bodyweight",
        "movement_pattern": "lunge",
        "exercise_type": "strength",
        "is_compound": True,
        "is_machine": False,
        "is_unilateral": True,
        "description": "Dynamic forward lunge for strength and coordination",
        "equipment": [
            {"slug": "dumbbells", "role": "optional", "required": False},
        ],
    },
    {
        "slug": "reverse_lunges",
        "name": "Reverse Lunges",
        "primary_muscle": "quads",
        "secondary_muscles": ["glutes", "hamstrings"],
        "equipment_bucket": "bodyweight",
        "movement_pattern": "lunge",
        "exercise_type": "strength",
        "is_compound": True,
        "is_machine": False,
        "is_unilateral": True,
        "description": "Knee-friendly lunge variation stepping backward",
        "equipment": [
            {"slug": "dumbbells", "role": "optional", "required": False},
        ],
    },
    {
        "slug": "goblet_squat",
        "name": "Goblet Squat",
        "primary_muscle": "quads",
        "secondary_muscles": ["glutes", "core"],
        "equipment_bucket": "dumbbells",
        "movement_pattern": "squat",
        "exercise_type": "strength",
        "is_compound": True,
        "is_machine": False,
        "is_unilateral": False,
        "description": "Beginner-friendly squat holding a dumbbell at chest",
        "equipment": [
            {"slug": "dumbbells", "role": "primary", "required": True},
        ],
    },
    {
        "slug": "step_ups",
        "name": "Step-ups",
        "primary_muscle": "quads",
        "secondary_muscles": ["glutes", "hamstrings"],
        "equipment_bucket": "dumbbells",
        "movement_pattern": "lunge",
        "exercise_type": "strength",
        "is_compound": True,
        "is_machine": False,
        "is_unilateral": True,
        "description": "Single-leg step-up with dumbbells for strength",
        "equipment": [
            {"slug": "dumbbells", "role": "primary", "required": False},
            {"slug": "plyo_box", "role": "support", "required": False},
        ],
    },
    {
        "slug": "bodyweight_squat",
        "name": "Bodyweight Squat",
        "primary_muscle": "quads",
        "secondary_muscles": ["glutes"],
        "equipment_bucket": "bodyweight",
        "movement_pattern": "squat",
        "exercise_type": "strength",
        "is_compound": True,
        "is_machine": False,
        "is_unilateral": False,
        "description": "Air squat with no added weight",
        "equipment": [],
    },
    {
        "slug": "wall_sit",
        "name": "Wall Sit",
        "primary_muscle": "quads",
        "secondary_muscles": [],
        "equipment_bucket": "bodyweight",
        "movement_pattern": "squat",
        "exercise_type": "strength",
        "is_compound": False,
        "is_machine": False,
        "is_unilateral": False,
        "description": "Isometric quad endurance hold against a wall",
        "equipment": [],
    },
    {
        "slug": "landmine_squat",
        "name": "Landmine Squat",
        "primary_muscle": "quads",
        "secondary_muscles": ["glutes", "core"],
        "equipment_bucket": "gym",
        "movement_pattern": "squat",
        "exercise_type": "strength",
        "is_compound": True,
        "is_machine": False,
        "is_unilateral": False,
        "description": "Goblet-style squat holding a landmine — very beginner-friendly",
        "equipment": [
            {"slug": "barbell", "role": "primary", "required": True},
            {"slug": "landmine_attachment", "role": "support", "required": True},
        ],
    },
    {
        "slug": "couch_stretch",
        "name": "Couch Stretch",
        "primary_muscle": "quads",
        "secondary_muscles": ["hip_flexors"],
        "equipment_bucket": "bodyweight",
        "movement_pattern": "mobility",
        "exercise_type": "mobility",
        "is_compound": False,
        "is_machine": False,
        "is_unilateral": True,
        "description": "Deep hip flexor and quad stretch with rear foot elevated",
        "equipment": [],
    },
]

# ─── Hamstrings ──────────────────────────────────────────────────────────────

HAMSTRINGS = [
    {
        "slug": "leg_curl",
        "name": "Leg Curl",
        "primary_muscle": "hamstrings",
        "secondary_muscles": [],
        "equipment_bucket": "gym",
        "movement_pattern": "isolation",
        "exercise_type": "strength",
        "is_compound": False,
        "is_machine": True,
        "is_unilateral": False,
        "description": "Lying hamstring curl on machine",
        "equipment": [
            {"slug": "leg_curl_machine", "role": "primary", "required": True},
        ],
    },
    {
        "slug": "seated_hamstring_curl",
        "name": "Seated Hamstring Curl",
        "primary_muscle": "hamstrings",
        "secondary_muscles": [],
        "equipment_bucket": "gym",
        "movement_pattern": "isolation",
        "exercise_type": "strength",
        "is_compound": False,
        "is_machine": True,
        "is_unilateral": False,
        "description": "Seated leg curl machine — constant tension at peak contraction",
        "equipment": [
            {"slug": "leg_curl_machine", "role": "primary", "required": True},
        ],
    },
    {
        "slug": "good_morning",
        "name": "Good Morning",
        "primary_muscle": "hamstrings",
        "secondary_muscles": ["back", "glutes"],
        "equipment_bucket": "gym",
        "movement_pattern": "hinge",
        "exercise_type": "strength",
        "is_compound": True,
        "is_machine": False,
        "is_unilateral": False,
        "description": "Hip hinge with barbell on upper back — posterior chain",
        "equipment": [
            {"slug": "barbell", "role": "primary", "required": True},
        ],
    },
    {
        "slug": "nordic_curl",
        "name": "Nordic Curl",
        "primary_muscle": "hamstrings",
        "secondary_muscles": [],
        "equipment_bucket": "bodyweight",
        "movement_pattern": "isolation",
        "exercise_type": "strength",
        "is_compound": True,
        "is_machine": False,
        "is_unilateral": False,
        "description": "Advanced eccentric hamstring curl — injury prevention staple",
        "equipment": [],
    },
    {
        "slug": "single_leg_rdl",
        "name": "Single-leg Romanian Deadlift",
        "primary_muscle": "hamstrings",
        "secondary_muscles": ["glutes", "core"],
        "equipment_bucket": "dumbbells",
        "movement_pattern": "hinge",
        "exercise_type": "strength",
        "is_compound": True,
        "is_machine": False,
        "is_unilateral": True,
        "description": "Balance-demanding unilateral hinge for hamstrings",
        "equipment": [
            {"slug": "dumbbells", "role": "primary", "required": True},
        ],
    },
    {
        "slug": "smith_machine_rdl",
        "name": "Smith Machine Romanian Deadlift",
        "primary_muscle": "hamstrings",
        "secondary_muscles": ["glutes", "back"],
        "equipment_bucket": "gym",
        "movement_pattern": "hinge",
        "exercise_type": "strength",
        "is_compound": True,
        "is_machine": True,
        "is_unilateral": False,
        "description": "Guided RDL for beginners or heavy loading without balance demand",
        "equipment": [
            {"slug": "smith_machine", "role": "primary", "required": True},
        ],
    },
]

# ─── Glutes ──────────────────────────────────────────────────────────────────

GLUTES = [
    {
        "slug": "hip_thrust",
        "name": "Hip Thrust",
        "primary_muscle": "glutes",
        "secondary_muscles": ["hamstrings"],
        "equipment_bucket": "gym",
        "movement_pattern": "hinge",
        "exercise_type": "strength",
        "is_compound": True,
        "is_machine": False,
        "is_unilateral": False,
        "description": "Barbell hip thrust — most effective glute builder",
        "equipment": [
            {"slug": "barbell", "role": "primary", "required": True},
            {"slug": "flat_bench", "role": "support", "required": True},
        ],
    },
    {
        "slug": "glute_bridge",
        "name": "Glute Bridge",
        "primary_muscle": "glutes",
        "secondary_muscles": ["hamstrings"],
        "equipment_bucket": "bodyweight",
        "movement_pattern": "hinge",
        "exercise_type": "strength",
        "is_compound": True,
        "is_machine": False,
        "is_unilateral": False,
        "description": "Bodyweight hip extension on the floor",
        "equipment": [],
    },
    {
        "slug": "single_leg_glute_bridge",
        "name": "Single-leg Glute Bridge",
        "primary_muscle": "glutes",
        "secondary_muscles": ["hamstrings"],
        "equipment_bucket": "bodyweight",
        "movement_pattern": "hinge",
        "exercise_type": "strength",
        "is_compound": True,
        "is_machine": False,
        "is_unilateral": True,
        "description": "Unilateral glute bridge progression",
        "equipment": [],
    },
    {
        "slug": "cable_glute_kickback",
        "name": "Cable Glute Kickback",
        "primary_muscle": "glutes",
        "secondary_muscles": [],
        "equipment_bucket": "gym",
        "movement_pattern": "isolation",
        "exercise_type": "strength",
        "is_compound": False,
        "is_machine": False,
        "is_unilateral": True,
        "description": "Cable kickback for isolated glute contraction",
        "equipment": [
            {"slug": "cable_machine", "role": "primary", "required": True},
        ],
    },
    {
        "slug": "donkey_kicks",
        "name": "Donkey Kicks",
        "primary_muscle": "glutes",
        "secondary_muscles": [],
        "equipment_bucket": "bodyweight",
        "movement_pattern": "isolation",
        "exercise_type": "strength",
        "is_compound": False,
        "is_machine": False,
        "is_unilateral": True,
        "description": "Quadruped bodyweight glute isolation",
        "equipment": [],
    },
    {
        "slug": "fire_hydrants",
        "name": "Fire Hydrants",
        "primary_muscle": "glutes",
        "secondary_muscles": [],
        "equipment_bucket": "bodyweight",
        "movement_pattern": "isolation",
        "exercise_type": "strength",
        "is_compound": False,
        "is_machine": False,
        "is_unilateral": True,
        "description": "Quadruped glute medius and external rotation work",
        "equipment": [],
    },
    {
        "slug": "hip_abduction_machine",
        "name": "Hip Abduction Machine",
        "primary_muscle": "glutes",
        "secondary_muscles": [],
        "equipment_bucket": "gym",
        "movement_pattern": "isolation",
        "exercise_type": "strength",
        "is_compound": False,
        "is_machine": True,
        "is_unilateral": False,
        "description": "Seated machine for glute medius and abductor isolation",
        "equipment": [
            {"slug": "hip_abduction_machine", "role": "primary", "required": True},
        ],
    },
]

# ─── Adductors ───────────────────────────────────────────────────────────────

ADDUCTORS = [
    {
        "slug": "hip_adduction_machine",
        "name": "Hip Adduction Machine",
        "primary_muscle": "adductors",
        "secondary_muscles": [],
        "equipment_bucket": "gym",
        "movement_pattern": "isolation",
        "exercise_type": "strength",
        "is_compound": False,
        "is_machine": True,
        "is_unilateral": False,
        "description": "Seated machine for inner thigh and adductor isolation",
        "equipment": [
            {"slug": "hip_adduction_machine", "role": "primary", "required": True},
        ],
    },
    {
        "slug": "copenhagen_plank",
        "name": "Copenhagen Plank",
        "primary_muscle": "core",
        "secondary_muscles": ["adductors"],
        "equipment_bucket": "bodyweight",
        "movement_pattern": "anti_extension",
        "exercise_type": "strength",
        "is_compound": False,
        "is_machine": False,
        "is_unilateral": True,
        "description": "Side plank with top leg elevated — heavy adductor and core load",
        "equipment": [],
    },
    {
        "slug": "sumo_squat",
        "name": "Sumo Squat",
        "primary_muscle": "quads",
        "secondary_muscles": ["glutes", "adductors"],
        "equipment_bucket": "dumbbells",
        "movement_pattern": "squat",
        "exercise_type": "strength",
        "is_compound": True,
        "is_machine": False,
        "is_unilateral": False,
        "description": "Wide-stance squat with toes flared — inner thigh and glutes",
        "equipment": [
            {"slug": "dumbbells", "role": "primary", "required": False},
        ],
    },
]

# ─── Calves ──────────────────────────────────────────────────────────────────

CALVES = [
    {
        "slug": "standing_calf_raise",
        "name": "Standing Calf Raise",
        "primary_muscle": "calves",
        "secondary_muscles": [],
        "equipment_bucket": "gym",
        "movement_pattern": "isolation",
        "exercise_type": "strength",
        "is_compound": False,
        "is_machine": True,
        "is_unilateral": False,
        "description": "Bilateral calf raise on machine or loaded step",
        "equipment": [
            {"slug": "leverage_machines", "role": "primary", "required": True},
        ],
    },
    {
        "slug": "seated_calf_raise",
        "name": "Seated Calf Raise",
        "primary_muscle": "calves",
        "secondary_muscles": [],
        "equipment_bucket": "gym",
        "movement_pattern": "isolation",
        "exercise_type": "strength",
        "is_compound": False,
        "is_machine": True,
        "is_unilateral": False,
        "description": "Soleus focus with knee bent on seated calf machine",
        "equipment": [
            {"slug": "leverage_machines", "role": "primary", "required": True},
        ],
    },
    {
        "slug": "single_leg_calf_raise",
        "name": "Single-leg Calf Raise",
        "primary_muscle": "calves",
        "secondary_muscles": [],
        "equipment_bucket": "bodyweight",
        "movement_pattern": "isolation",
        "exercise_type": "strength",
        "is_compound": False,
        "is_machine": False,
        "is_unilateral": True,
        "description": "Bodyweight single-leg calf raise on a step",
        "equipment": [],
    },
    {
        "slug": "jump_rope_calf",
        "name": "Jump Rope (Calf Focus)",
        "primary_muscle": "calves",
        "secondary_muscles": ["cardio"],
        "equipment_bucket": "home",
        "movement_pattern": "cardio",
        "exercise_type": "cardio",
        "is_compound": False,
        "is_machine": False,
        "is_unilateral": False,
        "description": "Jump rope with emphasis on plantar flexion at bottom",
        "equipment": [
            {"slug": "jump_rope", "role": "primary", "required": True},
        ],
    },
    {
        "slug": "tibialis_raise",
        "name": "Tibialis Raise",
        "primary_muscle": "calves",
        "secondary_muscles": [],
        "equipment_bucket": "bodyweight",
        "movement_pattern": "isolation",
        "exercise_type": "strength",
        "is_compound": False,
        "is_machine": False,
        "is_unilateral": False,
        "description": "Stand against a wall and raise toes — strengthens tibialis anterior and shin",
        "equipment": [],
    },
    {
        "slug": "ankle_mobility_drill",
        "name": "Ankle Mobility Drill",
        "primary_muscle": "calves",
        "secondary_muscles": [],
        "equipment_bucket": "bodyweight",
        "movement_pattern": "mobility",
        "exercise_type": "mobility",
        "is_compound": False,
        "is_machine": False,
        "is_unilateral": False,
        "description": "Controlled ankle circles and wall ankle flexion for joint health",
        "equipment": [],
    },
]

# ─── Core ────────────────────────────────────────────────────────────────────

CORE = [
    {
        "slug": "plank",
        "name": "Plank",
        "primary_muscle": "core",
        "secondary_muscles": [],
        "equipment_bucket": "bodyweight",
        "movement_pattern": "anti_extension",
        "exercise_type": "strength",
        "is_compound": False,
        "is_machine": False,
        "is_unilateral": False,
        "description": "Isometric core stabilisation hold",
        "equipment": [],
    },
    {
        "slug": "side_plank",
        "name": "Side Plank",
        "primary_muscle": "core",
        "secondary_muscles": [],
        "equipment_bucket": "bodyweight",
        "movement_pattern": "anti_extension",
        "exercise_type": "strength",
        "is_compound": False,
        "is_machine": False,
        "is_unilateral": True,
        "description": "Oblique and anti-lateral flexion isometric work",
        "equipment": [],
    },
    {
        "slug": "dead_bug",
        "name": "Dead Bug",
        "primary_muscle": "core",
        "secondary_muscles": [],
        "equipment_bucket": "bodyweight",
        "movement_pattern": "anti_extension",
        "exercise_type": "strength",
        "is_compound": False,
        "is_machine": False,
        "is_unilateral": False,
        "description": "Beginner-friendly anti-extension core coordination move",
        "equipment": [],
    },
    {
        "slug": "bird_dog",
        "name": "Bird Dog",
        "primary_muscle": "core",
        "secondary_muscles": ["back"],
        "equipment_bucket": "bodyweight",
        "movement_pattern": "anti_extension",
        "exercise_type": "strength",
        "is_compound": False,
        "is_machine": False,
        "is_unilateral": True,
        "description": "Core stability and contralateral coordination drill",
        "equipment": [],
    },
    {
        "slug": "cable_crunch",
        "name": "Cable Crunch",
        "primary_muscle": "core",
        "secondary_muscles": [],
        "equipment_bucket": "gym",
        "movement_pattern": "isolation",
        "exercise_type": "strength",
        "is_compound": False,
        "is_machine": False,
        "is_unilateral": False,
        "description": "Weighted kneeling crunch using cable machine",
        "equipment": [
            {"slug": "cable_machine", "role": "primary", "required": True},
        ],
    },
    {
        "slug": "hanging_leg_raise",
        "name": "Hanging Leg Raise",
        "primary_muscle": "core",
        "secondary_muscles": [],
        "equipment_bucket": "home",
        "movement_pattern": "isolation",
        "exercise_type": "strength",
        "is_compound": False,
        "is_machine": False,
        "is_unilateral": False,
        "description": "Lower ab focus hanging from pull-up bar",
        "equipment": [
            {"slug": "pull_up_bar", "role": "primary", "required": True},
        ],
    },
    {
        "slug": "russian_twist",
        "name": "Russian Twist",
        "primary_muscle": "core",
        "secondary_muscles": [],
        "equipment_bucket": "bodyweight",
        "movement_pattern": "rotation",
        "exercise_type": "strength",
        "is_compound": False,
        "is_machine": False,
        "is_unilateral": False,
        "description": "Rotational core exercise with or without weight",
        "equipment": [],
    },
    {
        "slug": "ab_wheel_rollout",
        "name": "Ab Wheel Rollout",
        "primary_muscle": "core",
        "secondary_muscles": ["shoulders"],
        "equipment_bucket": "home",
        "movement_pattern": "anti_extension",
        "exercise_type": "strength",
        "is_compound": False,
        "is_machine": False,
        "is_unilateral": False,
        "description": "Challenging anti-extension core exercise with ab wheel",
        "equipment": [
            {"slug": "ab_wheel", "role": "primary", "required": True},
        ],
    },
    {
        "slug": "mountain_climbers",
        "name": "Mountain Climbers",
        "primary_muscle": "core",
        "secondary_muscles": ["cardio"],
        "equipment_bucket": "bodyweight",
        "movement_pattern": "anti_extension",
        "exercise_type": "cardio",
        "is_compound": True,
        "is_machine": False,
        "is_unilateral": False,
        "description": "Dynamic core and cardiovascular conditioning drill",
        "equipment": [],
    },
    {
        "slug": "cable_woodchop",
        "name": "Cable Woodchop",
        "primary_muscle": "core",
        "secondary_muscles": ["shoulders"],
        "equipment_bucket": "gym",
        "movement_pattern": "rotation",
        "exercise_type": "strength",
        "is_compound": True,
        "is_machine": False,
        "is_unilateral": False,
        "description": "Rotational cable pull for anti-rotation and oblique strength",
        "equipment": [
            {"slug": "cable_machine", "role": "primary", "required": True},
        ],
    },
    {
        "slug": "pallof_press",
        "name": "Pallof Press",
        "primary_muscle": "core",
        "secondary_muscles": [],
        "equipment_bucket": "gym",
        "movement_pattern": "anti_rotation",
        "exercise_type": "strength",
        "is_compound": False,
        "is_machine": False,
        "is_unilateral": False,
        "description": "Anti-rotation cable press — builds lateral core stability",
        "equipment": [
            {"slug": "cable_machine", "role": "primary", "required": True},
        ],
    },
]

# ─── Rotator Cuff / Shoulder Health ──────────────────────────────────────────

PREHAB = [
    {
        "slug": "external_rotation_band",
        "name": "External Rotation (Band)",
        "primary_muscle": "shoulders",
        "secondary_muscles": [],
        "equipment_bucket": "home",
        "movement_pattern": "isolation",
        "exercise_type": "mobility",
        "is_compound": False,
        "is_machine": False,
        "is_unilateral": True,
        "description": "Band external rotation for rotator cuff health",
        "equipment": [
            {"slug": "resistance_bands", "role": "primary", "required": True},
        ],
    },
    {
        "slug": "internal_rotation_band",
        "name": "Internal Rotation (Band)",
        "primary_muscle": "shoulders",
        "secondary_muscles": [],
        "equipment_bucket": "home",
        "movement_pattern": "isolation",
        "exercise_type": "mobility",
        "is_compound": False,
        "is_machine": False,
        "is_unilateral": True,
        "description": "Band internal rotation drill for shoulder balance",
        "equipment": [
            {"slug": "resistance_bands", "role": "primary", "required": True},
        ],
    },
    {
        "slug": "prone_ytw",
        "name": "Prone Y-T-W",
        "primary_muscle": "back",
        "secondary_muscles": ["shoulders"],
        "equipment_bucket": "bodyweight",
        "movement_pattern": "mobility",
        "exercise_type": "mobility",
        "is_compound": False,
        "is_machine": False,
        "is_unilateral": False,
        "description": "Prone scapular control drill — Y, T, and W positions",
        "equipment": [],
    },
    {
        "slug": "cuban_press",
        "name": "Cuban Press",
        "primary_muscle": "shoulders",
        "secondary_muscles": [],
        "equipment_bucket": "dumbbells",
        "movement_pattern": "isolation",
        "exercise_type": "mobility",
        "is_compound": False,
        "is_machine": False,
        "is_unilateral": False,
        "description": "External rotation to overhead press combo for shoulder prehab",
        "equipment": [
            {"slug": "dumbbells", "role": "primary", "required": True},
        ],
    },
]

# ─── Mobility / Warmup ──────────────────────────────────────────────────────

MOBILITY = [
    {
        "slug": "worlds_greatest_stretch",
        "name": "World's Greatest Stretch",
        "primary_muscle": "full_body",
        "secondary_muscles": [],
        "equipment_bucket": "bodyweight",
        "movement_pattern": "mobility",
        "exercise_type": "mobility",
        "is_compound": False,
        "is_machine": False,
        "is_unilateral": True,
        "description": "Lunge to thoracic rotation — total mobility warmup",
        "equipment": [],
    },
    {
        "slug": "hip_90_90_stretch",
        "name": "Hip 90-90 Stretch",
        "primary_muscle": "glutes",
        "secondary_muscles": ["hamstrings"],
        "equipment_bucket": "bodyweight",
        "movement_pattern": "mobility",
        "exercise_type": "mobility",
        "is_compound": False,
        "is_machine": False,
        "is_unilateral": True,
        "description": "Hip internal and external rotation mobility drill",
        "equipment": [],
    },
    {
        "slug": "leg_swings",
        "name": "Leg Swings",
        "primary_muscle": "hamstrings",
        "secondary_muscles": ["glutes"],
        "equipment_bucket": "bodyweight",
        "movement_pattern": "mobility",
        "exercise_type": "mobility",
        "is_compound": False,
        "is_machine": False,
        "is_unilateral": True,
        "description": "Dynamic hip flexor and hamstring warmup swing",
        "equipment": [],
    },
    {
        "slug": "arm_circles",
        "name": "Arm Circles",
        "primary_muscle": "shoulders",
        "secondary_muscles": [],
        "equipment_bucket": "bodyweight",
        "movement_pattern": "mobility",
        "exercise_type": "mobility",
        "is_compound": False,
        "is_machine": False,
        "is_unilateral": False,
        "description": "Dynamic shoulder warmup and mobility drill",
        "equipment": [],
    },
    {
        "slug": "cat_cow",
        "name": "Cat-Cow",
        "primary_muscle": "back",
        "secondary_muscles": ["core"],
        "equipment_bucket": "bodyweight",
        "movement_pattern": "mobility",
        "exercise_type": "mobility",
        "is_compound": False,
        "is_machine": False,
        "is_unilateral": False,
        "description": "Spinal flexion and extension mobility flow",
        "equipment": [],
    },
    {
        "slug": "inchworm",
        "name": "Inchworm",
        "primary_muscle": "full_body",
        "secondary_muscles": ["core", "shoulders"],
        "equipment_bucket": "bodyweight",
        "movement_pattern": "mobility",
        "exercise_type": "mobility",
        "is_compound": True,
        "is_machine": False,
        "is_unilateral": False,
        "description": "Walk-out warmup targeting hamstrings, core, and shoulders",
        "equipment": [],
    },
]

# ─── Cardio — machine ────────────────────────────────────────────────────────

CARDIO_MACHINE = [
    {
        "slug": "treadmill_run",
        "name": "Treadmill Run",
        "primary_muscle": "cardio",
        "secondary_muscles": [],
        "equipment_bucket": "cardio",
        "movement_pattern": "cardio",
        "exercise_type": "cardio",
        "is_compound": False,
        "is_machine": True,
        "is_unilateral": False,
        "description": "Steady-state or interval treadmill run",
        "equipment": [
            {"slug": "treadmill", "role": "primary", "required": True},
        ],
    },
    {
        "slug": "treadmill_intervals",
        "name": "Treadmill Intervals",
        "primary_muscle": "cardio",
        "secondary_muscles": [],
        "equipment_bucket": "cardio",
        "movement_pattern": "cardio",
        "exercise_type": "cardio",
        "is_compound": True,
        "is_machine": True,
        "is_unilateral": False,
        "description": "Alternating sprint and recovery on treadmill",
        "equipment": [
            {"slug": "treadmill", "role": "primary", "required": True},
        ],
    },
    {
        "slug": "incline_walk",
        "name": "Incline Walk",
        "primary_muscle": "cardio",
        "secondary_muscles": ["glutes", "calves"],
        "equipment_bucket": "cardio",
        "movement_pattern": "cardio",
        "exercise_type": "cardio",
        "is_compound": False,
        "is_machine": True,
        "is_unilateral": False,
        "description": "Low-impact incline treadmill walk for conditioning",
        "equipment": [
            {"slug": "treadmill", "role": "primary", "required": True},
        ],
    },
    {
        "slug": "stationary_bike",
        "name": "Stationary Bike",
        "primary_muscle": "cardio",
        "secondary_muscles": ["quads", "calves"],
        "equipment_bucket": "cardio",
        "movement_pattern": "cardio",
        "exercise_type": "cardio",
        "is_compound": False,
        "is_machine": True,
        "is_unilateral": False,
        "description": "Low-impact cycling cardio on stationary bike",
        "equipment": [
            {"slug": "stationary_bike", "role": "primary", "required": True},
        ],
    },
    {
        "slug": "stationary_bike_intervals",
        "name": "Stationary Bike Intervals",
        "primary_muscle": "cardio",
        "secondary_muscles": ["quads"],
        "equipment_bucket": "cardio",
        "movement_pattern": "cardio",
        "exercise_type": "cardio",
        "is_compound": True,
        "is_machine": True,
        "is_unilateral": False,
        "description": "High-intensity cycling sprints on stationary bike",
        "equipment": [
            {"slug": "stationary_bike", "role": "primary", "required": True},
        ],
    },
    {
        "slug": "assault_bike",
        "name": "Assault Bike",
        "primary_muscle": "cardio",
        "secondary_muscles": ["full_body"],
        "equipment_bucket": "cardio",
        "movement_pattern": "cardio",
        "exercise_type": "cardio",
        "is_compound": True,
        "is_machine": True,
        "is_unilateral": False,
        "description": "Fan bike — brutal full-body cardiovascular effort",
        "equipment": [
            {"slug": "assault_bike", "role": "primary", "required": True},
        ],
    },
    {
        "slug": "elliptical",
        "name": "Elliptical",
        "primary_muscle": "cardio",
        "secondary_muscles": [],
        "equipment_bucket": "cardio",
        "movement_pattern": "cardio",
        "exercise_type": "cardio",
        "is_compound": False,
        "is_machine": True,
        "is_unilateral": False,
        "description": "Joint-friendly low-impact cardio",
        "equipment": [
            {"slug": "elliptical", "role": "primary", "required": True},
        ],
    },
    {
        "slug": "stair_climber",
        "name": "Stair Climber",
        "primary_muscle": "cardio",
        "secondary_muscles": ["glutes", "quads"],
        "equipment_bucket": "cardio",
        "movement_pattern": "cardio",
        "exercise_type": "cardio",
        "is_compound": False,
        "is_machine": True,
        "is_unilateral": False,
        "description": "Lower-body-focused cardio stair climbing machine",
        "equipment": [
            {"slug": "stair_climber", "role": "primary", "required": True},
        ],
    },
    {
        "slug": "rowing_machine",
        "name": "Rowing Machine",
        "primary_muscle": "full_body",
        "secondary_muscles": ["back", "quads"],
        "equipment_bucket": "cardio",
        "movement_pattern": "cardio",
        "exercise_type": "cardio",
        "is_compound": True,
        "is_machine": True,
        "is_unilateral": False,
        "description": "Full-body cardio with strong back and leg activation",
        "equipment": [
            {"slug": "rowing_machine", "role": "primary", "required": True},
        ],
    },
    {
        "slug": "rowing_machine_intervals",
        "name": "Rowing Machine Intervals",
        "primary_muscle": "full_body",
        "secondary_muscles": ["back", "quads"],
        "equipment_bucket": "cardio",
        "movement_pattern": "cardio",
        "exercise_type": "cardio",
        "is_compound": True,
        "is_machine": True,
        "is_unilateral": False,
        "description": "High-intensity rowing sprints with recovery periods",
        "equipment": [
            {"slug": "rowing_machine", "role": "primary", "required": True},
        ],
    },
]

# ─── Cardio — outdoor / bodyweight ───────────────────────────────────────────

CARDIO_OUTDOOR = [
    {
        "slug": "running_outdoor",
        "name": "Running (Outdoor)",
        "primary_muscle": "cardio",
        "secondary_muscles": [],
        "equipment_bucket": "bodyweight",
        "movement_pattern": "cardio",
        "exercise_type": "cardio",
        "is_compound": False,
        "is_machine": False,
        "is_unilateral": False,
        "description": "Steady-state outdoor run",
        "equipment": [],
    },
    {
        "slug": "jogging",
        "name": "Jogging",
        "primary_muscle": "cardio",
        "secondary_muscles": [],
        "equipment_bucket": "bodyweight",
        "movement_pattern": "cardio",
        "exercise_type": "cardio",
        "is_compound": False,
        "is_machine": False,
        "is_unilateral": False,
        "description": "Easy-pace endurance jogging outdoors",
        "equipment": [],
    },
    {
        "slug": "sprint_intervals",
        "name": "Sprint Intervals",
        "primary_muscle": "cardio",
        "secondary_muscles": ["quads", "glutes"],
        "equipment_bucket": "bodyweight",
        "movement_pattern": "cardio",
        "exercise_type": "cardio",
        "is_compound": True,
        "is_machine": False,
        "is_unilateral": False,
        "description": "All-out sprints with walking recovery",
        "equipment": [],
    },
    {
        "slug": "hill_sprints",
        "name": "Hill Sprints",
        "primary_muscle": "cardio",
        "secondary_muscles": ["glutes", "calves"],
        "equipment_bucket": "bodyweight",
        "movement_pattern": "cardio",
        "exercise_type": "cardio",
        "is_compound": True,
        "is_machine": False,
        "is_unilateral": False,
        "description": "Uphill sprint repeats for power and conditioning",
        "equipment": [],
    },
    {
        "slug": "swimming_laps",
        "name": "Swimming Laps",
        "primary_muscle": "cardio",
        "secondary_muscles": ["back", "shoulders"],
        "equipment_bucket": "bodyweight",
        "movement_pattern": "cardio",
        "exercise_type": "cardio",
        "is_compound": True,
        "is_machine": False,
        "is_unilateral": False,
        "description": "Full-body low-impact cardio in pool",
        "equipment": [
            {"slug": "swimming_pool", "role": "primary", "required": True},
        ],
    },
    {
        "slug": "cycling_outdoor",
        "name": "Cycling (Outdoor)",
        "primary_muscle": "cardio",
        "secondary_muscles": ["quads", "calves"],
        "equipment_bucket": "bodyweight",
        "movement_pattern": "cardio",
        "exercise_type": "cardio",
        "is_compound": False,
        "is_machine": False,
        "is_unilateral": False,
        "description": "Steady outdoor bike ride",
        "equipment": [],
    },
    {
        "slug": "jump_rope",
        "name": "Jump Rope",
        "primary_muscle": "cardio",
        "secondary_muscles": ["calves"],
        "equipment_bucket": "home",
        "movement_pattern": "cardio",
        "exercise_type": "cardio",
        "is_compound": False,
        "is_machine": False,
        "is_unilateral": False,
        "description": "Jump rope cardiovascular conditioning",
        "equipment": [
            {"slug": "jump_rope", "role": "primary", "required": True},
        ],
    },
    {
        "slug": "jump_rope_hiit",
        "name": "Jump Rope HIIT",
        "primary_muscle": "cardio",
        "secondary_muscles": ["calves", "shoulders"],
        "equipment_bucket": "home",
        "movement_pattern": "cardio",
        "exercise_type": "cardio",
        "is_compound": True,
        "is_machine": False,
        "is_unilateral": False,
        "description": "High-intensity jump rope intervals",
        "equipment": [
            {"slug": "jump_rope", "role": "primary", "required": True},
        ],
    },
    {
        "slug": "hiit_circuit",
        "name": "HIIT Circuit",
        "primary_muscle": "full_body",
        "secondary_muscles": [],
        "equipment_bucket": "bodyweight",
        "movement_pattern": "cardio",
        "exercise_type": "cardio",
        "is_compound": True,
        "is_machine": False,
        "is_unilateral": False,
        "description": "High-intensity interval circuit — no equipment needed",
        "equipment": [],
    },
    {
        "slug": "battle_ropes",
        "name": "Battle Ropes",
        "primary_muscle": "full_body",
        "secondary_muscles": ["shoulders", "core"],
        "equipment_bucket": "gym",
        "movement_pattern": "cardio",
        "exercise_type": "cardio",
        "is_compound": True,
        "is_machine": False,
        "is_unilateral": False,
        "description": "Wave and slam conditioning with battle ropes",
        "equipment": [
            {"slug": "battle_ropes", "role": "primary", "required": True},
        ],
    },
]

# ─── Full body / power ───────────────────────────────────────────────────────

POWER = [
    {
        "slug": "kettlebell_swing",
        "name": "Kettlebell Swing",
        "primary_muscle": "full_body",
        "secondary_muscles": ["glutes", "hamstrings"],
        "equipment_bucket": "other",
        "movement_pattern": "hinge",
        "exercise_type": "strength",
        "is_compound": True,
        "is_machine": False,
        "is_unilateral": False,
        "description": "Hip-hinge power movement with kettlebell",
        "equipment": [
            {"slug": "kettlebell", "role": "primary", "required": True},
        ],
    },
    {
        "slug": "burpees",
        "name": "Burpees",
        "primary_muscle": "full_body",
        "secondary_muscles": [],
        "equipment_bucket": "bodyweight",
        "movement_pattern": "plyometric",
        "exercise_type": "cardio",
        "is_compound": True,
        "is_machine": False,
        "is_unilateral": False,
        "description": "High-intensity full body conditioning movement",
        "equipment": [],
    },
    {
        "slug": "box_jump",
        "name": "Box Jump",
        "primary_muscle": "quads",
        "secondary_muscles": ["glutes"],
        "equipment_bucket": "gym",
        "movement_pattern": "plyometric",
        "exercise_type": "strength",
        "is_compound": True,
        "is_machine": False,
        "is_unilateral": False,
        "description": "Plyometric lower body power onto a plyo box",
        "equipment": [
            {"slug": "plyo_box", "role": "primary", "required": True},
        ],
    },
    {
        "slug": "broad_jump",
        "name": "Broad Jump",
        "primary_muscle": "quads",
        "secondary_muscles": ["glutes"],
        "equipment_bucket": "bodyweight",
        "movement_pattern": "plyometric",
        "exercise_type": "strength",
        "is_compound": True,
        "is_machine": False,
        "is_unilateral": False,
        "description": "Horizontal plyometric power jump",
        "equipment": [],
    },
    {
        "slug": "jump_squats",
        "name": "Jump Squats",
        "primary_muscle": "quads",
        "secondary_muscles": ["glutes"],
        "equipment_bucket": "bodyweight",
        "movement_pattern": "plyometric",
        "exercise_type": "strength",
        "is_compound": True,
        "is_machine": False,
        "is_unilateral": False,
        "description": "Explosive squat with a jump at the top",
        "equipment": [],
    },
    {
        "slug": "thrusters",
        "name": "Thrusters",
        "primary_muscle": "full_body",
        "secondary_muscles": ["shoulders", "quads"],
        "equipment_bucket": "dumbbells",
        "movement_pattern": "squat",
        "exercise_type": "strength",
        "is_compound": True,
        "is_machine": False,
        "is_unilateral": False,
        "description": "Squat-to-press full body exercise with dumbbells",
        "equipment": [
            {"slug": "dumbbells", "role": "primary", "required": True},
        ],
    },
    {
        "slug": "farmer_carry",
        "name": "Farmer Carry",
        "primary_muscle": "full_body",
        "secondary_muscles": ["core", "forearms"],
        "equipment_bucket": "dumbbells",
        "movement_pattern": "carry",
        "exercise_type": "strength",
        "is_compound": True,
        "is_machine": False,
        "is_unilateral": False,
        "description": "Heavy loaded carry for full-body stability and grip",
        "equipment": [
            {"slug": "dumbbells", "role": "primary", "required": True},
        ],
    },
    {
        "slug": "sled_push",
        "name": "Sled Push",
        "primary_muscle": "full_body",
        "secondary_muscles": ["quads", "glutes"],
        "equipment_bucket": "other",
        "movement_pattern": "cardio",
        "exercise_type": "strength",
        "is_compound": True,
        "is_machine": False,
        "is_unilateral": False,
        "description": "Sled drive for power, conditioning, and leg strength",
        "equipment": [
            {"slug": "sled", "role": "primary", "required": True},
        ],
    },
    {
        "slug": "med_ball_slam",
        "name": "Med Ball Slam",
        "primary_muscle": "full_body",
        "secondary_muscles": ["core", "shoulders"],
        "equipment_bucket": "other",
        "movement_pattern": "plyometric",
        "exercise_type": "strength",
        "is_compound": True,
        "is_machine": False,
        "is_unilateral": False,
        "description": "Explosive overhead slam with a medicine ball",
        "equipment": [
            {"slug": "medicine_ball", "role": "primary", "required": True},
        ],
    },
    {
        "slug": "suitcase_carry",
        "name": "Suitcase Carry",
        "primary_muscle": "core",
        "secondary_muscles": ["glutes", "traps"],
        "equipment_bucket": "dumbbells",
        "movement_pattern": "carry",
        "exercise_type": "strength",
        "is_compound": True,
        "is_machine": False,
        "is_unilateral": True,
        "description": "Unilateral loaded carry for anti-lateral flexion core strength",
        "equipment": [
            {"slug": "dumbbells", "role": "primary", "required": True},
        ],
    },
    {
        "slug": "sled_drag",
        "name": "Sled Drag",
        "primary_muscle": "full_body",
        "secondary_muscles": ["hamstrings", "glutes"],
        "equipment_bucket": "other",
        "movement_pattern": "cardio",
        "exercise_type": "strength",
        "is_compound": True,
        "is_machine": False,
        "is_unilateral": False,
        "description": "Backward sled drag for posterior chain conditioning",
        "equipment": [
            {"slug": "sled", "role": "primary", "required": True},
        ],
    },
    {
        "slug": "trap_bar_deadlift",
        "name": "Trap Bar Deadlift",
        "primary_muscle": "full_body",
        "secondary_muscles": ["quads", "glutes", "back"],
        "equipment_bucket": "gym",
        "movement_pattern": "hinge",
        "exercise_type": "strength",
        "is_compound": True,
        "is_machine": False,
        "is_unilateral": False,
        "description": "Deadlift with trap bar — more upright torso, beginner-friendly",
        "equipment": [
            {"slug": "trap_bar", "role": "primary", "required": True},
        ],
    },
]


# ─── Equipment seed data with slugs ─────────────────────────────────────────

SEED_EQUIPMENT = [
    # Bodyweight & Home
    {"slug": "pull_up_bar",        "name": "Pull-up bar",              "category": "Bodyweight & Home", "icon": "\U0001f529"},
    {"slug": "resistance_bands",   "name": "Resistance bands",         "category": "Bodyweight & Home", "icon": "\U0001f517"},
    {"slug": "yoga_mat",           "name": "Yoga mat",                 "category": "Bodyweight & Home", "icon": "\U0001f9d8"},
    {"slug": "jump_rope",          "name": "Jump rope",                "category": "Bodyweight & Home", "icon": "\u26a1"},
    {"slug": "foam_roller",        "name": "Foam roller",              "category": "Bodyweight & Home", "icon": "\U0001f6e2\ufe0f"},
    {"slug": "ab_wheel",           "name": "Ab wheel",                 "category": "Bodyweight & Home", "icon": "\u2b55"},
    {"slug": "dip_bars",           "name": "Dip bars",                 "category": "Bodyweight & Home", "icon": "\U0001f938"},
    {"slug": "suspension_trainer", "name": "Suspension trainer",       "category": "Bodyweight & Home", "icon": "\U0001faa2"},

    # Free Weights
    {"slug": "dumbbells",          "name": "Dumbbells",                "category": "Free Weights", "icon": "\U0001f3cb\ufe0f"},
    {"slug": "barbell",            "name": "Barbell",                  "category": "Free Weights", "icon": "\U0001f3cb\ufe0f"},
    {"slug": "kettlebell",         "name": "Kettlebell",               "category": "Free Weights", "icon": "\U0001f514"},
    {"slug": "ez_curl_bar",        "name": "EZ curl bar",              "category": "Free Weights", "icon": "\u3030\ufe0f"},
    {"slug": "weight_plates",      "name": "Weight plates",            "category": "Free Weights", "icon": "\u2b55"},
    {"slug": "trap_bar",           "name": "Trap bar",                 "category": "Free Weights", "icon": "\u2b21"},
    {"slug": "medicine_ball",      "name": "Medicine ball",            "category": "Free Weights", "icon": "\u26bd"},

    # Benches & Racks
    {"slug": "flat_bench",         "name": "Flat bench",               "category": "Benches & Racks", "icon": "\U0001fa91"},
    {"slug": "adjustable_bench",   "name": "Adjustable bench",         "category": "Benches & Racks", "icon": "\U0001f4d0"},
    {"slug": "incline_bench",      "name": "Incline bench",            "category": "Benches & Racks", "icon": "\U0001f4d0"},
    {"slug": "squat_rack",         "name": "Squat rack",               "category": "Benches & Racks", "icon": "\U0001f3d7\ufe0f"},
    {"slug": "power_rack",         "name": "Power rack",               "category": "Benches & Racks", "icon": "\U0001f3d7\ufe0f"},
    {"slug": "landmine_attachment","name": "Landmine attachment",       "category": "Benches & Racks", "icon": "\U0001f527"},

    # Gym Machines
    {"slug": "cable_machine",          "name": "Cable machine",            "category": "Gym Machines", "icon": "\U0001f517"},
    {"slug": "leg_press_machine",      "name": "Leg press",                "category": "Gym Machines", "icon": "\U0001f9b5"},
    {"slug": "lat_pulldown_machine",   "name": "Lat pulldown",             "category": "Gym Machines", "icon": "\u2b07\ufe0f"},
    {"slug": "chest_press_machine",    "name": "Chest press machine",      "category": "Gym Machines", "icon": "\U0001f4aa"},
    {"slug": "seated_row_machine",     "name": "Seated row machine",       "category": "Gym Machines", "icon": "\U0001f519"},
    {"slug": "leg_extension_machine",  "name": "Leg extension",            "category": "Gym Machines", "icon": "\U0001f9b5"},
    {"slug": "leg_curl_machine",       "name": "Leg curl machine",         "category": "Gym Machines", "icon": "\U0001f9b5"},
    {"slug": "shoulder_press_machine", "name": "Shoulder press machine",   "category": "Gym Machines", "icon": "\u2b06\ufe0f"},
    {"slug": "hip_abduction_machine",  "name": "Hip abduction machine",    "category": "Gym Machines", "icon": "\U0001f9b5"},
    {"slug": "hip_adduction_machine",  "name": "Hip adduction machine",    "category": "Gym Machines", "icon": "\U0001f9b5"},
    {"slug": "smith_machine",          "name": "Smith machine",            "category": "Gym Machines", "icon": "\U0001f4cd"},
    {"slug": "hack_squat_machine",     "name": "Hack squat machine",       "category": "Gym Machines", "icon": "\U0001f9b5"},
    {"slug": "assisted_pullup_machine","name": "Assisted pull-up machine", "category": "Gym Machines", "icon": "\U0001f91d"},
    {"slug": "leverage_machines",      "name": "Leverage machines",        "category": "Gym Machines", "icon": "\u2699\ufe0f"},

    # Cardio
    {"slug": "treadmill",          "name": "Treadmill",                "category": "Cardio", "icon": "\U0001f3c3"},
    {"slug": "stationary_bike",    "name": "Stationary bike",          "category": "Cardio", "icon": "\U0001f6b4"},
    {"slug": "elliptical",         "name": "Elliptical",               "category": "Cardio", "icon": "\U0001f504"},
    {"slug": "rowing_machine",     "name": "Rowing machine",           "category": "Cardio", "icon": "\U0001f6a3"},
    {"slug": "stair_climber",      "name": "Stair climber",            "category": "Cardio", "icon": "\U0001fa9c"},
    {"slug": "assault_bike",       "name": "Assault bike",             "category": "Cardio", "icon": "\U0001f4a8"},
    {"slug": "swimming_pool",      "name": "Swimming pool",            "category": "Cardio", "icon": "\U0001f3ca"},
    {"slug": "battle_ropes",       "name": "Battle ropes",             "category": "Cardio", "icon": "\U0001faa2"},

    # Athletic / Functional
    {"slug": "plyo_box",           "name": "Plyo box",                 "category": "Athletic / Functional", "icon": "\U0001f4e6"},
    {"slug": "sled",               "name": "Sled",                     "category": "Athletic / Functional", "icon": "\U0001f6f7"},
]


# ─── Master list ─────────────────────────────────────────────────────────────

SEED_EXERCISES: list[dict] = (
    CHEST
    + BACK
    + SHOULDERS
    + BICEPS
    + TRICEPS
    + QUADS
    + HAMSTRINGS
    + GLUTES
    + ADDUCTORS
    + CALVES
    + CORE
    + PREHAB
    + MOBILITY
    + CARDIO_MACHINE
    + CARDIO_OUTDOOR
    + POWER
)
