"""Pure-function Switch Day pin/rotation logic.

Extracted from `routers/workouts.py::generate_full_week` so the rotation
rules can be unit-tested without DB, auth, or HTTP. The router still
owns IO (regen with forced split, generate cardio finisher) and passes
callbacks for those side-effecting steps; everything else lives here.

Five outcomes for a pin:
  - `noop`        — target day already matches the requested focus.
  - `rotate`      — target is a lift slot; circularly rotate the
                    lifting sub-sequence by minimum distance so the
                    requested focus lands at target_idx.
  - `swap`        — target is a non-lifting slot (rest/cardio/recovery)
                    and a matching lift exists; swap the two slots.
  - `regen`       — focus isn't in the current split; needs a fresh
                    plan with `preferred_split` forced. Returns a
                    PinDecision with `regen_split` set; caller runs
                    the regen and applies the result.
  - `replace_day` — target should become a fresh recovery / mobility /
                    cardio day generated by the planner. Returns the
                    target index + the day type; caller generates and
                    assigns.
"""
from __future__ import annotations

from dataclasses import dataclass, field
from typing import Literal, Optional


PinAction = Literal["noop", "rotate", "swap", "bro_canonical_swap", "regen", "replace_day", "label_only"]
DayKind = Literal["recovery", "mobility", "cardio"]

NON_LIFTING_FOCUSES: frozenset[str] = frozenset({
    "mobility", "recovery", "active recovery", "stretching",
    "cardio", "conditioning", "mobility_flow", "recovery_easy",
})

# Map a fine focus name → the split that natively contains it.
# Used when the user pins a day to a focus that isn't in the current
# split (e.g. "Push" on a U/L plan); the caller regenerates with
# preferred_split forced to the mapped split, then lifts the matching
# day's exercises into the target slot.
SPLIT_FOR_FOCUS: dict[str, str] = {
    "push": "ppl",
    "pull": "ppl",
    "legs": "ppl",
    "upper": "upper_lower",
    "lower": "upper_lower",
    "full body": "full_body",
    "full_body": "full_body",
    "chest": "bro",
    "back": "bro",
    "shoulders": "bro",
    "arms": "bro",
}


# Canonical cycles per split. The pinning algorithm picks a starting
# offset of the cycle that places the requested focus at the requested
# position, then rebuilds the lift sequence from there. This preserves
# the split's intended ordering across successive pins (a series of
# single-day swaps would scramble the cycle — see the user-reported
# back-to-back-Legs / split-broken bugs).
BRO_CYCLE = ["chest", "back", "shoulders", "arms", "legs"]
PPL_CYCLE = ["push", "pull", "legs"]
UL_CYCLE = ["upper", "lower"]
LOWER_FOCUSED_CYCLE = ["lower", "upper"]
UPPER_FOCUSED_CYCLE = ["upper", "lower"]


def _canonical_cycle_for_split(preferred_split: Optional[str]) -> Optional[list[str]]:
    """The canonical cycle for a given split id. Returns None for
    splits that don't have a cycle (full_body, ppl_upper_lower, or
    when no split is set)."""
    if not preferred_split:
        return None
    s = preferred_split.lower().strip()
    if s == "ppl":
        return PPL_CYCLE
    if s == "upper_lower":
        return UL_CYCLE
    if s == "bro":
        return BRO_CYCLE
    if s == "lower_focused":
        return LOWER_FOCUSED_CYCLE
    if s == "upper_focused":
        return UPPER_FOCUSED_CYCLE
    return None


def _canonical_pin_rotation(
    lift_days: list[dict],
    target_lift_idx: int,
    base_focus: str,
    cycle: list[str],
) -> Optional[list[dict]]:
    """Compute a lift sequence that's a contiguous slice of `cycle`
    placed so the requested focus lands at `target_lift_idx`.

    Generalized version of the bro-specific algorithm. Works for PPL
    (cycle=push/pull/legs), U/L, bro, lower/upper-focused. Reuses
    existing exercise content from `lift_days` keyed by focus family
    (so we don't lose the user's logged data or the planner's
    exercise selections).

    Returns None if the requested focus isn't in this split's cycle —
    caller falls through to the regen path.
    """
    if base_focus not in cycle:
        return None
    cycle_idx = cycle.index(base_focus)
    n = len(lift_days)

    # Group existing lift_days by their family. Same focus map regardless
    # of variant ("Push", "Push (Heavy)", "Push + Cardio" all map to
    # "push" family).
    def _family(focus_str: str) -> str:
        f = normalize_focus(focus_str).replace(" + cardio", "").strip()
        if " — " in f:
            f = f.split(" — ")[0].strip()
        # Bro-specific synonyms.
        if "chest" in f: return "chest"
        if "back" in f: return "back"
        if "shoulders" in f or "shoulder" in f: return "shoulders"
        if "arms" in f or "arm" in f: return "arms"
        # PPL/UL/focused.
        if "legs" in f: return "legs"
        if "push" in f: return "push"
        if "pull" in f: return "pull"
        if "upper" in f: return "upper"
        if "lower" in f: return "lower"
        return f

    by_family: dict[str, list[dict]] = {}
    for d in lift_days:
        fam = _family(d.get("focus") or "")
        by_family.setdefault(fam, []).append(d)

    if not by_family:
        return None

    # Bro caps at 5 unique lifts (the recipe path enforces this in
    # weekly_recipe.py). If the caller passes more lift slots than the
    # cycle length, the canonical walk would wrap and produce duplicate
    # focuses (e.g. [Back, Shoulders, Arms, Legs, Chest, Back, ...]).
    # That violates the bro split's "max recovery per muscle" intent.
    # Cap output at len(cycle) and mark overflow positions with a
    # sentinel — `apply_rotate` swaps these for recovery day stubs.
    is_bro = cycle is BRO_CYCLE
    overflow_cap = len(cycle) if is_bro else n

    new_lift_days: list[dict] = []
    used: dict[str, int] = {f: 0 for f in cycle}
    for i in range(n):
        if i >= overflow_cap:
            # Past the bro cap — slot becomes a recovery day stub.
            new_lift_days.append({"_overflow_recovery": True})
            continue
        canon_pos = (cycle_idx + (i - target_lift_idx)) % len(cycle)
        wanted = cycle[canon_pos]
        pool = by_family.get(wanted, [])
        if used.get(wanted, 0) < len(pool):
            new_lift_days.append(pool[used[wanted]])
            used[wanted] = used.get(wanted, 0) + 1
        elif pool:
            new_lift_days.append(pool[0])
        else:
            # This family isn't in the original recipe at all. For bro
            # 6d this shouldn't happen (every cycle focus appears at
            # least once). For PPL where the recipe might have been
            # imbalanced (e.g. only Push + Pull, no Legs), bail and
            # let caller fall back to swap.
            return None
    return new_lift_days


def _bro_canonical_pin(
    lift_days: list[dict],
    target_lift_idx: int,
    focus_name: str,
) -> list[dict] | None:
    """Compute a bro lift sequence where the requested focus lands at
    target_lift_idx and the full sequence is a valid contiguous slice
    of the canonical Chest→Back→Shoulders→Arms→Legs cycle.

    Returns the new lift_days list, or None if the requested focus
    isn't a canonical bro focus (caller falls through).

    Why bro needs this special case: bro 6d/7d recipes have a focus
    repeat (Chest appears twice in [Chest, Back, Shoulders, Arms,
    Legs, Chest]). Rotating the array shifts content but breaks the
    cycle — produces e.g. [Chest, Chest, Back, ...] with back-to-back
    duplicates. Building the new sequence from the canonical cycle
    instead preserves the cycle's spacing and re-uses existing day
    content (exercises) by focus name.
    """
    focus_lo = focus_name.lower().strip().replace(" + cardio", "").strip()
    if focus_lo not in BRO_CYCLE:
        return None
    canonical_idx = BRO_CYCLE.index(focus_lo)
    n = len(lift_days)

    # Group existing lift_days by focus so we can reuse exercise
    # content. Each focus may have 1 or 2 days (bro 6d has 2 chest).
    by_focus: dict[str, list[dict]] = {}
    for d in lift_days:
        df = normalize_focus(d.get("focus") or "").replace(" + cardio", "").strip()
        if df in BRO_CYCLE:
            by_focus.setdefault(df, []).append(d)

    if not by_focus:
        return None

    new_lift_days: list[dict] = []
    used: dict[str, int] = {f: 0 for f in BRO_CYCLE}
    for i in range(n):
        # Output position i corresponds to canonical position offset
        # from canonical_idx by (i - target_lift_idx).
        canon_pos = (canonical_idx + (i - target_lift_idx)) % 5
        wanted = BRO_CYCLE[canon_pos]
        pool = by_focus.get(wanted, [])
        if used[wanted] < len(pool):
            new_lift_days.append(pool[used[wanted]])
            used[wanted] += 1
        elif pool:
            # Need a duplicate of this focus but original recipe had
            # only one — reuse the first. Acceptable for bro since
            # the user is reorganizing, not generating new content.
            new_lift_days.append(pool[0])
        else:
            # This canonical focus isn't in the original recipe at
            # all — shouldn't happen for canonical bro recipes since
            # every focus appears at least once at n_lifts >= 5.
            return None
    return new_lift_days


@dataclass
class PinDecision:
    """The pin algorithm's output. Caller mutates `days` accordingly."""
    action: PinAction
    target_idx: int
    # rotate: shift the lifting sub-sequence by this many positions.
    # swap: swap days[target_idx] with days[swap_with_idx].
    # noop: nothing to do.
    src_lift_idx: Optional[int] = None
    dst_lift_idx: Optional[int] = None
    swap_with_idx: Optional[int] = None
    rotation_shift: Optional[int] = None
    rotated_lift_days: list[dict] = field(default_factory=list)
    # regen: caller must regen a plan with this preferred_split, then
    # find a day whose focus matches `regen_match_focus` (or the
    # already-with-cardio variant) and put it at target_idx.
    regen_split: Optional[str] = None
    regen_match_focus: Optional[str] = None
    # replace_day: caller generates a recovery/mobility/cardio day
    # and assigns it to days[target_idx].
    day_kind: Optional[DayKind] = None
    # Whether the requested focus came in with a cardio finisher
    # suffix (" + Cardio"). After the primary action, caller may need
    # to append a cardio finisher exercise to the target day.
    wants_cardio_finisher: bool = False
    base_focus: str = ""
    full_focus: str = ""


def normalize_focus(focus: str) -> str:
    return (focus or "").lower().strip()


def split_lifting_focus(focus: str) -> tuple[str, bool]:
    """Return (base_focus_lowercased, wants_cardio_finisher).

    "Push + Cardio" → ("push", True). "Push" → ("push", False).
    """
    lo = normalize_focus(focus)
    if " + cardio" in lo:
        return lo.replace(" + cardio", "").strip(), True
    return lo, False


def _classify_target(focus: str) -> Optional[DayKind]:
    """Special-case targets that map straight to a fresh planner day."""
    lo = normalize_focus(focus)
    if lo in ("recovery", "active recovery"):
        return "recovery"
    if lo in ("mobility", "stretching"):
        return "mobility"
    if lo == "cardio":
        return "cardio"
    return None


def _focus_family(focus: str) -> str:
    """Coarse family for adjacency checking. Strips '+ Cardio' suffix
    and the '— Variant' trailer so 'Push (Heavy)', 'Push', and
    'Push + Cardio' all map to 'push'.

    Bro split: chest/shoulders → 'push', back → 'pull', arms → 'upper',
    legs → 'legs'. Mirrors archetype_to_focus_family in the planner so
    adjacency checks here agree with the rest of the system."""
    f = normalize_focus(focus).replace(" + cardio", "").strip()
    if " — " in f:
        f = f.split(" — ")[0].strip()
    if "legs" in f or "leg " in f:
        return "legs"
    if "chest" in f:
        return "push"
    if "back" in f:
        return "pull"
    if "shoulders" in f or "shoulder" in f:
        return "push"
    if "arms" in f or "arm" in f:
        return "upper"
    if "push" in f:
        return "push"
    if "pull" in f:
        return "pull"
    if "upper" in f:
        return "upper"
    if "lower" in f:
        return "lower"
    if "full body" in f or "full_body" in f:
        return "full_body"
    return f or "?"


def _swap_creates_adjacency(
    days: list[dict],
    target_idx: int,
    src_orig_idx: int,
) -> bool:
    """True if swapping days[target_idx] and days[src_orig_idx] would
    create same-family adjacency at EITHER end (around target or src).
    Adjacency is checked against the actual neighbors in the days list,
    skipping non-lifting days (rest doesn't break adjacency rules)."""
    if target_idx == src_orig_idx:
        return False
    n = len(days)
    # After swap: days[target_idx] holds old days[src_orig_idx];
    # days[src_orig_idx] holds old days[target_idx].
    new_at_target = days[src_orig_idx]
    new_at_src = days[target_idx]
    new_target_fam = _focus_family(new_at_target.get("focus") or "")
    new_src_fam = _focus_family(new_at_src.get("focus") or "")

    def _neighbor_fam(idx: int, direction: int) -> Optional[str]:
        """Walk in direction (-1 or +1) from idx, skip non-lifting days
        AND the OTHER swap position, return the first lift family found."""
        i = idx + direction
        while 0 <= i < n:
            if i == target_idx or i == src_orig_idx:
                i += direction
                continue
            f = normalize_focus(days[i].get("focus") or "")
            if f in NON_LIFTING_FOCUSES:
                i += direction
                continue
            return _focus_family(days[i].get("focus") or "")
        return None

    # Check target's neighbors against new content at target.
    if new_target_fam != "?":
        for direction in (-1, 1):
            nf = _neighbor_fam(target_idx, direction)
            if nf is not None and nf == new_target_fam:
                return True
    # Check src's neighbors against new content at src.
    if new_src_fam != "?":
        for direction in (-1, 1):
            nf = _neighbor_fam(src_orig_idx, direction)
            if nf is not None and nf == new_src_fam:
                return True
    return False


def _pick_closest(
    matches: list[int],
    *,
    dst_lift_idx: Optional[int],
    target_idx: int,
    lift_positions: list[int],
    days: Optional[list[dict]] = None,
) -> Optional[int]:
    """Pick the match closest to the target. For lifting targets, distance
    is in the lift-day sequence (minimizes rotation). For non-lifting
    targets, distance is in the full day-of-week sequence (minimizes
    swap displacement).

    When `days` is provided, candidates are SORTED by distance, then we
    pick the first one whose swap doesn't create same-family adjacency
    at either end. Falls back to the unconditional closest if every
    candidate creates adjacency (rare). Without `days`, behaves as the
    pure-distance selector for backwards compat."""
    if not matches:
        return None
    if dst_lift_idx is not None:
        sorted_matches = sorted(matches, key=lambda li: abs(li - dst_lift_idx))
    else:
        sorted_matches = sorted(matches, key=lambda li: abs(lift_positions[li] - target_idx))
    if days is None:
        return sorted_matches[0]
    # Adjacency-aware: walk candidates from closest outward, return the
    # first that doesn't create adjacency. Falls through to closest if
    # all of them do.
    for li in sorted_matches:
        src_orig = lift_positions[li]
        if not _swap_creates_adjacency(days, target_idx, src_orig):
            return li
    return sorted_matches[0]


def _rebuild_clobbers_existing_pins(
    lift_positions: list[int],
    new_lift_days: list[dict],
    new_pin_target_idx: int,
    existing_pins: dict[int, str],
) -> bool:
    """True if the canonical rebuild would change any prior-pinned day
    to a different focus base. The new pin's own target is excluded
    (it's allowed to overwrite its own previous pin)."""
    for pin_pos, pinned_focus in existing_pins.items():
        if pin_pos == new_pin_target_idx:
            continue
        if pin_pos not in lift_positions:
            continue
        li = lift_positions.index(pin_pos)
        new_focus = normalize_focus(new_lift_days[li].get("focus") or "")
        new_base = new_focus.replace(" + cardio", "").strip()
        if " — " in new_base:
            new_base = new_base.split(" — ")[0].strip()
        pinned_base = (pinned_focus or "").lower().strip().replace(" + cardio", "").strip()
        if new_base != pinned_base:
            return True
    return False


def decide_pin(
    days: list[dict],
    *,
    pin_day_index: int,
    pin_focus: str,
    preferred_split: Optional[str] = None,
    existing_pins: Optional[dict[int, str]] = None,
    prefer_swap: bool = False,
) -> PinDecision:
    """Compute the action needed to honor a Switch Day pin. Pure — no
    side effects. Returns a PinDecision the caller applies.

    `existing_pins`: optional {position: focus_base} map of days the
    user has already pinned in earlier interactions. When provided:
      - The canonical-rebuild path checks whether the rebuild would
        change any pinned position to a different focus base; if so,
        it falls back to single-day swap so prior pins are preserved
        (cycle purity sacrificed in favor of honoring user intent).
      - Single-day swap excludes prior-pinned positions from the
        candidate swap-partner pool.
    Without this param, behavior matches pre-fix (cumulative pins lose
    earlier pins to canonical-cycle rebuilds).

    `prefer_swap`: when True, prefer a minimal single-day swap over a
    canonical-cycle rebuild. Used when the caller is operating on the
    user's existing plan (current_days) — the user expects only the
    pinned day to change, not the entire week to reshuffle."""
    pins = existing_pins or {}
    target_idx = max(0, min(len(days) - 1, int(pin_day_index)))
    full_focus = normalize_focus(pin_focus)
    base_focus, wants_cardio_finisher = split_lifting_focus(pin_focus)

    # Recovery / Mobility / Cardio → caller generates a fresh day.
    day_kind = _classify_target(pin_focus)
    if day_kind is not None:
        return PinDecision(
            action="replace_day",
            target_idx=target_idx,
            day_kind=day_kind,
            wants_cardio_finisher=False,
            base_focus=base_focus,
            full_focus=full_focus,
        )

    lift_positions: list[int] = []
    lift_days: list[dict] = []
    for idx, d in enumerate(days):
        if normalize_focus(d.get("focus") or "") not in NON_LIFTING_FOCUSES:
            lift_positions.append(idx)
            lift_days.append(d)

    dst_lift_idx = (
        lift_positions.index(target_idx)
        if target_idx in lift_positions else None
    )

    # Build candidate pool. Each candidate is tagged with whether it's
    # an EXACT focus match or a BASE-focus match (relaxed: ignores
    # "+ Cardio" suffix / variant trailers). We then rank candidates
    # so the picker prefers in this order:
    #   1. Doesn't create same-family adjacency (the user-reported
    #      back-to-back-Legs bug was the absence of this check)
    #   2. Exact focus match over base match
    #   3. Closest distance to target
    #
    # Without combining the two pools, an exact-match-with-adjacency
    # would be picked even when a base-match-without-adjacency exists
    # (e.g. pin "Push + Cardio" → only one Push+Cardio at day 2 creates
    # adjacency; a plain "Push" at day 3 doesn't and is the better swap).
    def _base_of(focus_str: str) -> str:
        f = normalize_focus(focus_str).replace(" + cardio", "").strip()
        if " — " in f:
            f = f.split(" — ")[0].strip()
        return f

    exact_set = {
        li for li, ld in enumerate(lift_days)
        if normalize_focus(ld.get("focus") or "") == full_focus
    }
    base_set = {
        li for li, ld in enumerate(lift_days)
        if _base_of(ld.get("focus") or "") == base_focus
    }
    candidates = sorted(exact_set | base_set)

    # Exclude prior-pinned positions from the swap-candidate pool so a
    # swap can't clobber an earlier pin. The new pin's own target is
    # always allowed (it's overwriting its own previous pin).
    if pins:
        candidates = [
            li for li in candidates
            if lift_positions[li] not in pins or lift_positions[li] == target_idx
        ]

    def _rank(li: int) -> tuple:
        src_orig = lift_positions[li]
        creates_adj = _swap_creates_adjacency(days, target_idx, src_orig) if dst_lift_idx is not None or True else False
        is_exact = li in exact_set
        if dst_lift_idx is not None:
            distance = abs(li - dst_lift_idx)
        else:
            distance = abs(lift_positions[li] - target_idx)
        # Lower is better. Tuple ordering: adjacency-free first, then
        # exact match, then proximity.
        return (1 if creates_adj else 0, 0 if is_exact else 1, distance)

    src_lift_idx = min(candidates, key=_rank) if candidates else None

    common = dict(
        target_idx=target_idx,
        wants_cardio_finisher=wants_cardio_finisher,
        base_focus=base_focus,
        full_focus=full_focus,
    )

    # Minimal swap: when operating on the user's existing plan, prefer
    # swapping just the pinned day with the closest matching focus.
    # This preserves the rest of the week exactly as the user had it.
    if prefer_swap and src_lift_idx is not None and dst_lift_idx is not None:
        if src_lift_idx == dst_lift_idx:
            return PinDecision(
                action="noop",
                src_lift_idx=src_lift_idx,
                dst_lift_idx=dst_lift_idx,
                **common,
            )
        return PinDecision(
            action="swap",
            src_lift_idx=src_lift_idx,
            dst_lift_idx=dst_lift_idx,
            swap_with_idx=lift_positions[src_lift_idx],
            **common,
        )

    # Canonical-cycle rebuild for splits with a stable cycle (PPL, U/L,
    # Bro, lower/upper-focused). Falls back to single-day swap when the
    # split has no canonical cycle (full_body, ppl_ul) or when the focus
    # isn't in the cycle.
    cycle = _canonical_cycle_for_split(preferred_split)
    if cycle is not None and base_focus in cycle and dst_lift_idx is not None:
        # If target already matches AND no other change is needed,
        # report noop. Compute what canonical would produce and check.
        if src_lift_idx == dst_lift_idx:
            return PinDecision(
                action="noop",
                src_lift_idx=src_lift_idx,
                dst_lift_idx=dst_lift_idx,
                **common,
            )
        new_lift_days = _canonical_pin_rotation(
            lift_days, dst_lift_idx, base_focus, cycle,
        )
        if new_lift_days is not None:
            # If canonical rebuild would clobber a prior user pin, fall
            # through to single-day swap so both pins are honored. The
            # cycle ends up "broken" (cumulative pins can produce a
            # valid week that isn't a contiguous cycle slice) — that's
            # the explicit tradeoff. The next FULL regen restores the
            # canonical cycle from scratch.
            if not _rebuild_clobbers_existing_pins(
                lift_positions, new_lift_days, target_idx, pins
            ):
                return PinDecision(
                    action="rotate",
                    src_lift_idx=src_lift_idx,
                    dst_lift_idx=dst_lift_idx,
                    rotation_shift=0,  # not used for canonical rebuild
                    rotated_lift_days=new_lift_days,
                    **common,
                )

    # Fallback: single-day swap when there's no canonical cycle, or
    # when the canonical rebuild would clobber a prior user pin. Used
    # for full_body / ppl_upper_lower / unknown splits + prior-pin
    # conflict cases.
    if src_lift_idx is not None and dst_lift_idx is not None:
        if src_lift_idx == dst_lift_idx:
            return PinDecision(
                action="noop",
                src_lift_idx=src_lift_idx,
                dst_lift_idx=dst_lift_idx,
                **common,
            )
        return PinDecision(
            action="swap",
            src_lift_idx=src_lift_idx,
            dst_lift_idx=dst_lift_idx,
            swap_with_idx=lift_positions[src_lift_idx],
            **common,
        )

    # Non-lifting target (rest/cardio/recovery) with a matching lift day.
    # For canonical-cycle splits, use the bro_canonical_swap path so
    # the new lift positions get re-canonicalized.
    if src_lift_idx is not None and dst_lift_idx is None:
        cycle = _canonical_cycle_for_split(preferred_split)
        if cycle is not None and base_focus in cycle:
            src_orig = lift_positions[src_lift_idx]
            new_lift_positions = sorted(
                [p for p in lift_positions if p != src_orig] + [target_idx]
            )
            new_target_lift_idx = new_lift_positions.index(target_idx)
            new_lift_days = _canonical_pin_rotation(
                lift_days, new_target_lift_idx, base_focus, cycle,
            )
            if new_lift_days is not None:
                # Same clobber check as the canonical-rebuild path —
                # bro_canonical_swap also rebuilds the lift sequence
                # and can clobber prior pins.
                if not _rebuild_clobbers_existing_pins(
                    new_lift_positions, new_lift_days, target_idx, pins
                ):
                    return PinDecision(
                        action="bro_canonical_swap",
                        src_lift_idx=src_lift_idx,
                        dst_lift_idx=None,
                        swap_with_idx=src_orig,
                        rotated_lift_days=new_lift_days,
                        **common,
                    )
                # Fall through to plain swap below.
        return PinDecision(
            action="swap",
            src_lift_idx=src_lift_idx,
            swap_with_idx=lift_positions[src_lift_idx],
            **common,
        )

    # Case 3: focus not in this split. Caller must regen with the
    # split that natively contains this focus.
    forced_split = SPLIT_FOR_FOCUS.get(base_focus)
    if forced_split and forced_split != (preferred_split or "auto"):
        return PinDecision(
            action="regen",
            regen_split=forced_split,
            regen_match_focus=base_focus,
            **common,
        )

    # Case 4: nothing to swap, nothing to regen — last resort label-only.
    return PinDecision(
        action="label_only",
        **common,
    )


def apply_rotate(days: list[dict], decision: PinDecision, session_minutes: int = 45) -> list[dict]:
    """Apply a `rotate` decision in place and return the mutated list.

    Iterates the original lift_positions and overwrites them with the
    rotated lift days from the decision. Non-lifting positions are
    untouched.

    `_overflow_recovery` sentinels (emitted by `_canonical_pin_rotation`
    when bro has more lift slots than its 5-cycle can fill without
    duplicates) are swapped for fresh recovery-day stubs.
    """
    if decision.action != "rotate":
        return days
    lift_positions = [
        idx for idx, d in enumerate(days)
        if normalize_focus(d.get("focus") or "") not in NON_LIFTING_FOCUSES
    ]
    for pos, orig_idx in enumerate(lift_positions):
        new_day = decision.rotated_lift_days[pos]
        if new_day.get("_overflow_recovery"):
            from app.services.workout.planner import generate_recovery_day
            days[orig_idx] = generate_recovery_day(session_minutes)
        else:
            days[orig_idx] = new_day
    return days


def apply_swap(days: list[dict], decision: PinDecision) -> list[dict]:
    """Apply a `swap` decision in place. Swaps two positions in the
    day list — typically a non-lifting day with a lifting day."""
    if decision.action != "swap" or decision.swap_with_idx is None:
        return days
    a, b = decision.target_idx, decision.swap_with_idx
    days[a], days[b] = days[b], days[a]
    return days


def apply_bro_canonical_swap(days: list[dict], decision: PinDecision, session_minutes: int = 45) -> list[dict]:
    """Apply a `bro_canonical_swap` decision. The non-lifting day at
    `swap_with_idx` (the original position of the matched lift day)
    moves to the OLD non-lifting slot's position; lift positions are
    repopulated from `rotated_lift_days` in canonical order.

    This is the bro equivalent of `apply_swap` for cases where simple
    swap would break the canonical cycle.
    """
    if decision.action != "bro_canonical_swap":
        return days
    target_idx = decision.target_idx
    src_orig_idx = decision.swap_with_idx
    if src_orig_idx is None:
        return days
    # The day currently at target_idx (non-lifting) moves to where
    # the matched lift day was.
    non_lifting_day = days[target_idx]
    # Compute new lift positions: swap target_idx in, src_orig out.
    old_lift_positions = [
        idx for idx, d in enumerate(days)
        if normalize_focus(d.get("focus") or "") not in NON_LIFTING_FOCUSES
    ]
    new_lift_positions = sorted(
        [p for p in old_lift_positions if p != src_orig_idx] + [target_idx]
    )
    # Place rotated_lift_days at new_lift_positions in order. Swap
    # bro overflow sentinels for fresh recovery stubs.
    for slot_idx, new_day in zip(new_lift_positions, decision.rotated_lift_days):
        if new_day.get("_overflow_recovery"):
            from app.services.workout.planner import generate_recovery_day
            days[slot_idx] = generate_recovery_day(session_minutes)
        else:
            days[slot_idx] = new_day
    # Place the displaced non-lifting day at src_orig_idx.
    days[src_orig_idx] = non_lifting_day
    return days
