"""Pure-function Switch Day pin/rotation logic.

Extracted from `routers/workouts.py::generate_full_week` so the rotation
rules can be unit-tested without DB, auth, or HTTP. The router still
owns IO (regen with forced split, generate cardio finisher) and passes
callbacks for those side-effecting steps; everything else lives here.

Five outcomes for a pin:
  - `noop`        — target day already matches the requested focus.
  - `rotate`      — target is a lift slot; circularly rotate the
                    lifting sub-sequence by minimum distance so the
                    requested focus lands at target_idx.
  - `swap`        — target is a non-lifting slot (rest/cardio/recovery)
                    and a matching lift exists; swap the two slots.
  - `regen`       — focus isn't in the current split; needs a fresh
                    plan with `preferred_split` forced. Returns a
                    PinDecision with `regen_split` set; caller runs
                    the regen and applies the result.
  - `replace_day` — target should become a fresh recovery / mobility /
                    cardio day generated by the planner. Returns the
                    target index + the day type; caller generates and
                    assigns.
"""
from __future__ import annotations

from dataclasses import dataclass, field
from typing import Literal, Optional


PinAction = Literal["noop", "rotate", "swap", "bro_canonical_swap", "regen", "replace_day", "label_only"]
DayKind = Literal["recovery", "mobility", "cardio"]

NON_LIFTING_FOCUSES: frozenset[str] = frozenset({
    "mobility", "recovery", "active recovery", "stretching",
    "cardio", "conditioning", "mobility_flow", "recovery_easy",
})

# Map a fine focus name → the split that natively contains it.
# Used when the user pins a day to a focus that isn't in the current
# split (e.g. "Push" on a U/L plan); the caller regenerates with
# preferred_split forced to the mapped split, then lifts the matching
# day's exercises into the target slot.
SPLIT_FOR_FOCUS: dict[str, str] = {
    "push": "ppl",
    "pull": "ppl",
    "legs": "ppl",
    "upper": "upper_lower",
    "lower": "upper_lower",
    "full body": "full_body",
    "full_body": "full_body",
    "chest": "bro",
    "back": "bro",
    "shoulders": "bro",
    "arms": "bro",
}


# Canonical bro cycle. Used by `_bro_canonical_pin` to compute the
# correct rotation when n_lifts > 5 (where a focus appears twice and
# simple array rotation produces back-to-back duplicates).
BRO_CYCLE = ["chest", "back", "shoulders", "arms", "legs"]


def _bro_canonical_pin(
    lift_days: list[dict],
    target_lift_idx: int,
    focus_name: str,
) -> list[dict] | None:
    """Compute a bro lift sequence where the requested focus lands at
    target_lift_idx and the full sequence is a valid contiguous slice
    of the canonical Chest→Back→Shoulders→Arms→Legs cycle.

    Returns the new lift_days list, or None if the requested focus
    isn't a canonical bro focus (caller falls through).

    Why bro needs this special case: bro 6d/7d recipes have a focus
    repeat (Chest appears twice in [Chest, Back, Shoulders, Arms,
    Legs, Chest]). Rotating the array shifts content but breaks the
    cycle — produces e.g. [Chest, Chest, Back, ...] with back-to-back
    duplicates. Building the new sequence from the canonical cycle
    instead preserves the cycle's spacing and re-uses existing day
    content (exercises) by focus name.
    """
    focus_lo = focus_name.lower().strip().replace(" + cardio", "").strip()
    if focus_lo not in BRO_CYCLE:
        return None
    canonical_idx = BRO_CYCLE.index(focus_lo)
    n = len(lift_days)

    # Group existing lift_days by focus so we can reuse exercise
    # content. Each focus may have 1 or 2 days (bro 6d has 2 chest).
    by_focus: dict[str, list[dict]] = {}
    for d in lift_days:
        df = normalize_focus(d.get("focus") or "").replace(" + cardio", "").strip()
        if df in BRO_CYCLE:
            by_focus.setdefault(df, []).append(d)

    if not by_focus:
        return None

    new_lift_days: list[dict] = []
    used: dict[str, int] = {f: 0 for f in BRO_CYCLE}
    for i in range(n):
        # Output position i corresponds to canonical position offset
        # from canonical_idx by (i - target_lift_idx).
        canon_pos = (canonical_idx + (i - target_lift_idx)) % 5
        wanted = BRO_CYCLE[canon_pos]
        pool = by_focus.get(wanted, [])
        if used[wanted] < len(pool):
            new_lift_days.append(pool[used[wanted]])
            used[wanted] += 1
        elif pool:
            # Need a duplicate of this focus but original recipe had
            # only one — reuse the first. Acceptable for bro since
            # the user is reorganizing, not generating new content.
            new_lift_days.append(pool[0])
        else:
            # This canonical focus isn't in the original recipe at
            # all — shouldn't happen for canonical bro recipes since
            # every focus appears at least once at n_lifts >= 5.
            return None
    return new_lift_days


@dataclass
class PinDecision:
    """The pin algorithm's output. Caller mutates `days` accordingly."""
    action: PinAction
    target_idx: int
    # rotate: shift the lifting sub-sequence by this many positions.
    # swap: swap days[target_idx] with days[swap_with_idx].
    # noop: nothing to do.
    src_lift_idx: Optional[int] = None
    dst_lift_idx: Optional[int] = None
    swap_with_idx: Optional[int] = None
    rotation_shift: Optional[int] = None
    rotated_lift_days: list[dict] = field(default_factory=list)
    # regen: caller must regen a plan with this preferred_split, then
    # find a day whose focus matches `regen_match_focus` (or the
    # already-with-cardio variant) and put it at target_idx.
    regen_split: Optional[str] = None
    regen_match_focus: Optional[str] = None
    # replace_day: caller generates a recovery/mobility/cardio day
    # and assigns it to days[target_idx].
    day_kind: Optional[DayKind] = None
    # Whether the requested focus came in with a cardio finisher
    # suffix (" + Cardio"). After the primary action, caller may need
    # to append a cardio finisher exercise to the target day.
    wants_cardio_finisher: bool = False
    base_focus: str = ""
    full_focus: str = ""


def normalize_focus(focus: str) -> str:
    return (focus or "").lower().strip()


def split_lifting_focus(focus: str) -> tuple[str, bool]:
    """Return (base_focus_lowercased, wants_cardio_finisher).

    "Push + Cardio" → ("push", True). "Push" → ("push", False).
    """
    lo = normalize_focus(focus)
    if " + cardio" in lo:
        return lo.replace(" + cardio", "").strip(), True
    return lo, False


def _classify_target(focus: str) -> Optional[DayKind]:
    """Special-case targets that map straight to a fresh planner day."""
    lo = normalize_focus(focus)
    if lo in ("recovery", "active recovery"):
        return "recovery"
    if lo in ("mobility", "stretching"):
        return "mobility"
    if lo == "cardio":
        return "cardio"
    return None


def _pick_closest(
    matches: list[int],
    *,
    dst_lift_idx: Optional[int],
    target_idx: int,
    lift_positions: list[int],
) -> Optional[int]:
    """Pick the match closest to the target. For lifting targets, distance
    is in the lift-day sequence (minimizes rotation). For non-lifting
    targets, distance is in the full day-of-week sequence (minimizes
    swap displacement)."""
    if not matches:
        return None
    if dst_lift_idx is not None:
        return min(matches, key=lambda li: abs(li - dst_lift_idx))
    return min(matches, key=lambda li: abs(lift_positions[li] - target_idx))


def decide_pin(
    days: list[dict],
    *,
    pin_day_index: int,
    pin_focus: str,
    preferred_split: Optional[str] = None,
) -> PinDecision:
    """Compute the action needed to honor a Switch Day pin. Pure — no
    side effects. Returns a PinDecision the caller applies."""
    target_idx = max(0, min(len(days) - 1, int(pin_day_index)))
    full_focus = normalize_focus(pin_focus)
    base_focus, wants_cardio_finisher = split_lifting_focus(pin_focus)

    # Recovery / Mobility / Cardio → caller generates a fresh day.
    day_kind = _classify_target(pin_focus)
    if day_kind is not None:
        return PinDecision(
            action="replace_day",
            target_idx=target_idx,
            day_kind=day_kind,
            wants_cardio_finisher=False,
            base_focus=base_focus,
            full_focus=full_focus,
        )

    lift_positions: list[int] = []
    lift_days: list[dict] = []
    for idx, d in enumerate(days):
        if normalize_focus(d.get("focus") or "") not in NON_LIFTING_FOCUSES:
            lift_positions.append(idx)
            lift_days.append(d)

    dst_lift_idx = (
        lift_positions.index(target_idx)
        if target_idx in lift_positions else None
    )

    exact_matches = [
        li for li, ld in enumerate(lift_days)
        if normalize_focus(ld.get("focus") or "") == full_focus
    ]
    src_lift_idx = _pick_closest(
        exact_matches,
        dst_lift_idx=dst_lift_idx,
        target_idx=target_idx,
        lift_positions=lift_positions,
    )

    # Symmetric base-focus fallback: matches lift days whose focus has
    # the SAME BASE as the requested focus, ignoring "+ Cardio" suffix
    # and "— Variant" trailers in BOTH directions.
    #
    # Examples:
    #   pin "Push" + recipe has "Push + Cardio"  → match (rotate it in)
    #   pin "Push + Cardio" + recipe has "Push"  → match (rotate +
    #     cardio-finisher promotion adds the finisher)
    #   pin "Push" + recipe has "Push — Heavy"   → match
    #
    # Without this, plans that the planner produced with PLUS_CARDIO
    # promotion silently fall through to label-only and the user sees
    # no rotation when picking the plain focus name.
    if src_lift_idx is None:
        def _base_of(focus_str: str) -> str:
            f = normalize_focus(focus_str).replace(" + cardio", "").strip()
            if " — " in f:
                f = f.split(" — ")[0].strip()
            return f
        base_matches = [
            li for li, ld in enumerate(lift_days)
            if _base_of(ld.get("focus") or "") == base_focus
        ]
        src_lift_idx = _pick_closest(
            base_matches,
            dst_lift_idx=dst_lift_idx,
            target_idx=target_idx,
            lift_positions=lift_positions,
        )

    common = dict(
        target_idx=target_idx,
        wants_cardio_finisher=wants_cardio_finisher,
        base_focus=base_focus,
        full_focus=full_focus,
    )

    # Single-day swap model. Pin day X to focus Y → swap days[X] with
    # the closest lift day whose focus matches Y. Every other day in
    # the week is byte-identical to the original.
    #
    # Why not whole-week rotation: rotating shifts content across days
    # the user didn't touch (pin day 3 → Push could move Legs onto day
    # 0). Users found this confusing and surprising. Single-day swap
    # matches the mental model "I tapped this day, it changed."
    #
    # Tradeoff: successive pins can break split balance (e.g. pin two
    # days to Push). Acceptable — the user explicitly chose. The next
    # full regen restores balance via the planner.
    if src_lift_idx is not None and dst_lift_idx is not None:
        if src_lift_idx == dst_lift_idx:
            return PinDecision(
                action="noop",
                src_lift_idx=src_lift_idx,
                dst_lift_idx=dst_lift_idx,
                **common,
            )
        return PinDecision(
            action="swap",
            src_lift_idx=src_lift_idx,
            dst_lift_idx=dst_lift_idx,
            swap_with_idx=lift_positions[src_lift_idx],
            **common,
        )

    # Non-lifting target (rest/cardio/recovery) with a matching lift day.
    # Same single-day swap: target gets the lift day, src gets the
    # non-lifting day. Lift count preserved.
    if src_lift_idx is not None and dst_lift_idx is None:
        return PinDecision(
            action="swap",
            src_lift_idx=src_lift_idx,
            swap_with_idx=lift_positions[src_lift_idx],
            **common,
        )

    # Case 3: focus not in this split. Caller must regen with the
    # split that natively contains this focus.
    forced_split = SPLIT_FOR_FOCUS.get(base_focus)
    if forced_split and forced_split != (preferred_split or "auto"):
        return PinDecision(
            action="regen",
            regen_split=forced_split,
            regen_match_focus=base_focus,
            **common,
        )

    # Case 4: nothing to swap, nothing to regen — last resort label-only.
    return PinDecision(
        action="label_only",
        **common,
    )


def apply_rotate(days: list[dict], decision: PinDecision) -> list[dict]:
    """Apply a `rotate` decision in place and return the mutated list.

    Iterates the original lift_positions and overwrites them with the
    rotated lift days from the decision. Non-lifting positions are
    untouched.
    """
    if decision.action != "rotate":
        return days
    # Reconstruct lift_positions from the days list — they're stable
    # because the rotate action doesn't change which positions are
    # lifting (rotation only moves contents around within those slots).
    lift_positions = [
        idx for idx, d in enumerate(days)
        if normalize_focus(d.get("focus") or "") not in NON_LIFTING_FOCUSES
    ]
    for pos, orig_idx in enumerate(lift_positions):
        days[orig_idx] = decision.rotated_lift_days[pos]
    return days


def apply_swap(days: list[dict], decision: PinDecision) -> list[dict]:
    """Apply a `swap` decision in place. Swaps two positions in the
    day list — typically a non-lifting day with a lifting day."""
    if decision.action != "swap" or decision.swap_with_idx is None:
        return days
    a, b = decision.target_idx, decision.swap_with_idx
    days[a], days[b] = days[b], days[a]
    return days


def apply_bro_canonical_swap(days: list[dict], decision: PinDecision) -> list[dict]:
    """Apply a `bro_canonical_swap` decision. The non-lifting day at
    `swap_with_idx` (the original position of the matched lift day)
    moves to the OLD non-lifting slot's position; lift positions are
    repopulated from `rotated_lift_days` in canonical order.

    This is the bro equivalent of `apply_swap` for cases where simple
    swap would break the canonical cycle.
    """
    if decision.action != "bro_canonical_swap":
        return days
    target_idx = decision.target_idx
    src_orig_idx = decision.swap_with_idx
    if src_orig_idx is None:
        return days
    # The day currently at target_idx (non-lifting) moves to where
    # the matched lift day was.
    non_lifting_day = days[target_idx]
    # Compute new lift positions: swap target_idx in, src_orig out.
    old_lift_positions = [
        idx for idx, d in enumerate(days)
        if normalize_focus(d.get("focus") or "") not in NON_LIFTING_FOCUSES
    ]
    new_lift_positions = sorted(
        [p for p in old_lift_positions if p != src_orig_idx] + [target_idx]
    )
    # Place rotated_lift_days at new_lift_positions in order.
    for slot_idx, new_day in zip(new_lift_positions, decision.rotated_lift_days):
        days[slot_idx] = new_day
    # Place the displaced non-lifting day at src_orig_idx.
    days[src_orig_idx] = non_lifting_day
    return days
