"""Daily + weekly food-signal aggregator.

Inputs: the user's MealItem rows for a date, plus FoodMetadata lookups.
Outputs: a DailyNutritionMetrics row with raw facts + per-category servings.

This service used to derive three "scores" (Gut Support / Food Quality /
Longevity Signals). Those are gone. Food Quality lives in the unified
Nutrition Score now; Gut & Plants is a descriptive insight card. What
remains here is the fact-gathering layer — fiber, added sugar, sodium,
saturated fat, plant diversity, fermented / probiotic / omega-3
servings, seafood / fruit / veg / alcohol / processed-meat / refined-
grain servings, protein source split, and the per-meal protein
distribution used by the Resilience flags.

Raw nutrition rows (MealItem / FoodNutrition) are never mutated.
Everything here is additive and can be regenerated by bumping
METRICS_VERSION or CLASSIFIER_VERSION.
"""

from __future__ import annotations

from dataclasses import dataclass, field
from datetime import date, timedelta
from typing import Any

from sqlmodel import select

from app.models import Meal, MealItem, Food, FoodNutrition, FoodMetadata, DailyNutritionMetrics
from app.services.nutrition.ai_classify import get_or_create_metadata
from app.services.nutrition.food_classifier import CLASSIFIER_VERSION, PLANT_CATEGORY
from app.services.nutrition.meal_history import dedupe_generated_plan_meals

METRICS_VERSION = 3   # bumped at unified-score rewrite (v3 adds tag servings + recovery_flags)


# ── Targets / defaults ───────────────────────────────────────────────────────
FIBER_TARGET_G = 28.0
FIBER_TARGET_PER_1000 = 14.0


@dataclass
class DailyRawSignals:
    calories_total: float
    fiber_total_g: float
    fiber_per_1000_kcal: float
    added_sugar_g: float
    sodium_mg: float
    saturated_fat_g: float
    distinct_plant_foods: int
    fermented_servings: float
    probiotic_servings: float
    omega3_servings: float
    seafood_servings: float
    fruit_servings: float
    vegetable_servings: float
    alcohol_servings: float
    processed_meat_servings: float
    refined_grain_servings: float
    processing_counts: dict[str, int]
    plant_protein_g: float
    animal_protein_g: float
    max_meal_protein_pct: float
    plant_slugs: list[str]
    item_count: int
    classified_item_count: int
    # AI-estimated amount aggregates. Summed as per-serving × servings
    # consumed rather than binary flag hits — so "bone broth, 2 cups"
    # contributes ~20g collagen, not just "1 serving."
    collagen_g: float = 0.0
    probiotic_cfu_billions: float = 0.0
    per_meal_protein: dict[str, float] = field(default_factory=dict)


def compute_daily_metrics(
    db: Any, user_id: int, metric_date: date, *, allow_ai: bool = False,
) -> DailyNutritionMetrics:
    """Compute (or recompute) one day's metrics. Idempotent."""
    raw = _gather_raw_signals(db, user_id, metric_date, allow_ai=allow_ai)

    existing = db.exec(
        select(DailyNutritionMetrics)
        .where(DailyNutritionMetrics.user_id == user_id)
        .where(DailyNutritionMetrics.metric_date == metric_date)
    ).first()

    from datetime import datetime, timezone
    now = datetime.now(timezone.utc)

    if existing:
        row = existing
    else:
        row = DailyNutritionMetrics(user_id=user_id, metric_date=metric_date)
        db.add(row)

    row.metrics_version = METRICS_VERSION
    row.classifier_version_used = CLASSIFIER_VERSION
    row.calories_total = raw.calories_total
    row.fiber_total_g = raw.fiber_total_g
    row.fiber_per_1000_kcal = raw.fiber_per_1000_kcal
    row.added_sugar_g = raw.added_sugar_g
    row.sodium_mg = raw.sodium_mg
    row.distinct_plant_foods = raw.distinct_plant_foods
    row.fermented_servings = raw.fermented_servings
    row.probiotic_servings = raw.probiotic_servings
    row.omega3_servings = raw.omega3_servings
    row.collagen_g = raw.collagen_g
    row.probiotic_cfu_billions = raw.probiotic_cfu_billions
    row.seafood_servings = raw.seafood_servings
    row.fruit_servings = raw.fruit_servings
    row.vegetable_servings = raw.vegetable_servings
    row.alcohol_servings = raw.alcohol_servings
    row.processed_meat_servings = raw.processed_meat_servings
    row.refined_grain_servings = raw.refined_grain_servings
    row.plant_protein_g = raw.plant_protein_g
    row.animal_protein_g = raw.animal_protein_g
    row.max_meal_protein_pct = raw.max_meal_protein_pct
    row.processing_counts = raw.processing_counts
    row.saturated_fat_g = raw.saturated_fat_g
    row.plant_slugs = raw.plant_slugs
    row.item_count = raw.item_count
    row.classified_item_count = raw.classified_item_count
    # Legacy score columns stay present in DB but are no longer written. The
    # unified Nutrition Score lives in score_builder.py / /meals/score.
    row.gut_support_score = 0
    row.food_quality_score = 0
    row.longevity_signals_score = 0
    row.updated_at = now

    db.commit()
    db.refresh(row)
    return row


def compute_weekly_rollup(db: Any, user_id: int, end_date: date, *, days: int = 7) -> dict:
    """7-day descriptive summary. Does NOT recompute days — callers should
    ensure the backfill (or per-log hook) has populated DailyNutritionMetrics."""
    start = end_date - timedelta(days=days - 1)
    rows = db.exec(
        select(DailyNutritionMetrics)
        .where(DailyNutritionMetrics.user_id == user_id)
        .where(DailyNutritionMetrics.metric_date >= start)
        .where(DailyNutritionMetrics.metric_date <= end_date)
        .order_by(DailyNutritionMetrics.metric_date.asc())
    ).all()

    if not rows:
        return _empty_rollup(days)

    n = len(rows)
    weekly_slugs: set[str] = set()
    for r in rows:
        for s in (r.plant_slugs or []):
            weekly_slugs.add(s)

    days_hitting_fiber = sum(1 for r in rows if r.fiber_total_g >= FIBER_TARGET_G)

    proc_totals: dict[str, int] = {}
    for r in rows:
        for bucket, count in (r.processing_counts or {}).items():
            proc_totals[bucket] = proc_totals.get(bucket, 0) + int(count)

    def _avg(field_name: str) -> float:
        return round(sum(getattr(r, field_name) or 0 for r in rows) / n, 1)

    plant_p_sum = sum((getattr(r, "plant_protein_g", 0) or 0) for r in rows)
    animal_p_sum = sum((getattr(r, "animal_protein_g", 0) or 0) for r in rows)
    total_p = plant_p_sum + animal_p_sum
    plant_protein_pct = round(100 * plant_p_sum / total_p) if total_p > 0 else 0

    # Calorie stability: coefficient of variation over logged days (0-1).
    # Low CV = steady eating; high CV = big swings. Feeds the LEA flag.
    cals = [float(r.calories_total or 0) for r in rows if (r.calories_total or 0) > 0]
    if len(cals) >= 2:
        mean_cal = sum(cals) / len(cals)
        variance = sum((c - mean_cal) ** 2 for c in cals) / len(cals)
        stdev = variance ** 0.5
        cv = (stdev / mean_cal) if mean_cal > 0 else 0.0
    else:
        cv = 0.0

    return {
        "days_with_data": n,
        "window_days": days,
        "avg_calories": _avg("calories_total"),
        "avg_fiber_g": _avg("fiber_total_g"),
        "avg_fiber_per_1000_kcal": _avg("fiber_per_1000_kcal"),
        "avg_added_sugar_g": _avg("added_sugar_g"),
        "avg_sodium_mg": _avg("sodium_mg"),
        "avg_saturated_fat_g": _avg("saturated_fat_g"),
        "pct_days_fiber_target": round(100 * days_hitting_fiber / n, 0),
        "distinct_plant_foods_week": len(weekly_slugs),
        "fermented_servings": round(sum((r.fermented_servings or 0) for r in rows), 1),
        "probiotic_servings": round(sum((getattr(r, "probiotic_servings", 0) or 0) for r in rows), 1),
        "omega3_servings": round(sum((r.omega3_servings or 0) for r in rows), 1),
        # AI-estimated nutrients USDA doesn't carry. Summed from
        # per-food per-serving × servings consumed.
        "collagen_g": round(sum((getattr(r, "collagen_g", 0) or 0) for r in rows), 1),
        "avg_collagen_g": round(sum((getattr(r, "collagen_g", 0) or 0) for r in rows) / n, 1),
        "seafood_servings": round(sum((getattr(r, "seafood_servings", 0) or 0) for r in rows), 1),
        "fruit_servings": round(sum((getattr(r, "fruit_servings", 0) or 0) for r in rows), 1),
        "vegetable_servings": round(sum((getattr(r, "vegetable_servings", 0) or 0) for r in rows), 1),
        "alcohol_servings": round(sum((getattr(r, "alcohol_servings", 0) or 0) for r in rows), 1),
        "processed_meat_servings": round(sum((getattr(r, "processed_meat_servings", 0) or 0) for r in rows), 1),
        "refined_grain_servings": round(sum((getattr(r, "refined_grain_servings", 0) or 0) for r in rows), 1),
        # Raw sums kept for backwards-compat with old clients.
        "plant_protein_g": round(plant_p_sum, 1),
        "animal_protein_g": round(animal_p_sum, 1),
        # Daily averages — the UI prefers these so "Xg plant" reads
        # sanely ("10g plant / day" beats "72g plant total over 7 days").
        "avg_plant_protein_g": round(plant_p_sum / n, 1),
        "avg_animal_protein_g": round(animal_p_sum / n, 1),
        "plant_protein_pct": plant_protein_pct,
        "processing_counts": proc_totals,
        "calorie_stability_cv": round(cv, 3),
    }


def _empty_rollup(days: int) -> dict:
    return {
        "days_with_data": 0, "window_days": days,
        "avg_calories": 0.0, "avg_fiber_g": 0.0, "avg_fiber_per_1000_kcal": 0.0,
        "avg_added_sugar_g": 0.0, "avg_sodium_mg": 0.0, "avg_saturated_fat_g": 0.0,
        "pct_days_fiber_target": 0.0,
        "distinct_plant_foods_week": 0,
        "fermented_servings": 0.0, "probiotic_servings": 0.0, "omega3_servings": 0.0,
        "collagen_g": 0.0, "avg_collagen_g": 0.0,
        "seafood_servings": 0.0, "fruit_servings": 0.0, "vegetable_servings": 0.0,
        "alcohol_servings": 0.0, "processed_meat_servings": 0.0, "refined_grain_servings": 0.0,
        "plant_protein_g": 0.0, "animal_protein_g": 0.0, "plant_protein_pct": 0,
        "processing_counts": {},
        "calorie_stability_cv": 0.0,
    }


def _empty_signals() -> DailyRawSignals:
    return DailyRawSignals(
        calories_total=0, fiber_total_g=0, fiber_per_1000_kcal=0,
        added_sugar_g=0, sodium_mg=0, saturated_fat_g=0,
        distinct_plant_foods=0, fermented_servings=0, probiotic_servings=0,
        omega3_servings=0, seafood_servings=0, fruit_servings=0, vegetable_servings=0,
        alcohol_servings=0, processed_meat_servings=0, refined_grain_servings=0,
        processing_counts={}, plant_protein_g=0, animal_protein_g=0,
        max_meal_protein_pct=0, plant_slugs=[], item_count=0, classified_item_count=0,
    )


def _gather_raw_signals(
    db: Any, user_id: int, metric_date: date, *, allow_ai: bool,
) -> DailyRawSignals:
    meals = db.exec(
        select(Meal).where(Meal.user_id == user_id).where(Meal.meal_date == metric_date)
    ).all()
    meal_ids = [m.id for m in meals]
    if not meal_ids:
        return _empty_signals()
    items = db.exec(select(MealItem).where(MealItem.meal_id.in_(meal_ids))).all()
    if not items:
        return _empty_signals()
    items_by_meal: dict[int, list] = {}
    for item in items:
        items_by_meal.setdefault(item.meal_id, []).append(item)
    meals = dedupe_generated_plan_meals(meals, items_by_meal)
    kept_meal_ids = {m.id for m in meals}
    items = [item for item in items if item.meal_id in kept_meal_ids]

    food_ids = [i.food_id for i in items if i.food_id is not None]
    nut_by_food: dict[int, FoodNutrition] = {}
    if food_ids:
        for n in db.exec(select(FoodNutrition).where(FoodNutrition.food_id.in_(food_ids))).all():
            nut_by_food[n.food_id] = n

    calories_total = 0.0
    fiber_total_g = 0.0
    added_sugar_g = 0.0
    sodium_mg = 0.0
    saturated_fat_g = 0.0
    fermented_servings = 0.0
    probiotic_servings = 0.0
    omega3_servings = 0.0
    collagen_g = 0.0
    probiotic_cfu_billions = 0.0
    seafood_servings = 0.0
    fruit_servings = 0.0
    vegetable_servings = 0.0
    alcohol_servings = 0.0
    processed_meat_servings = 0.0
    refined_grain_servings = 0.0
    plant_protein_g = 0.0
    animal_protein_g = 0.0
    processing_counts: dict[str, int] = {}
    plant_slugs: set[str] = set()
    classified_count = 0
    # Per-meal protein totals so we can compute max_meal_protein_pct.
    per_meal_protein: dict[int, float] = {}

    for item in items:
        calories_total += float(item.calories or 0)
        per_meal_protein[item.meal_id] = (
            per_meal_protein.get(item.meal_id, 0.0) + float(item.protein_g or 0)
        )
        nut = nut_by_food.get(item.food_id) if item.food_id else None
        grams_consumed = float(item.serving_grams or 0)
        # Fallback: derive grams from logged calories when serving_grams
        # is missing. Saved meals / hand-logged items often lack the
        # serving_grams field, which historically zeroed out fiber /
        # sodium / added_sugar for those rows. Keeps the metric
        # honest without forcing every saver to include grams.
        if (
            grams_consumed == 0
            and nut is not None
            and (nut.calories or 0) > 0
            and (nut.reference_grams or 0) > 0
            and (item.calories or 0) > 0
        ):
            grams_consumed = (float(item.calories) / float(nut.calories)) * float(nut.reference_grams)
        if nut and grams_consumed > 0 and nut.reference_grams > 0:
            scale = grams_consumed / float(nut.reference_grams)
            if nut.fiber is not None:
                fiber_total_g += float(nut.fiber) * scale
            if getattr(nut, "added_sugar_g", None) is not None:
                added_sugar_g += float(nut.added_sugar_g) * scale
            if nut.sodium_mg is not None:
                sodium_mg += float(nut.sodium_mg) * scale
            extras = nut.extra_nutrients or {}
            sat = extras.get("saturated_fat")
            if sat is not None:
                try: saturated_fat_g += float(sat) * scale
                except Exception: pass
            # If added_sugar_g wasn't a top-level column, try extras as a fallback.
            if added_sugar_g == 0 and "added_sugar" in extras:
                try: added_sugar_g += float(extras["added_sugar"]) * scale
                except Exception: pass

        meta = get_or_create_metadata(item.food_name, db=db, allow_ai=allow_ai)
        if meta.source != "unknown" or meta.confidence > 0:
            classified_count += 1

        # Servings consumed of this item — used to scale per-serving
        # AI amount estimates. When serving_grams and nut.reference_grams
        # are both known we use that ratio; otherwise assume 1 serving.
        servings_consumed = 1.0
        if nut and grams_consumed > 0 and (nut.reference_grams or 0) > 0:
            servings_consumed = grams_consumed / float(nut.reference_grams)
        servings_consumed = max(0.1, servings_consumed)

        if meta.fermented_flag:
            fermented_servings += 1.0
        # Probiotic aggregation — CFU count (billions) is the real
        # bioactive unit. When the AI estimated CFUs we sum them and
        # also bump the legacy servings count for back-compat with
        # UIs that haven't switched yet. Older rows without CFU fall
        # back to the servings estimate, then the boolean flag.
        cfu_per_serving = getattr(meta, "probiotic_cfu_billions_per_serving", None)
        if cfu_per_serving is not None and cfu_per_serving > 0:
            probiotic_cfu_billions += float(cfu_per_serving) * servings_consumed
            probiotic_servings += 1.0 * servings_consumed
        else:
            pb_per_serving = getattr(meta, "probiotic_servings_per_serving", None)
            if pb_per_serving is not None and pb_per_serving > 0:
                probiotic_servings += float(pb_per_serving) * servings_consumed
                probiotic_cfu_billions += 1.0 * servings_consumed
            elif getattr(meta, "probiotic_flag", False):
                probiotic_servings += 1.0
                probiotic_cfu_billions += 1.0
        # Collagen — purely AI-estimated, no legacy fallback because
        # the column didn't exist before v4.
        col_per_serving = getattr(meta, "collagen_g_per_serving", None)
        if col_per_serving is not None and col_per_serving > 0:
            collagen_g += float(col_per_serving) * servings_consumed
        if meta.omega3_flag:
            omega3_servings += 1.0
        if getattr(meta, "seafood_flag", False):
            seafood_servings += 1.0
        if getattr(meta, "fruit_flag", False):
            fruit_servings += 1.0
        if getattr(meta, "vegetable_flag", False):
            vegetable_servings += 1.0
        if getattr(meta, "alcohol_flag", False):
            alcohol_servings += 1.0
        if getattr(meta, "processed_meat_flag", False):
            processed_meat_servings += 1.0
        if getattr(meta, "refined_grain_flag", False):
            refined_grain_servings += 1.0

        item_protein = float(item.protein_g or 0)
        ps = getattr(meta, "protein_source", "unknown") or "unknown"
        if item_protein > 0:
            if ps == "plant":
                plant_protein_g += item_protein
            elif ps == "animal":
                animal_protein_g += item_protein
            elif ps == "mixed":
                plant_protein_g += item_protein * 0.5
                animal_protein_g += item_protein * 0.5

        bucket = meta.processing_bucket or "unknown"
        processing_counts[bucket] = processing_counts.get(bucket, 0) + 1

        if meta.likely_plant_foods and meta.confidence >= 0.5:
            for slug in meta.likely_plant_foods:
                plant_slugs.add(slug)

    total_protein_day = sum(per_meal_protein.values())
    max_meal_protein_pct = (
        round(100 * max(per_meal_protein.values()) / total_protein_day, 1)
        if per_meal_protein and total_protein_day > 0 else 0.0
    )

    fiber_per_1000 = (fiber_total_g / calories_total * 1000.0) if calories_total > 0 else 0.0

    return DailyRawSignals(
        calories_total=round(calories_total, 1),
        fiber_total_g=round(fiber_total_g, 1),
        fiber_per_1000_kcal=round(fiber_per_1000, 1),
        added_sugar_g=round(added_sugar_g, 1),
        sodium_mg=round(sodium_mg, 1),
        saturated_fat_g=round(saturated_fat_g, 1),
        distinct_plant_foods=len(plant_slugs),
        fermented_servings=fermented_servings,
        probiotic_servings=round(probiotic_servings, 2),
        omega3_servings=omega3_servings,
        collagen_g=round(collagen_g, 1),
        probiotic_cfu_billions=round(probiotic_cfu_billions, 1),
        seafood_servings=seafood_servings,
        fruit_servings=fruit_servings,
        vegetable_servings=vegetable_servings,
        alcohol_servings=alcohol_servings,
        processed_meat_servings=processed_meat_servings,
        refined_grain_servings=refined_grain_servings,
        processing_counts=processing_counts,
        plant_protein_g=round(plant_protein_g, 1),
        animal_protein_g=round(animal_protein_g, 1),
        max_meal_protein_pct=max_meal_protein_pct,
        plant_slugs=sorted(plant_slugs),
        item_count=len(items),
        classified_item_count=classified_count,
        per_meal_protein={str(k): round(v, 1) for k, v in per_meal_protein.items()},
    )
